### ISSUE TITLE
Custom inline text tag

### ISSUE THREAD

**Issue by JungleCatSW** [archriss/react-native-render-html#100]
Hi I am trying to style a custom tag, it is an inline text tag. and uses the **wrapper: 'Text'** to be added to the renderer.

The problem is that the **fontSize** attribute is not having any effect, but font weight bold does work.

If this is a bug is there a way to set the default size for all the text in the html view?

```js
function appLinkRenderer(htmlAttribs, children, convertedCSSStyles, passProps) {
  return (
    <Text
      style={{ fontSize: 18, fontWeight:'bold' }}
      onPress={() => { onPressAppTag(htmlAttribs); }}
    >
      {children}
    </Text>
  );
}
```

**Comment by Exilz** [comment]
Hi,
you can use `baseFontStyle ` to style all texts rendered from your HTML.

If it's not working for you in your custom renderer, please provide the HTML you're trying to render and the props you're using.

**Comment by JungleCatSW** [comment]
Thanks that worked great!

**Comment by pxmage** [comment]
> Hi,
> you can use `baseFontStyle ` to style all texts rendered from your HTML.
> 
> If it's not working for you in your custom renderer, please provide the HTML you're trying to render and the props you're using.
@Exilz 
What if I want specify **fontSize** of different element individually ? They all have different **fontSize**.
