### ISSUE TITLE
Measure the position of custom renderers element

### ISSUE THREAD

**Issue by baona95** [archriss/react-native-render-html#103]
So I have `<HTML />` component inside a `ScrollView`
I want to scroll to some node parsed by `<HTML renderers={} />` using this method https://facebook.github.io/react-native/docs/direct-manipulation.html#measurecallback

The code as below

```
renderers = {
      note: {
        wrapper: 'Text',
        renderer: (htmlAttribs) => 
          <Text key={htmlAttribs.id}
          ref={note => { this.refCache['note' + htmlAttribs.id] = note; }}
          onLayout={null}
          collapsable={false}>
            <FontAwesome 
              style={this.state.preset.font}>
              {Icons.stickyNote}
            </FontAwesome>
          </Text>
      }
    };
``` 

```
// this.refCache['note' + noteId] defined
this.refCache['note' + noteId].measure((x, y, width, height, pageX, pageY) => {
      // ...undefined
      console.log(x, y, width, height, pageY, pageY);
    });
```

But arguments in callback always undefined. I'm trying to figure it out.

There is some issues like this but I've tried all solutions without working https://github.com/facebook/react-native/issues/3282

Anyone has ever done this?

**Comment by kesha-antonov** [comment]
Hi @baoanhng 
How did you solve it?
