### ISSUE TITLE
[ANDROID] Unsupported Style : line-height

### ISSUE THREAD

**Issue by LouisJS** [archriss/react-native-render-html#108]
I have this html :
```
<p style=\"margin:0cm 0cm 8pt\"><span style=\"font-size:11pt\"><span style=\"line-height:107%\"><span style='font-family:\"Calibri\",sans-serif'>If ignition fails a second time, a warning message will appear on control panel.</span></span></span></p>
```

And i get error on Android which is :
```
Error while updating property 'lineHeight' in shadow node of type : RCTVirtualText
TypeError: expected dynamic type `double`, but had type `string`
```

I did ignore this style for now to avoid any mistake, but that would be great to have support for this.
Thanks for your time.

**Comment by Exilz** [comment]
Hi, which version of the plugin are you running ? I can't reproduce your issue with the latest one. This seems like something I fixed a little while ago.

**Comment by chixpc123** [comment]
Any update??

**Comment by Exilz** [comment]
@chixpc123 please try PR #117, I couldn't get a look at it yet.

Please review this change in the PR's thread so @mchudy is kept up to date.

**Comment by Exilz** [comment]
I'll assume this is fixed, please re-open an issue if you encounter this error again.

**Comment by SirishaBellam** [comment]
Failed prop type: Invalid prop `lineHeight` of type `string` supplied to `Text`, expected `number`.
Bad object: {
  "fontSize": 9.1,
  "lineHeight": "normal"
}

Having the same issue.
