### ISSUE TITLE
Link of url can't click 

### ISSUE THREAD

**Issue by bhiantara** [archriss/react-native-render-html#109]
i got a problem with link url, 
the url is showing in page component but can't clicking or directing open browser 
how to solve this issue?

**Comment by Exilz** [comment]
Please show us your code, we can't help you with so little information.

**Comment by bhiantara** [comment]
` <Container style={{paddingLeft: 10, paddingRight:10, flex: 1}}>
                        <HTML html={this.state.data.htmlcontent} imagesMaxWidth={win}/>
  </Container>`

this is my code , my app get html content from my API , 
my content html  include tag link `<a href ...  >downlad</a>`
but  url  link download cant clicking...   
what is wrong?

**Comment by Exilz** [comment]
Nothing wrong with that code, please copy/paste the HTML you're rendering.

**Comment by LouisJS** [comment]
You probably want to take a look at : `onLinkPress`
You can implement it such as : `onLinkPress: (evt, href) => { Linking.openURL(href); }`

**Comment by bhiantara** [comment]
@LouisJS Oh.. Thanks work it..

**Comment by donni106** [comment]
I asked myself the same question. Thanks.

So for others: Linking is not default, if there are `<a...>` in your HTML, you have to implement `onLinkPress `.

**Comment by tkserver** [comment]
How does one "implement onLinkPress?

**Comment by tkserver** [comment]
Answered my own question by looking at the demo here: https://goo.gl/ewkqXx

**Comment by vikram-kodag** [comment]
> You probably want to take a look at : `onLinkPress`
> You can implement it such as : `onLinkPress: (evt, href) => { Linking.openURL(href); }`

import {Linking } from 'react-native';

**Comment by infinitbility** [comment]
Implement link in react native render Html complete example

https://infinitbility.com/how-to-open-any-link-from-react-native-render-html

**Comment by florinrelea** [comment]
```
import RenderHtml from 'react-native-render-html'
...

<RenderHtml
  renderersProps={{
    a: {
      onPress: (evt, href) => {
        Linking.openURL(href)
      }
    }
  }}
/>
```

**Comment by iphonic** [comment]
> ```
> import RenderHtml from 'react-native-render-html'
> ...
> 
> <RenderHtml
>  renderersProps={{
>    a: {
>      onPress: (evt, href) => {
>        Linking.openURL(href)
>      }
>    }
>  }}
> />
> ```

Is there any way to access this.state or this.props inside the  `renderersProps` definition?

**Comment by florinrelea** [comment]
> > ```
> > import RenderHtml from 'react-native-render-html'
> > ...
> > 
> > <RenderHtml
> >  renderersProps={{
> >    a: {
> >      onPress: (evt, href) => {
> >        Linking.openURL(href)
> >      }
> >    }
> >  }}
> > />
> > ```
> 
> Is there any way to access this.state or this.props inside the `renderersProps` definition?

I did not try that but this should work:
```
class Example extends React.Component {
  ...
  render() {
    const { state, props }  = this

    return (
      <RenderHtml
         renderersProps={{
           a: {
             onPress: (evt, href) => {
               // Use state & props
               const foo = state.bar
             }
           }
         }}
      />
    )
  }
}
```
