### ISSUE TITLE
Question: Able to exclude some elements from incoming html 

### ISSUE THREAD

**Issue by nwkeeley** [archriss/react-native-render-html#11]
Hi - Love your app its greater for displaying the content that we are receiving from a rich text editor. 

I am using Expo.io and as such I need to load all the font prior to the app starting. I am pulling in some rich text and I am getting an error that I've not loaded the Verdana system font. The problem I am facing is that I don't know what fonts may exist within these rich content snippets. 

What I would like to do is strip out all fontStyle from the rich text. Is there a way with react-native-render-html to say that I do not want any fontFamily styles but still render things like paragraphs, bullets etc.

Thanks for the great work!

**Comment by Exilz** [comment]
Hi, thanks for the feedback.

This is an interesting question. It'd be great to implement some kind of filter as a prop to be able to exclude some styles directly, yeah.

In the meantime, you should be able to get rid of these errors by implementing custom renderers for each of your HTML tags that might have these fonts. It's quite cumbersome, but it should do the trick.

You can access `htmlAttribs, children & passProps` in the function of your renderer so I guess you will be able to achieve what you want that way.

**Comment by Exilz** [comment]
Hi again,
I'm currently working a big release including many features.

Once the first release candidate of `v2.0.0` is out, you'll be able to ignore specific CSS styles with the `ignoredStyles` prop. You'll be able to test it soon.

**Comment by Exilz** [comment]
This feature is now available in `3.0.0`, check out the [3 available props](https://github.com/archriss/react-native-render-html#ignoring-html-content)
