### ISSUE TITLE
Error when "font-weight" is present on html

### ISSUE THREAD

**Issue by bbicudo** [archriss/react-native-render-html#111]
Whenever i try to render a page which contains font-Weight, i get the following error:

Warning: Failed prop type: Invalid prop `fontWeight` of value `400` supplied to `Text`, expected one of ["normal","bold","100","200","300","400","500","600","700","800","900"].
Bad object: {
  "marginTop": 14,
  "marginBottom": 14,
  "fontWeight": 400
}
    in Text (at HTML.js:460)

**Comment by arnsa** [comment]
400 has to be a string, not a number.

**Comment by Exilz** [comment]
This plugin is supposed to handle the conversion automatically.
Please show us the HTML you're trying to render and the props you're using.

**Comment by marcin-chudy** [comment]
I stumbled upon a weird issue which caused this error in the following HTML:
```html
<h5><strong>Text <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Small-world-network-example.png/220px-Small-world-network-example.png" alt="sample_image" /></strong></h5>
```
with `fontWeight: '500'` set in `tagStyles` for both `h5` and `strong`.

After removing `<strong>` or `<img>` everything works properly. It seems that the string value gets converted to a number in the child `Text` component. I managed to find a hacky way to get around this by modifying source code of this library from https://github.com/archriss/react-native-render-html/blob/60d53598e35f5cf36d89a5c9a526d85a9744288f/src/HTMLStyles.js#L143 to
```js
       if (value.search('px') !== -1 && !isNaN(numericValue)) {
```
I'm not sure if this is the right way to tackle this problem though and if it would not cause some other issues. Do you have any suggestions?

**Comment by roadmanfong** [comment]
Hi, I have this issue too. 
It works good with @marcin-chudy solution.
Do you have any update plan for this, thanks.

**Comment by Exilz** [comment]
Hi,
although @marcin-chudy 's solution works with this case, I'm worried it might impact other styles.

Do you guys think about other rules that are not written with `'px'` but still need to be converted to `number` to be rendered in react-native ?

Since `fontWeight` is different between its css implementation and react-native's one (`string` vs `number`), we might add a specific check just for it and leave all the others rules be.

What do you think ?

**Comment by marcin-chudy** [comment]
@Exilz Yes, you're right - my initial solution would result in problems with other styles like `margin: 3` or `font-size: 12` (without `px`). Filtering just `fontWeight` is enough for now I guess. I'll try to submit a PR later tonight.
