### ISSUE TITLE
font-weight css property not read and parse 

### ISSUE THREAD

**Issue by batuhanorhn** [archriss/react-native-render-html#112]
font-weight css style value integer but styleSheet fontWeight value is string. that's problem

![sad](https://user-images.githubusercontent.com/6142773/36801383-05e1cc28-1cc3-11e8-9ce8-cdd294bb6d3d.jpeg)

**Comment by Exilz** [comment]
Hi, this might be related to #108. Just to be sure, which version of the plugin are you running ?

**Comment by batuhanorhn** [comment]
may be, 

version : 
    "react-native-render-html": "^3.9.0",
    "react-native": "0.52.2",

**Comment by Exilz** [comment]
I'm closing this one since we're already discussing this issue in #108.
