### ISSUE TITLE
Problems with gif rendering

### ISSUE THREAD

**Issue by rodrigobrando** [archriss/react-native-render-html#113]
Hello friends,
I'm having a problem, the animated gifs are static. Is it missing any configuration? It works on the iOS emuldor but not on Android.

**Comment by Exilz** [comment]
Hi, this is not related to the plugin but to react-native itself. Animated gifs are not supported out of the box on Android.
If you need to see them move, you should install a different image component. I use [fast-image](https://github.com/DylanVann/react-native-fast-image) and animated gifs are working great!

**Comment by Temirtator** [comment]
+
