### ISSUE TITLE
Remove use of deprecated component lifecycle APIs

### ISSUE THREAD

**Issue by rhysforyou** [archriss/react-native-render-html#114]
In preparation for async support, React is dropping support for some of the current component lifecycle hooks, notably `componentWillMount`. That means that if you add `react-native-render-html` to a new React Native project, you'll start seeing warnings from components like [HTML](https://github.com/reactjs/rfcs/pull/6) that still use those APIs. It's not going to break anything just yet, but we should stop using these APIs at some point to ensure things keep working.

**Comment by Exilz** [comment]
Thanks for the heads up, once this new major version is ready to rollout, we'll see how we handle deprecated versions of react with this plugin.

**Comment by rhysforyou** [comment]
Great to hear, also worth noting the new static lifecycle methods break backwards compatibility, so it'd be best to save those for a major release.

**Comment by charpeni** [comment]
On a side note, these lifecycles won't be deprecated before React 17.

To prevent a breaking change, you can use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) which provide a polyfill of new lifecycles.

**Comment by Exilz** [comment]
I'll close this issue since this has been reopened with the new contributing guidelines. See #135
