### ISSUE TITLE
Cannot handle style="font-size: 1em;"

### ISSUE THREAD

**Issue by oddzombie** [archriss/react-native-render-html#12]
I have html that has inline styles. this particular one causes an error.
`Error while updating property 'fontSize' in shadow node of type : TCTVirtualText

TypeError: expected dynamic type `double',
but had type `string'

**Comment by Exilz** [comment]
Hi,
I tested it with the latest version and my app isn't crashing, what's your react-native version ?

However, it's not working.

I just added the `em` support, you'll be able to test it once I've published the first release candidate for the next major release.

**Comment by Exilz** [comment]
This feature is now available in `3.0.0`.
