### ISSUE TITLE
img in html producing error

### ISSUE THREAD

**Issue by AishwaryaSurana** [archriss/react-native-render-html#120]
### Is this a bug report or a feature request?
Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?
Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?
Yes

### Have you made sure that your issue hasn't already been reported/solved?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Its reciprocated in both

### Is the bug reproductible in a production environment (not a debug one)?
Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?
Yes

### Environment

  Environment:
    React: 16.0.0-beta.5
    React native: 0.49.2
    react-native-render-html: 3.9.0

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

When I add styles to `<HTML/>` component like:

`<HTML 
                                    html={htmlContent} 
                                    imagesMaxWidth={Dimensions.get('window').width} 
                                    style={{backgroundColor:'#00ffff'}} />`

and html contains img like:
`
const htmlContent='<img src="https://i.imgur.com/dHLmxfO.jpg?2"/>'
            `

than it gives me this error:

![simulator screen shot - iphone 6 - 2018-03-14 at 18 30 07](https://user-images.githubusercontent.com/10483937/37404437-e261e814-27b7-11e8-947f-e0afc0604532.png)

 img to my html content it gives this error

When img is removed everything is working as expected

### Expected Behavior

Image should be shown

### Actual Behavior

Error

**Comment by fvsch** [comment]
I’m getting the same error when using the HTMLImage component directly.

```js
import HTMLImage from 'react-native-render-html/src/HTMLImage'

<HTMLImage source="…" /> // TypeError
<HTMLImage source="…" style={{alignSelf:'center'}} /> // TypeError
<HTMLImage source="…" style={[]} /> // Works
```

**Comment by Exilz** [comment]
Without looking at the code, I guess I assumed we always have an array supplied in `style`, hence `forEach` being undefined.
I don't have time right now to fix this but this should be fairly easy.
