### ISSUE TITLE
CSS Colors using !Important Cause Crash

### ISSUE THREAD

**Issue by paul-hart** [archriss/react-native-render-html#121]
### Is this a bug report or a feature request?

Bug Report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

YES

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

YES

### Have you made sure that your issue hasn't already been reported/solved?

YES

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Only verified on IOS

### Is the bug reproductible in a production environment (not a debug one)?

Red screen only appears in simulator while release builds seem to let it slide. ie "react-native run-ios"

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

YES

### Environment

Environment:
    React: 16.2.0
    React native: 0.52.0
    react-native-render-html: 3.9.0

  Target Platform:
    iOS (11.2 Simulator)

### Steps to Reproduce

1. Create a react native component using react-native-render-html
2. Load a URL that uses CSS that defines colors with !important

### Expected Behavior

The usage of !Important in CSS converts nicely (at least does not crash) to React Native elements.

### Actual Behavior

Red screen of death in iOS simulator with lots of these errors:

Warning: Failed prop type: Invalid prop `color` supplied to `Text`: #333333!important
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

Bad object: {
  "textDecorationLine": "underline",
  "color": "#333333!important",
  "fontFamily": "Helvetica Neue,Helvetica,Arial,Lucida Grande,sans-serif!important",
  "fontSize": 16,
  "lineHeight": 16,
  "paddingTop": 10,
  "fontWeight": 700
}    in Text (at HTMLRenderers.js:21)

...

JSON value '35%!important' of type NSString cannot be converted to a YGValue. Did you forget the % or pt suffix?

...

JSON value '700' of type NSNumber cannot be converted to NSString

**Comment by Exilz** [comment]
Hi,
I think your red screen of death comes from the `fontWeight` style, that has already been fixed and will land in `3.9.1`.

However, `!important` does break the color and raises a yellowbox, but doesn't crash, since react-native is expecting a string anyway.

I'll try to improve this by simply removing all `!important` occurencies from CSS styling, this should do it.

**Comment by paul-hart** [comment]
Had some success doing the following:

1. remove !important from remote HTML:

 let articleHtml = this.props.article !== null ? this._getArticleHtml(this.props.article) : null;
if (articleHtml) {
     articleHtml = articleHtml.replace(/!important;/g, ';');
}

2. Ignore the following:

<HTML ... ignoredStyles={['font-weight', 'display', 'font-family']} ... />

**Comment by Exilz** [comment]
@paul-hart please try the development branch, I added [a small fix](https://github.com/archriss/react-native-render-html/pull/127/commits/06297c1ab9dbd1866f709796ddcd434f62fdc0ef) to address this issue.

**Comment by rebornishard** [comment]
sorry to come to this issue, but without important it also show warning if i use color in html,
i already have this on my db and want to render it
<p style="color:red">this is red</p>
will result in warning
what should i do
