### ISSUE TITLE
 Multi-label elements problem

### ISSUE THREAD

**Issue by cesar-blog** [archriss/react-native-render-html#129]
html = `<em style="color: #fd6600;font-style: normal;">test</em>`
It shows normal;

![image](https://user-images.githubusercontent.com/17369383/37769244-4ce0ac58-2e0b-11e8-8e32-92c8058af21f.png)

html = `<em style="color: #fd6600;font-style: normal;">test</em><em style="color: #fd6600;font-style: normal;">test</em>`  OR any content outside the element like  <em style="color: #fd6600;font-style: normal;">test</em>test
It shows unnormal;

![image](https://user-images.githubusercontent.com/17369383/37769336-a3c61166-2e0b-11e8-8e2b-4af59a829c64.png)

how can i deal with it?

**Comment by Exilz** [comment]
Please follow the guidelines when submitting an issue.
