### ISSUE TITLE
how to twitter iframe render

### ISSUE THREAD

**Issue by mcakmakali** [archriss/react-native-render-html#131]
```
<blockquote class="twitter-tweet tw-align-center" data-lang="en">
<p dir="ltr" lang="tr">23 Nisan Ulusal Egemenlik ve Çocuk Bayramı kutlu olsun <a href="https://twitter.com/hashtag/KalbininSesiniDinle?src=hash">#KalbininSesiniDinle</a> <a href="https://twitter.com/hashtag/23Nisan?src=hash">#23Nisan</a> <a href="https://t.co/XeV3zfKtwN">pic.twitter.com/XeV3zfKtwN</a></p>
— Akbank (@Akbank) <a href="https://twitter.com/Akbank/status/855662454059089921">April 22, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```
Unable to resolve codes above.
how can i solve it.

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
