### ISSUE TITLE
Error "in this environment the sources for assign must be an object" when you pass native style to baseFontStyle

### ISSUE THREAD

**Issue by serhiipalash** [archriss/react-native-render-html#132]
When I pass native styles to `baseFontStyle` prop

```
<HTML
    baseFontStyle={styles.text}
    ...
/>
```

I get this

<img width="377" alt="screen shot 2018-03-27 at 4 25 51 pm" src="https://user-images.githubusercontent.com/14208343/37970286-c9df9dd0-31db-11e8-8ace-ee5882577a5e.png">

<img width="376" alt="screen shot 2018-03-27 at 4 26 01 pm" src="https://user-images.githubusercontent.com/14208343/37970296-cf69de28-31db-11e8-89bd-ba42622d367c.png">

Please replace this
<img width="978" alt="screen shot 2018-03-27 at 4 28 16 pm" src="https://user-images.githubusercontent.com/14208343/37970393-0d5aa578-31dc-11e8-9766-612cdc78fecb.png">

on this
<img width="989" alt="screen shot 2018-03-27 at 4 28 59 pm" src="https://user-images.githubusercontent.com/14208343/37970408-14930fce-31dc-11e8-9d3c-1089099ce34a.png">

I would create pull request by myself, but you have strange repository structure. Why is your master is not your releases branch? Currently dev is published to npm.

**Comment by Exilz** [comment]
Hi,
thanks for telling me I screwed up with the latest npm release... I published the development branch instead of master once again. I really need to set up an automatic deployment somehow.

I published `3.9.3` on npm, which actually is the master branch. Sorry for the mix up.

Please open an issue, the feature you're talking about is supposed to be under development, I'm not surprised you found a bug.

**Comment by serhiipalash** [comment]
Hi!
NP, thanks for you work! This is a great library.

I can help you to setup automatic deployment with CircleIO. It will take 10-15 minutes.

**Comment by Exilz** [comment]
Yes I'd love to set up continuous integration on these repos, I'll look into it once I have some time. I'll definitely give you a shout if I need some help, thanks 😄

**Comment by serhiipalash** [comment]
Ok, write me in this chat or on my public email if you need any help .
