### ISSUE TITLE
Nested Img and Iframe

### ISSUE THREAD

**Issue by LouisJS** [archriss/react-native-render-html#134]
### Is this a bug report or a feature request?

Seems like a Bug.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

I did

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Noth Platforms

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

I didn't try

### Environment

  Environment:
    React: 16.2.0
    React native: 0.52.0
    react-native-render-html: 3.9.3

### The Error

I have this HTML Content

```
<p style="text-align: center;">Notre Collection Made in France propose des modèles fabriqués dans les Vosges, ayant obtenu le label "<strong>Origine France Garantie</strong>"</p>

<p style="text-align: center;"> </p>

<div class="videoEmbed" style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="349" src="https://www.youtube.com/embed/8wpozmL-TRE?color=white&amp;iv_load_policy=3&amp;rel=0&amp;autoplay=1&amp;showinfo=0&amp;modestbranding=1&amp;theme=light&amp;showsearch=0" width="560"></iframe></div>

<p style="text-align: center;"> </p>

<p style="text-align: center;"><img alt="" src="https://hivency-staging.s3.amazonaws.com/uploads/ckeditor/pictures/2/content_Visuel.png" style="width: 659px; height: 800px;"></p>

<p style="text-align: center;"> </p>

<p style="text-align: center;"><strong>Vous souhaitez tester nos lunettes ? Rien de plus simple</strong> :</p>
```

By encapsulating its `iframe` and `img` inside a `p` tag, the `staticContentMaxWidth` and `imagesMaxWidth` are ignored and oversize the width of my screen.
Also, i've had to ignore `textAlign` styling, it throws an error on Android.

I've tried to ignore also `height` and `width`, without success.

**Comment by Exilz** [comment]
Hi,
the `height` and `width` styles passed as HTML attributes take precedence over `staticContentMaxWidth`. I know this is controversial, it might be useful to add a prop to configure this behavior... So your image will be 659px wide anyway.

`imagesMaxWidth` seems to be resizing your image properly, whether it's in a `<p>` or not.

`ignoredStyles={['width']}` also seems to be working on the demo.

The only problem I see here is that the `width` attribute of your `<iframe>`, it's not being ignored by `ignoredStyles` since it's not inside the `style` attribute.

You should be able to circumvent this by using something like this :

```javascript
alterChildren: (node) => {
    if (node.name === 'iframe') {
        delete node.attribs.width;
    }
    return node.children;
}
```

I've tried on iOS and Android.

**Comment by SBogdy** [comment]
Hello! 
I have the same problem, with `staticContentMaxWidth` not working for an `<iframe>` inside a `<p>`. My `<iframe>` has width attribute, so the solutions seems legit.
Being a starter in react-native and javascript, I don't really get where should that code be applied. Can you enlighten me, please?

**Comment by AbodyAmer** [comment]
`                <HTML 
                alterChildren = { (node) => {
                  if (node.name === 'iframe') {
                    console.log('node.attribs.width ' , node.attribs.width)
                      delete node.attribs.width;
                  }
                  return node.children;
              }}
                tagsStyles={paraStyle} 
                html={content.content}
                onLinkPress={ (arg, href) => Linking.openURL(href)}
                textSelectable={ true }
                ignoredStyles={['width']}
                imagesMaxWidth={Dimensions.get('window').width}
                staticContentMaxWidth={Dimensions.get('window').width}
                
                />`

the ifrmae is so small. this is my code, i tried to use the same solution as avove

**Comment by AbodyAmer** [comment]
```
                <HTML 
                alterChildren = { (node) => {
                  if (node.name === 'iframe') {
                    console.log('node.attribs.width ' , node.attribs.width)
                      delete node.attribs.width;
                  }
                  return node.children;
              }}
                tagsStyles={paraStyle} 
                html={content.content}
                onLinkPress={ (arg, href) => Linking.openURL(href)}
                textSelectable={ true }
                ignoredStyles={['width']}
                imagesMaxWidth={Dimensions.get('window').width}
                staticContentMaxWidth={Dimensions.get('window').width}
                
                />
```

this is my code. i tried to copy the above solution but it is not working for me. the iframe is so small

**Comment by Milrer** [comment]
@jsamr Hello ! I have done amazing things thanks to you, thank you for what you do!

The only thing I've been struggling with for the past few days is that when I want to embed an iframe, it doesn't display (and leaves an empty space) if it's embedded inside a paragraph.

If it is not in a paragraph or in a division, it is displayed.

Maybe there is a solution to this?

This works:
`<iframe src='https://www.youtube.com/embed/sX1Y2JMK6g8' allowfullscreen></iframe>`

This does not work:
`<p><iframe src='https://www.youtube.com/embed/sX1Y2JMK6g8' allowfullscreen></iframe></p>`

**Comment by jsamr** [comment]
@Milrer On which version of react-native-render-html this is happening? Which version of the plugin?

**Comment by Milrer** [comment]
Oh sorry for that:
- "react-native-render-html": "^6.0.0-alpha.22",
- "react-native-webview": "^11.0.0",
- "@native-html/iframe-plugin": "^2.2.0"

**Comment by jsamr** [comment]
OK! Share me a snack and I'll be happy to take a look

**Comment by Milrer** [comment]
Great thanks!

Here is the snack: https://snack.expo.io/h9hM6LUMX
There seems to be a problem because on snack, the video doesn't appear either even if it's not in a paragraph, while on the app it works.

**Comment by Milrer** [comment]
@jsamr No worries, thanks

**Comment by jsamr** [comment]
@Milrer I've tried to reproduce again; I believe the issue was that you wrapped `RenderHTML` component into a `Text` element... this is not supported (although I admit undocumented). In this slightly simplified reproduction, it works on both iOS and Android: https://snack.expo.io/@jsamr/project-demonstration-with-iframe-and-react-native-render-html 
As you mentioned, it does not work in Expo Go for whatever reason. But I copy / pasted the reproduction in the example playground of this repository and it worked on both iOS and Android.

**Comment by Milrer** [comment]
@jsamr Wow, indeed, I am quite surprised, the problem was indeed with the Text component.

I thank you very much for helping me to find out where this problem came from, I think it will be very useful for other people who will come across this.

**Comment by Lucashfonseca123** [comment]
@jsamr it's works for me! Thanks.

**Comment by MohamedAhmed122** [comment]
it took while to figured it out, I had the same issue, iframe  doesn't appear and this's how I fixed:

```
import React from 'react';
import { View, StyleSheet, Dimensions } from 'react-native';
import IframeRenderer, { iframeModel } from '@native-html/iframe-plugin';
import RenderHTML from 'react-native-render-html';
import WebView from 'react-native-webview';

const renderers = {
  iframe: IframeRenderer,
};

const customHTMLElementModels = {
  iframe: iframeModel,
};

const TestIframe = () => {
  const contentWidth = Dimensions.get('screen').width * 0.9;
  const content = `<p>Test:<iframe width="560" height="315" src="https://www.youtube.com/embed/sX1Y2JMK6g8" allowfullscreen></iframe></p>`;

  return (
    <View>
      <RenderHTML
        renderers={renderers}
        WebView={WebView}
        source={{
          html: content,
        }}
        contentWidth={contentWidth}
        customHTMLElementModels={customHTMLElementModels}
        defaultWebViewProps={{ allowsFullscreenVideo: true }}
        renderersProps={{
          iframe: {
            scalesPageToFit: false,
            webViewProps: {
              allowsFullscreenVideo: true,
              javaScriptEnabled: true,
              domStorageEnabled: true,
            },
          },
        }}
        tagsStyles={{
          iframe: {
            width: '100%',
            height: 200, // Ensure to set a height here
          },
        }}
      />
    </View>
  );
};

export default TestIframe;

```
