### ISSUE TITLE
Images failing to render if the URL must be resolved to the image

### ISSUE THREAD

**Issue by dajaffe** [archriss/react-native-render-html#139]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Unknown - only able to test on Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example]

I have not tried the demo, but I have it reproduced in a Snack.

### Environment

  Environment:
    React: 16.3.2
    React native: 0.55.2
    react-native-render-html: 3.9.3

  Target Platform:
    Android (7.0)

### Steps to Reproduce

1. Create a string containing HTML Markup, with an image tag whose src points to a url which is resolved into the image.

### Expected Behavior

Image should render.

### Actual Behavior

An empty area with a border where the image should render is present.

### Reproducible Demo

https://snack.expo.io/HyRLyKGpz

**Comment by Exilz** [comment]
It looks like this URL : http://www.ravelry.com/forum-images/RoadTripKnits/32dmo-dx5lho redirects you to a login page if you're not already logged into your account in your browser.

If you're redirected to the image directly, I guess you're just authenticated on your side. The behavior of this module looks fine to me.

**Comment by dajaffe** [comment]
Ah yeah, you're right. Having to be authenticated completely slipped my mind. I'll have to handle this a different way. Thanks.
