### ISSUE TITLE
Force image width

### ISSUE THREAD

**Issue by enguerranws** [archriss/react-native-render-html#14]
Hi again,

I'm trying to use style to set a width to the img element, but it does nothing. As far as I understand, right now, the module is getting the image URI to set its original width / height.

Any way to force image width? Should I use a renderer for this?

**Comment by Exilz** [comment]
Hi,
I didn't know this wasn't supported.

I fixed this in my development branch, you'll be able to test it when the first release candidate of the next major release is out.

In the meantime, you should be able to work something out with your own renderer, but this should indeed be handled by the default one.

Thanks for reporting it !

**Comment by Exilz** [comment]
You can now force dimensions in `3.0.0`, an exemple is available in the demo :)
