### ISSUE TITLE
Support self closing tags

### ISSUE THREAD

**Issue by assurancetourix** [archriss/react-native-render-html#142]
Hello,
it is a feature request.

Is it possible to support auto closing tags, especially for custom tags ?

Ie we could have `<mytag />`
instead of `<mytag></mytag>`

Many thanks

**Comment by Exilz** [comment]
Hi, the first step while rendering HTML is to parse the string with [htmlparser2](https://github.com/fb55/htmlparser2).

I haven't taken a look at this feature yet, but this is more related to the HTML parser than this module in particular. If anyone is manages to support self closing tags in htmlparser2, there shouldn't be anything to change on this plugin's end.

**Comment by Exilz** [comment]
Looks like this will never be supported by htmlparser2. I'll close this issue since I'm not planning on adding a feature on this plugin's end to support this.
