### ISSUE TITLE
remove underline from 'a' tag

### ISSUE THREAD

**Issue by jahnavi310** [archriss/react-native-render-html#149]
Hi there,

I am trying to remove the underline from the anchor tag.

I have the following in tagStyles:

```
a : {
    color:'#0098D9',
    fontSize: 15,
    textDecoration: 'none'
  },
```

but for some reason that style is not being applied. Any ideas on how to achieve this?
Thanks in advance for the help!

**Comment by ZakZubair** [comment]
It should be `textDecorationLine`

```
a : {
    color:'#0098D9',
    fontSize: 15,
    textDecorationLine: 'none'
  }
```

**Comment by vinpez** [comment]
Why?

**Comment by tanoto-the-explorer** [comment]
Does anyone figure out this?

**Comment by dog5tar** [comment]
`text-decoration` is a shorthand CSS property for `text-decoration-line`, `text-decoration-color`, `text-decoration-style`. The longhand properties will work in V5. Generic shorthands properties support has landed on V6. So the easiest workaround is to use those longhands. [Source](https://github.com/meliorence/react-native-render-html/issues/495#issuecomment-864874385)
