### ISSUE TITLE
Allow Font Scaling props

### ISSUE THREAD

**Issue by simonemarinelli** [archriss/react-native-render-html#158]
Like in the React Native Text component it would be nice to have the allowFontScaling props.

Docs:
[React Native Text (allowFontScaling)](https://facebook.github.io/react-native/docs/text.html#allowfontscaling)

**Comment by simonemarinelli** [comment]
Please merge PR #157

**Comment by jaychenjun** [comment]
Please merge this one

**Comment by kennym** [comment]
This would be very useful.

**Comment by Exilz** [comment]
Available in `4.1.0`

**Comment by liquidvisual** [comment]
Sorry to bother, but how does this feature work? I can't seem to find it in the docs. 
Going off that PR, does it only apply for custom renderers? Eg, adding `allowFontScaling={false}` to custom components or can I apply it to all?

**Comment by nathalia-rus** [comment]
> 

Hey not sure if this helps, but I'm adding `allowFontScaling: false` to `defaultTextProps` in `<RenderHtml />` like so: `<RenderHtml defaultTextProps={{ allowFontScaling: false }}  ... />` and it works as expected :)

**Comment by annguyen-iosdev** [comment]
Thanks muc @nathalia-rus , works perfect for me also.

**Comment by codestar9** [comment]
it works for me as well
