### ISSUE TITLE
[#82 closed issue reference] How to render local image?

### ISSUE THREAD

**Issue by themakerman** [archriss/react-native-render-html#159]
<img src='./images/sopFlowChart1.jpg /> is not working for me. Can anyone plz help? #82

**Comment by themakerman** [comment]
?

**Comment by themakerman** [comment]
its been so long. Can anyone please help me on this?

**Comment by themakerman** [comment]
okay. This can be solved using custom renderers. Closing the issue.

**Comment by liamjones** [comment]
Where's your image? Inside your RN bundle or elsewhere (e.g. files (Android) / Documents (iOS))

**Comment by themakerman** [comment]
@liamjones inside RN bundle. But the thing is i cannot require them dynamically right in custom renderer by passing image path in html
