### ISSUE TITLE
a链接只是转成了普通的文本显示，并没有赋予外链功能

### ISSUE THREAD

**Issue by xiao0502** [archriss/react-native-render-html#163]
// Here's the code that I changed a little bit

   export function a (htmlAttribs, children, convertedCSSStyles, passProps) {
       const style = _constructStyles({
           tagName: 'a',
          htmlAttribs,
           passProps,
           styleSet: passProps.parentWrapper === 'Text' ? 'TEXT' : 'VIEW'
    });
    // !! This deconstruction needs to happen after the styles construction since
    // the passed props might be altered by it !!
    const { parentWrapper, onLinkPress, key, data } = passProps;
    const onPress = (evt) => onLinkPress && htmlAttribs && htmlAttribs.href ?
        onLinkPress(evt, htmlAttribs.href, htmlAttribs) :
        undefined;

    if (parentWrapper === 'Text') {
        let url = htmlAttribs.href;
        return (
            <Text {...passProps} style={style} onPress={url? () => {
                Linking.openURL(url)
            }:onPress} key={key}>
                { children || data }
            </Text>
        );
    } else {
        return (
            <TouchableOpacity onPress={onPress} key={key}>
                { children || data }
            </TouchableOpacity>
        );
    }
}

**Comment by Exilz** [comment]
Please fill the issue template, use an english title and state your problem explicitly.
