### ISSUE TITLE
ImageMaxWidth does not work...

### ISSUE THREAD

**Issue by nalorim** [archriss/react-native-render-html#166]
RN 0.55 Lastest

I have tried to hard input the number in the imagemaxwidth or using Dimensions but, the image is still showing full size and overflow out of frame.

FYI, I fetch content from wordpress api. The images does not show correctly.

Any idea, what i did wrong?

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
