### ISSUE TITLE
Yellow warning

### ISSUE THREAD

**Issue by simonewd** [archriss/react-native-render-html#167]
I'm getting this yellow warning but the library is rendering html properly.
16:30:25
▼react-native-render-html
- node_modules/expo/src/Expo.js:21:41 in warn
- node_modules/react-native-render-html/src/HTML.js:129:25 in registerDOM$
- node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:296:30 in invoke
- node_modules/regenerator-runtime/runtime.js:62:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:152:28 in invoke
- node_modules/regenerator-runtime/runtime.js:195:17 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:194:27 in callInvokeWithMethodAndArg
- node_modules/regenerator-runtime/runtime.js:217:12 in enqueue
- node_modules/regenerator-runtime/runtime.js:241:8 in async
* :null:null in registerDOM
- node_modules/react-native-render-html/src/HTML.js:82:8 in componentDidMount
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:10627:12 in commitLifeCycles
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:12512:10 in commitAllLifeCycles
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:39:15 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:221:34 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:12677:10 in commitRoot
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13685:46 in completeRoot
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13635:23 in performWorkOnRoot
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13545:26 in performWork
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13506:16 in performSyncWork
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13728:8 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:2565:27 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:2701:17 in _receiveRootNodeIDEvent
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:2721:26 in receiveEvent
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:351:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:116:26 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:314:6 in __guardSafe
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:115:17 in callFunctionReturnFlushedQueue

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
