### ISSUE TITLE
img's tag resizeMode property not modifiable through html tagStyles

### ISSUE THREAD

**Issue by adderly** [archriss/react-native-render-html#172]
### Is this a bug report or a feature request?
feature/bug

### Details

There seems no way to set the resizeMode property to an image tag **<img>** through the tagStyles.

```javascript
const myTagStyles = {
    img: {
        resizeMode: 'contain',
    },
};
<HTML  tagsStyles={myTagStyles} />
```

As i searched in the source code it defaults to "cover".

**Comment by adderly** [comment]
I made a little PR addressing the issue.
I added some thing that might not be needed, you guys check it out.

**Comment by Exilz** [comment]
If someone needs this feature and is reading this issue, this still needs to be addressed.

This should be a fairly easy change. So, if you're wiling to contribute to this project, this is a good starting point.

**Comment by adderly** [comment]
Well, i made some changes to a branch but it is nothing pull request worthy...

**Comment by wxcvbn612** [comment]
why you put cover as default, make stretch or contain?

**Comment by aashish-pixere** [comment]
Is there any solution for this ?

**Comment by LorrisSaintGenez** [comment]
@Exilz Any blocking to this PR https://github.com/archriss/react-native-render-html/pull/315 ? That would hopefully solve this issue

**Comment by jsamr** [comment]
@LorrisSaintGenez We're working on it!
