### ISSUE TITLE
Cannot display GIF images?

### ISSUE THREAD

**Issue by orzhtml** [archriss/react-native-render-html#175]
"react-native-render-html": "^3.10.0"

Cannot display GIF images?

![57c76deb-d8fb-454a-b878-27625d2d1ddd](https://user-images.githubusercontent.com/5866002/44129049-e7bd855e-a078-11e8-86dc-fe79c662bfab.png)

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
