### ISSUE TITLE
Image with 'Bearer' authentication token

### ISSUE THREAD

**Issue by sorakrisc** [archriss/react-native-render-html#179]
I kindda want to add 'Bearer' authentication token to the img tag

Normally react native image component could add headers like this.
```
<Image
    source={
    { uri: 'https://yourdomain.com/get-image',
      headers: {
                Authorization: 'Bearer xyz'
               }
            }
}/>
```
alteringImgNode would not work adding header to src since src requires a string.. adding header props to node.attribute would not work either because HTMLImage.js is not accecpting headers as a props 

Thanks in advance anyway

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
