### ISSUE TITLE
Is it possible to load local images inside HTML?

### ISSUE THREAD

**Issue by juniorklawa** [archriss/react-native-render-html#180]
### Is this a bug report or a feature request?

Feature request

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yep.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

(Write your answer here.)

Yep.

(Write your answer here.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

**Comment by Exilz** [comment]
Duplicate #82. I'll re-open it if you can't find a way to make it work.
