### ISSUE TITLE
Local images (base64) custom renderer: "Each child in array..." warning

### ISSUE THREAD

**Issue by greenais** [archriss/react-native-render-html#184]
### Is this a bug report or a feature request?
Bug, probably

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?
Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?
Yes

### Have you made sure that your issue hasn't already been reported/solved?
Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
Latest Adndroid 8.1 emulator (AndroidStudio)

### Is the bug reproductible in a production environment (not a debug one)?
Not tested yet

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?
Yes

### Environment
    React: 16.4.1
    React native: 0.55.4
    react-native-render-html: 3.10.0

  Target Platform:
    Android (8.1)

### Expected Behavior
No warnings

### Actual Behavior
Warning "Each child in an array or iterator should have a unique "key" prop"

### Reproducible Demo
My project uses base64 encoded images coming from server using JSON. So locally in RN I have encoded string for every image. I'm trying to make custom renderer which can consume this string via global variable - in this way:

```
const wWidth = Dimensions.get('window').width;

const image1renderer = ()=> {
  const size = wWidth*0.25;
  return (
    <Image
      style={{flex: 1, width: size, height: size}}
      source={{uri: `data:image/png;base64, ${global.image1}`}}
    />
  )
};
```

Data oblect:
```
const data = {};
data.html = `
    <h1>This HTML snippet is now rendered with native components !</h1>
    <h2>Enjoy a webview-free and blazing fast application</h2>
    <image1 />
`;
data.image1 = 'loooooong_base64_string....';
```

And then: 
```

render()
global.image1 = data.image1;

<ScrollView style={{flex: 1}}>
      <HTML
            html={data.html}
            imagesMaxWidth={wWidth}
            renderers={{image1: image1renderer}}
          />
...
```
It works, but gives the warning above

**Comment by Exilz** [comment]
This warning has been reported by numerous users who made their own custom renderers.
In order to fix it, you need the fourth parameter of your `image1renderer` which is `passProps`.

In this object, you can find `key`. Just add `key={passProps.key}` to the uppermost node of your renderer (`<Image>`).

This should fix your warning.
