### ISSUE TITLE
helpwanted: style.myStyle not working ?

### ISSUE THREAD

**Issue by magicmiles** [archriss/react-native-render-html#185]
below: 'item' is a json object.

`<HTML html={item.title.render} style={style.myStyle} />`

The title shows up but I can't style the text....how can I set a style sheet on the text that's coming off the object with your package ? 

And so that we're clear, yes I read > https://github.com/archriss/react-native-render-html/issues/145

If I understand your package properly, this package only understands embedded css within the HTML and then allows me style it from there. That's great! However, what happens if i have an object like what I'm showing above where it's the title of a post (wordpress) and there is no embedded css that it's pulling ? So should I be able to style the text from the object and not the direct html ?  

Thanks.

**Comment by tclarke-scottlogic** [comment]
What does the text of `item.title.render` look like? If it's just text with no HTML, you'd just want to use a basic React Native \<Text\> tag

**Comment by magicmiles** [comment]
@tclarke-scottlogic Sometimes the text in the field referenced has a "-" in it or other special characters. So it has to be rendered. 
Here's what the title looks like:

![img_1588](https://user-images.githubusercontent.com/4790208/46359717-d42cb200-c637-11e8-9427-d925ef896e7d.jpg)

**Comment by tclarke-scottlogic** [comment]
A Text block should be able to handle the special characters fine, unless they're html encoded?

`<Text>This is text - this is also text, texty text & text</Text>` works fine for me in raw React Native.

**Comment by magicmiles** [comment]
They're encoded. :-)

**Comment by tclarke-scottlogic** [comment]
Best to just [decode them then](https://github.com/mathiasbynens/he), rather than using a full html parser to do text decoding.

Alternatively (bit of a hack, this), prefix and suffix your header with <h1>&</h1>, and thus reduce the problem to one that has already been solved?

**Comment by magicmiles** [comment]
@tclarke-scottlogic Thomas, I like your last suggestion. Ummmm How would I do that ?

**Comment by tclarke-scottlogic** [comment]
e.g. `"<h1>"+item.title.rendered+"</h1>"` instead of `item.title.rendered` works fine, and then you just use tagStyles as mentioned in #145 to set your desired styling.

But honestly, it's ugly and means you're sending a simple string to something that's intended to parse a full HTML DOM. Just use https://github.com/mathiasbynens/he to do string decoding instead, that's what it's for.

**Comment by magicmiles** [comment]
Gotcha. Noted. Ok, I'll try it your way. One more noob question then: <Text>{he.decode(item.title.rendered, options)}</Text> ?

**Comment by magicmiles** [comment]
So If employ he.decode. the line to decode it should look like:

<Text>{he.decode(item.title.rendered, options)}</Text> 

Which the simulator thinks HE is a variable and throws an error.

**Comment by tclarke-scottlogic** [comment]
You need to import he. See my snack, but if you add `import he from 'he';`, snack will auto-add it to the package.json.

**Comment by magicmiles** [comment]
Well I know I have to import it, already done. My question was how to implement it from the line I showed you above.  And how did you show the log from the snack ? Didn't see that one as an option shown anywhere....that would help things along sometimes if I could work like that.

**Comment by tclarke-scottlogic** [comment]
Huh, if you've imported, it should treat `he` as an object with a function `decode`. Got an example of the error?

Oh, and you show the log by clicking on the "No Errors" portion of the bar at the bottom, and then a box pops up that has an "ERRORS" tab and a "LOGS" tab. The logs tab is the one you want.

**Comment by magicmiles** [comment]
Jesus. I'm an idiot some days ....

My import statement was `import HE from 'he';`
and it should have been `import he from 'he';`

Good lord! 

Problem solved. Issue closed. And now my app works. 

Now I just gotta clean up the visuals a little and we're good to go and I can actually publish this thing as a working demo but that's a whole different thread. 

Yeah, you're right the "NO ERRORS" thing is way to inconspicuous. That needs to be a radio button like everything else on that bottom row. Never would have seen that or clicked on it. Not exactly the easiest thing to find.

**Comment by tclarke-scottlogic** [comment]
Ah, typos. In other industries, a minor issue for pendants. In ours, failures that bring entire systems to their knees.

Have a good evening!
