### ISSUE TITLE
onLinkPress needs to be clearly documented.

### ISSUE THREAD

**Issue by magicmiles** [archriss/react-native-render-html#188]
Can I make a suggestion:

On your docs Page there should be a section about onLinkPress that reads something like |

To enable the user to press a link, the LINKING library must be IMPORTED at the top of your code, as well as this line must appear in the HTML call statement like so:

            <HTML
              html={this.content}
              onLinkPress={(event, href)=>{
                Linking.openURL(href)
              }}
            />

**Comment by erhanbicer** [comment]
@magicmiles thank you.

**Comment by davidcort** [comment]
I have troubles with this ...
Seems not works with the app is make with Expo  :(

**Comment by abzeede** [comment]
@davidcort It's doing fine with expo but you must import Linking from expo not react-native
Example: import { Linking } from 'expo'

**Comment by intransitorio** [comment]
this post saved my morning. Thanks @magicmiles

**Comment by cmejet** [comment]
Saved my bacon by providing this, THANK YOU!!! Worked awesome for phone linking too by providing the `tel:` in the href before the number.

**Comment by Synaric** [comment]
Thanks for your example! Really help me.

**Comment by guille-alibrate** [comment]
Excelent.
On question: how could you get the link text, besides the href attribute? The text is valuable info too.

**Comment by Yab-kami** [comment]
> Excelent.
> One question: how could you get the link text, besides the href attribute? The text is valuable info too.
> 
> `<a href="...">This here</a>`

Any Update on this?

**Comment by Akira-25** [comment]
You're a legend @davidcort

**Comment by Fred-Reis** [comment]
If you import  Linking from react-native, it's work like a charm.

**Comment by jsamr** [comment]
In react-native-render-html v5.0.0, `onLinkPress` defaults to a function invoking `Linking.openURL`, so there won't be a need for documenting this! See #442

**Comment by Koushik26011997** [comment]
tu log pagla hai
