### ISSUE TITLE
v3 incorrect render of special character 

### ISSUE THREAD

**Issue by AzSiAz** [archriss/react-native-render-html#19]
This page doesn't render correctly with special character : 
[this link](https://api.azsiaz.tech/chapter/query/?chapter=Absolute_Duo:Volume_1_Prologue)

![simulator screen shot - iphone 6 - 2017-10-02 at 13 52 39](https://user-images.githubusercontent.com/7109680/31076092-fd69922a-a778-11e7-8327-8a646dded782.png)

Render fine with v2.1.0
![simulator screen shot - iphone 6 - 2017-10-02 at 13 54 34](https://user-images.githubusercontent.com/7109680/31076174-49964404-a779-11e7-914f-c2012dc8eb2a.png)

**Comment by Exilz** [comment]
Hi,
HTML entities were not decoded by default.

I fixed it in `3.1.0`, thanks for reporting this.

**Comment by AzSiAz** [comment]
No problem, thanks for the fix 👍
