### ISSUE TITLE
textSelectable does not work when texts are not in a tag and there are other tags

### ISSUE THREAD

**Issue by zhangzhhz** [archriss/react-native-render-html#193]
### Is this a bug report or a feature request?

This is a bug report.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android (dont have an iPhone to test)

### Is the bug reproductible in a production environment (not a debug one)?

yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

yes

### Environment

    React: 16.5.0
    React native: 0.57.1
    react-native-render-html: 3.10.0

    React: 16.3.1
    React native: 0.56
    react-native-render-html: 3.10.0

### Steps to Reproduce

Please refer to this snack.
https://snack.expo.io/H16whhV6Q

### Expected Behavior

If textSelectable is provided, all texts should be selectable.

### Reproducible Demo

https://snack.expo.io/H16whhV6Q

**Comment by zhangzhhz** [comment]
Tried to follow the code and updated the following in HTMLRenderers.js, and it works for me now. 

```
export function textwrapper (htmlAttribs, children, convertedCSSStyles, { key }) {
    return (
        <Text key={key} style={convertedCSSStyles}>{ children }</Text>
    );
}
```

to

```
export function textwrapper (htmlAttribs, children, convertedCSSStyles, { key, textSelectable }) {
    return (
        <Text key={key} selectable={textSelectable} style={convertedCSSStyles}>{ children }</Text>
    );
}

```

**Comment by roblangridge** [comment]
Would be great to see this merged into the next version

**Comment by brsaylor2** [comment]
+1

**Comment by jsamr** [comment]
This issue will be fixed soon. I'm implementing tests and reviewing the PR. So far, I understand that Android only considers the first Text element in the tree to apply the selectable attribute. But this library, in some occasions, applies the `selectable` prop deeper. I could confirm this behaviors with snapshots, and this observation matches every example provided in the snack.

**Comment by Saren-Arterius** [comment]
Had the same issue as this and #362, which is <HTML> inside <FlatList>. https://github.com/facebook/react-native/issues/26264 solved it for me.
