### ISSUE TITLE
Suggestion: make webview use WkWebkit over uiWebkit

### ISSUE THREAD

**Issue by Djinne** [archriss/react-native-render-html#198]
If your iframes are causing crashes from embedded videos on iOS, add the following somewhere:

```
if (WebView.defaultProps == null) WebView.defaultProps = {};
    WebView.defaultProps.useWebKit=true;
```

All this does is makes sure the WebView component uses webkit by default.

**Comment by prashen** [comment]
@Djinne Can you tell me where to put it. I am facing issue in ios Bad excess crashing in xcode.
I have an embed youtube URL in the HTML rendering.

**Comment by maximus123123** [comment]
I put it at the end of constructor of app.js

**Comment by prashen** [comment]
But I have a details.js component where I am facing the issue I put it on that file before render and it's working.

So will this a global setting if I put it on constructor or I have to put it everywhere where HTMLrender used?

**Comment by maximus123123** [comment]
It's global, it may work

**Comment by prashen** [comment]
Thanks @Djinne I have created a article on it that other developer get it from medium channel.
https://medium.com/tutorials4beginners/solution-of-youtube-embed-inside-react-native-render-html-component-which-crashed-on-play-and-e4e2d1518e8f?source=friends_link&sk=7720c52ccaa1011f832d8bd11145fc1b

**Comment by maximus123123** [comment]
Haha thanks man,
I completely forgot what the error was, I kind of wrote that fix out of frustration/tiredness after fixing it.
For me it was Vimeo that was causing the problem
