### ISSUE TITLE
Missing props in children

### ISSUE THREAD

**Issue by pieter888** [archriss/react-native-render-html#200]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

No, the issue seems straightforward enough (hopefully) to skip this step

### Environment

react-native: 0.57.5
react-native-render-html: 3.10.0

Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

I will use this example html to be rendered to demonstrate the issue
```
<mycustomelement>
  <a href="https://github.com">
    <img src="example.jpg" />
  </a>
</mycustomelement>
```
What I want to do is pick up the `mycustomelement` tag and render my own version of the inside code using the `children` parameter.
Here is the content in ` children`  if I output it:
![image](https://user-images.githubusercontent.com/6928659/49012634-42927a00-f17a-11e8-8427-5aa0786515ef.png)
...
![image](https://user-images.githubusercontent.com/6928659/49012661-5e961b80-f17a-11e8-8537-6c95124542f6.png)

As you can see in the output, the contents of the `<a>` tag does NOT contain any information on it's properties, like the href tag.

### Expected Behavior

I expect all the child's parameters (and recursively all *their* child's parameters) to show up in their respective `props`  arrays, so I can modify my components looks/functionality according to their props.

### Actual Behavior

As shown in above screenshot, certain information is missing.
There is no reference to the value of  `href` on the `<a>` tag.
On the other hand, I can find the Image source just fine.

I also planned on using some custom properties on tags to give further info to my renderer, but custom tags are ignored. For example, if I wanted to parse `<a href='google.com' subtitle='example'>` I cannot read the value of the `subtitle` because it's ignored.

### Reproducible Demo

https://snack.expo.io/Bk-ypwtAX

**Comment by jsamr** [comment]
I am closing this issue because it concerns an old version of this library (3.x). If the issue persists on the latest version, feel free to reopen.
