### ISSUE TITLE
How to style text that are not wrapped in HTML?

### ISSUE THREAD

**Issue by reddeguzman** [archriss/react-native-render-html#204]
It's impossible to style text that are not wrapped with HTML tags. For example a string that comes from somewhere else and it contains combination of text that are bare and are wrapped with HTML tags

**Comment by mrquanghuy** [comment]
You cant try this
`customWrapper={(node) => <Text style={{...common.textPrimary}}>{node}</Text>}`

**Comment by AishwaryaSurana** [comment]
I am unable to use font color within HTML
My HTML is:
`var html="Text 1<font color = '#dd3936'><b>bold text with color</b></font>,hi<br><br>Also, this text<font color = '#dd3936'><b>feedback</b></font>, hello <font color = '#dd3936'><b>development.</b></font>"`

```
 <HTML 
              html={html
              baseFontStyle={{fontFamily: this.props.getFontFamily(template.font_family),fontSize:18}}
              />
```

**Comment by Exilz** [comment]
@AishwaryaSurana please open another issue. There's indeed a problem with your HTML string that isn't related to this question.

**Comment by Exilz** [comment]
@reddeguzman you can style unwrapped texts by using the `tagsStyle` prop. Just add the following : `rawtext: { color: 'red' }`. 
This might have unintended modifications on your styling, though.
