### ISSUE TITLE
is there any way to cache image like react-native-fast-image?

### ISSUE THREAD

**Issue by flyinghawker** [archriss/react-native-render-html#206]
### Is this a bug report or a feature request?

(Write your answer here.)

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

(Write your answer here.)

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

(Write your answer here.)

### Have you made sure that your issue hasn't already been reported/solved?

(Write your answer here.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by Exilz** [comment]
Write a custom renderer with `react-native-fast-image` or any component you like.

**Comment by Shummy1991** [comment]
For those who are still trying to solve this:
You can create a component for the img tags and use the contentWidth as width.
After that get the aspect ratio of the image with Image.getSize (when online).
After that store the ratio in a redux store.
Next time (actually first time also) check if the url is in the store or not, and if it is in the store, then you can use the ratio from there.
This way you can cache the images with react-native-fast-image.
@flyinghawker
