### ISSUE TITLE
Center tag on android not working as expected

### ISSUE THREAD

**Issue by ue** [archriss/react-native-render-html#212]
`<center> example </center>`

This tag not working as expected on android it should be center which is between tags but its doing nothing.

Devices: all mobile android devices.
btw version v1.0.0 yarn or npm doesn't upgrade to 3.10.0

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
