### ISSUE TITLE
em and strong doesnt render correctly in ios

### ISSUE THREAD

**Issue by lanzosuarez** [archriss/react-native-render-html#218]
Is there an additional configuration that will needs to be done for em and strong tags to render correctly on ios?

It's properly working on android.
Used tagsStyles but i got no luck

```
tagsStyles={{
     em: { fontStyle: "italic", color: blue },
      strong: { fontWeight: "900", color: blue }
}}
```

thanks for the help

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.

**Comment by guschilds** [comment]
As a heads up for others: I realized that the text that was properly bold and/or italic on Android was being rendered through the System font instead of the custom font we were using for all text. I achieved the same behavior on iOS by adding this to my `tagsStyles`:

```
    strong: {
      fontFamily: 'System',
    },
    em: {
      fontFamily: 'System',
    },
```

It's not ideal, but in our case, it's better than not being bold or italic at all.

**Comment by liquidvisual** [comment]
I just ran into this, but on Android. I stumbled across a fix by supplying the font weight as a string, which then allowed the specified font to display. This was my setup:

```js
import RenderHTML, { defaultSystemFonts } from "react-native-render-html";

<RenderHtml
    source={{ html: htmlSourceHere }}
    tagsStyles={TAGS_STYLES}
    systemFonts={[
      ...defaultSystemFonts,
      "Montserrat-Medium",
      "Montserrat-SemiBold",
      "Montserrat-Bold",
    ]}
/>
```
```js
const TAGS_STYLES = {
  body: {
    fontFamily: "Montserrat-Medium",
    fontSize: 14,
    lineHeight: 20,
    color: "white",
    whiteSpace: "normal",
  },
  strong: {
    fontFamily: "Montserrat-Bold",
    fontWeight: "600", // Huzzah! Montserrat now shows as bold on Android
    color: "lime",
  },
}
```

**Comment by jsamr** [comment]
@liquidvisual This is not a bug, you're just not registering fonts in Android in a way React can handle modifiers (boldness, italic) properly. [The real 'fix' is covered in the FAQ](https://meliorence.github.io/react-native-render-html/docs/faq#custom-font-families-dont-work-whats-happening).

**Comment by liquidvisual** [comment]
I didn't say it was a bug, this is what worked in my particular case.

**Comment by jsamr** [comment]
Well, you edited your post to remove the "bug" wording 🤷🏻 in the code comment.
