### ISSUE TITLE
Custom p tag. But fontSize not working.

### ISSUE THREAD

**Issue by NrqhEIcsRi004** [archriss/react-native-render-html#224]
Custom p tag. But fontSize not working.

```javascript
p = (htmlAttribs, children, convertedCSSStyles, passProps) => {
    return <Text key={passProps.key} style={{
        fontSize: 28,
        lineHeight: 28
    }}>{children}</Text>
}
```

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
