### ISSUE TITLE
App crashes when there are inline CSS functions

### ISSUE THREAD

**Issue by nekdev** [archriss/react-native-render-html#225]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

```
react-native-render-html: 4.1.0

React Native Environment Info:
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
    Memory: 76.87 MB / 12.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 27.0.3, 28.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: /undefined - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.6.3 => 16.8.1 
    react-native: ^0.58.3 => 0.58.4 
```

### Steps to Reproduce

1. Try to render an element with a CSS function inside the styles prop
2. Ex.: `<div style="width: calc(100% - 80px);">`
3. Load the app

### Expected Behavior

App continue working and fix the width style prop to something default or maybe try to parse the CSS function

### Actual Behavior

The app crashes entirely

### Reproducible Demo

Open the demo included and add a style with a CSS function `style="width: calc(100% - 20px)"`.

![react-native-render-html_css-func-bug](https://user-images.githubusercontent.com/41330892/52552543-5d73a280-2de9-11e9-99d4-b84b8a1c0ae5.png)

This will cause the app to creash entirely and it's very serius if the app tries to fetch and display live articles from pages.

**Comment by Exilz** [comment]
Hi,
thanks for the detailed report.

I made sure to ignore the `calc` style completely. We might be able to parse some of them in the future, but for now, let's just make sure it doesn't break apps.

This will be part of the next release that should be out shortly.

**Comment by Exilz** [comment]
Fixed in `v4.1.1`

**Comment by clytras** [comment]
There are more cases with inline CSS that result the app to crash due to invalid props value set. I also faced a case when there is an inline `display: block` styling and the result was the app to crash at that point. I think the best thing to do here is to compare the actual style props with some predefined lists of RN valid props/values and exlude/remove/(replace maybe) everything that does not match with RN supported style props/values.

**Comment by kristoff2016** [comment]
@clytras I faced this issue to use 

> display: block

any solution to fix this ?

thank you

**Comment by clytras** [comment]
@Exilz will you reopen this or I have to create a new bug report?

**Comment by kristoff2016** [comment]
I hope this issue in handle well in error
