### ISSUE TITLE
Error when inspecting: "Expected to find at least one React Renderer"

### ISSUE THREAD

**Issue by Slapbox** [archriss/react-native-render-html#230]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Searched for a while and didn't find anything similar.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android 9.0. Unsure about iOS or earlier versions of Android. This issue is affecting at least physical devices. Have not tested emulator.

### Is the bug reproductible in a production environment (not a debug one)?

No. It's only relevant in development.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes, but by copying the Demo src files into my Expo 31 project. I did not test the Demo exactly as provided (Independent of Expo)

### Environment

  **Environment:**
    - React: 16.0.0
    - React native: 0.57.1 (Expo 31.0.1)
    - React-native-render-html: 4.1.1

  **Target Platform:**
    - Android (9.0)

### Steps to Reproduce

(Write your steps here:)

1. Use `Toggle Inspector`
2. Click an item that has been rendered by React-native-render-html
3. Receive error message: `Expected to find at least one React Renderer`

### Expected Behavior

Allow inspection of rendered elements rather than throwing the error.

### Actual Behavior

`Expected to find at least one React Renderer`
![image](https://user-images.githubusercontent.com/6835891/52970106-ab0b8480-3380-11e9-97fb-a3cce856726f.png)

### Reproducible Demo

TBD

**Comment by Slapbox** [comment]
Quick update, the bug doesn't affect iOS.

**Comment by jsamr** [comment]
This is an upstream bug from react-native, see https://github.com/facebook/react-native/issues?q=Expected+to+find+at+least+one+React+renderer+in%3Atitle
