### ISSUE TITLE
Bug: Does not support conflict css with react native style app crashed 

### ISSUE THREAD

**Issue by kristoff2016** [archriss/react-native-render-html#237]
Hello thank you for nice plugin. 

There are some issue in render html that has some css inside div elements  when I copied any content blog on website and 

there is css inside example `display: block`  react native think it was itself css so the app is crashed

the point error is `display: block` (the library should not render css from web) react native think to render `display: flex` instead of.

thank you so much.

**Comment by Exilz** [comment]
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md)!**

As stated in these:
> You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.
> Although we might still help you without all these informations, it would be unfair to let some people post issues without filling everything.
