### ISSUE TITLE
Fail on import HTMLStyles in project Demo

### ISSUE THREAD

**Issue by fcostaprojects** [archriss/react-native-render-html#24]
Hi @archriss

On Demo project this import fail

react-native-render-html/Demo/snippets.js

import { _constructStyles } from 'react-native-render-html/HTMLStyles';
to
import { _constructStyles } from 'react-native-render-html/src/HTMLStyles';  OK

**Comment by Exilz** [comment]
Hi,
I fixed it, thanks !
