### ISSUE TITLE
Add support for maxFontSizeMultiplier

### ISSUE THREAD

**Issue by adam-buckley** [archriss/react-native-render-html#241]
### Is this a bug report or a feature request?

Feature request

It would be great to have support for [maxFontSizeMultiplier](https://facebook.github.io/react-native/docs/text#maxfontsizemultiplier) that was introduced in React 0.58. At the moment there are flags to disable font scaling but just turning it on or off is not the best outcome for people with a visual impairment who use their phones accessibility features to make text more legible. maxFontSizeMulitplier allows devs to introduce _some_ scaling without layouts completely breaking.

**Comment by jsamr** [comment]
This feature has been shipped in react-native-render-html v5.0.0, via the new `defaultTextProps` prop! See #442
