### ISSUE TITLE
Twitter widget not rendering

### ISSUE THREAD

**Issue by salhotra** [archriss/react-native-render-html#245]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

I have reproduced the issue on iOS

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

  Environment:
    React: 16.6.1,
    React native: 0.57.7,
    react-native-render-html: ^4.1.2

  Target Platform:
    iOS (12.0)

### Steps to Reproduce

(Write your steps here:)

In html prop, pass the following html string:
```
  <blockquote class="twitter-tweet" data-lang="en">
                <p dir="ltr" lang="en">"We can improve on that one."
                    <br />
                    <br /> Ole joined us on <a href="https://twitter.com/hashtag/MUTV?src=hash&ref_src=twsrc%5Etfw">#MUTV</a> after yesterday's game... <a href="https://t.co/F0oOm25bNx">pic.twitter.com/F0oOm25bNx</a></p> — Manchester United (@ManUtd) <a href="https://twitter.com/ManUtd/status/1112264634264768512?ref_src=twsrc%5Etfw">March 31, 2019</a></ blockquote>
<script async="async" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
as `html={`html string here`}`

### Expected Behavior

The script tag should have caused a webview to render with the tweet embedded via the te

![Screenshot 2019-04-01 19 43 41](https://user-images.githubusercontent.com/20168166/55334249-7d087c80-54b6-11e9-9af8-2a2ec9dbb486.png)

### Actual Behavior

The text got rendered but the script tag for twitter widget did not work.

![Screenshot 2019-04-01 19 35 37](https://user-images.githubusercontent.com/20168166/55334093-3f0b5880-54b6-11e9-8fff-06bc26f38b5b.png)

**Comment by gunduzcihat** [comment]
why doesn't anyone answer?

**Comment by jariwalabhavesh** [comment]
@salhotra :
Have you find any solution? I am facing same issue.

**Comment by salhotra** [comment]
@jariwalabhavesh I ended up spliting my html into multiple chunks. Each chunk will either be static HTML or an Embed. I am using this library for the static html chunks and using webview for the embeds.

**Comment by jariwalabhavesh** [comment]
@salhotra : How you are identifying height of embded?

**Comment by salhotra** [comment]
@jariwalabhavesh I am using react-native-autoheight-webview

**Comment by jariwalabhavesh** [comment]
@salhotra : Thank you, I will try

**Comment by Exilz** [comment]
There is no way a webview is rendered with this snippet. It depends on a JS script to display it inside browsers and falls back to a `blockquote` if JS is missing.

This is *nearly impossible* to achieve on this plugin. So you can either make a custom renderer for blockquote (that's what we did, it's hard but it renders pretty beautifuly) or you can find a way to render an `iframe` with your embedded tweet.

**Comment by jjg77** [comment]
@Exilz would you be willing to share the custom renderer for blockquote?

**Comment by ssingh1984** [comment]
@salhotra Will you pls share the code if you have to handle twiiter widget rendering.

**Comment by sadiefp** [comment]
Not sure if this will help anyone, but I was able to get the tweet's url from within a custom blockquote renderer:
`tnode?.children[1]?.children[0]?.children[1]?.attributes?.href`
