### ISSUE TITLE
decodeEntities is decoding but do not read tags

### ISSUE THREAD

**Issue by vUdav** [archriss/react-native-render-html#248]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android (don't know about iOS)

### Is the bug reproductible in a production environment (not a debug one)?

Don't know

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Didn't try

### Environment

 Environment:
    React: 16.8.3
    React native: 0.59.1
    react-native-render-html: 4.1.2

  Target Platform:
    Android (9.0)

### Steps to Reproduce

If I have HTML string with special chars, for example `&lt;h1&gt;This HTML snippet is now rendered with native components !&lt;/h1&gt;`, then plugin return string like as `<h1>This HTML snippet is now rendered with native components !</h1>` and do not read HTML tags. See screenshot.

1. Get string with html special chars
2. Set string on html property
3. Watch on render

### Expected Behavior

Render HTML tags

### Actual Behavior

![screenshot](https://user-images.githubusercontent.com/7684712/55418206-d6d27a80-557a-11e9-9318-c7da06ef17c8.jpg)

### Reproducible Demo

```js
render() {
   const htmlContent = `
      &lt;h1&gt;This HTML snippet is now rendered with native components !&lt;/h1&gt;
   `;

   return (
      <View>
         <HTML
            html={htmlContent}
            decodeEntities={true}
            imagesMaxWidth={Dimensions.get("window").width}
         />
      </View>
   )

}
```

**Comment by jsamr** [comment]
@vUdav This is the expected behavior!

**Comment by rezaarifian** [comment]
how to fix it? expected result is `<h1>` is title text
