### ISSUE TITLE
IGNORED_TAGS Typo

### ISSUE THREAD

**Issue by wongal5** [archriss/react-native-render-html#249]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

No

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

All environments

### Steps to Reproduce

1. Check the `IGNORED_TAGS` array in `src/HTMLUtils.js`
2. There is a typo where the HTML tag `dialog` appears instead as `diaglog`. 

### Expected Behavior

Package should not render dialog tags by default.

### Actual Behavior

Package does render dialog tags by default. 

### Reproducible Demo

N/A, typo clearly visible in source code

**Comment by rufusraghunath** [comment]
There is another typo in `IGNORED_TAGS` where it says `scripts` instead of `script`. This means that actual `script` tags are currently allowed by default, which seems like a significant security issue!
