### ISSUE TITLE
iframe design breaking after version upgrade

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [archriss/react-native-render-html#250]
### Is this a bug report or a feature request?

Yes

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes, sure.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

For both platform, not specific.

### Environment
**Environment:**
    React: 16.6.3
    React native: 0.57.8
    react-native-render-html: 4.1.2

  **Target Platform:**
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce

1. We have below html structure:
   ```
    <div class="medium-insert-embeds">
    <figure>
    <div class="insert-embed">
      <div class="metaloading member-embed" data-hrefurl="">
        <div class="metal">
          <div class="mf-wrap">
            <div class="mf-middle clearfix">
              <div class="mf-middle-right ocean-user-profile">
                <div class="post-logo">
                  <a href="" target="_blank" style="cursor: pointer;">
                    <img class="post-logo-img" src="https://facebook.github.io/react-native/" alt="logo">
                  </a>
                </div>
                <div class="post-content">
                  <h2>
                    <a class="post-content" href="" target="_blank">Piyalee Maiti</a>
                  </h2>
                  <p class="m-content-desc">Front End Developer</p>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </figure>
</div>
```

2.  Above html should render like below:
![Group 18 4](https://user-images.githubusercontent.com/20696057/55535339-8c651100-56d4-11e9-9a0b-9b9cf36bc5da.png)

3. But it's breaking like below : 
![IMG_20190404_122059](https://user-images.githubusercontent.com/20696057/55535308-72c3c980-56d4-11e9-8221-9164a4255a88.jpg)

4. It's happen from version 4.0.0.

**Comment by jsamr** [comment]
We are in the process of cleaning the issue tracker to make it manageable. Because your issue did not follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md), it will be closed. We need a full reproducible example to help you out. But you can [ask this question on stackoverflow](https://stackoverflow.com/questions/ask). Don't forget to add the `react-native-render-html` tag. We are notified on this tag, and will be happy to help you here.
