### ISSUE TITLE
Crash: text-align: start error: should be one of auto, center, justify, left, right.

### ISSUE THREAD

**Issue by Donhv** [archriss/react-native-render-html#252]
Is this a bug report or a feature request?
Bug report

Have you read the guidelines regarding bug report?
no

Have you read the documentation in its entirety?
yes

Have you made sure that your issue hasn't already been reported/solved?
yes

Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
I have only checked on Android

Is the bug reproductible in a production environment (not a debug one)?
debug doesn't run

Have you been able to reproduce the bug in the provided example?
no

Environment
Environment:
React: ^16.3.1
React native: ^0.55.4
react-native-render-html: ^3.10.0

Target Platform:
Android (6.0)
iOS (10.3)

Hi all, my app crash because css style: "text-align:start", text-decoration-style:initial", "font-family: "" "
now, i use: ignoredStyles={['text-align', 'text-decoration-style', 'text-decoration-color','font-family']} to prevent it, but i don't know when have more css style make crash. 
How can i always prevent it?

**Comment by nadav2051** [comment]
Same problem, can we just ignore or throw a warning rather than crash when encountering un-renderable CSS property?

**Comment by sumudu-dewasurendra** [comment]
@nadav2051 even for the "display" style same happens. Are there any way to fix this problem? Coz using ignoring is not the way to handle this

**Comment by nadav2051** [comment]
@sumudu-dewasurendra I agree. I'm also waiting for a more robust solution.

**Comment by diamont1001** [comment]
Same problem, any solution?

**Comment by axu6705** [comment]
+1

**Comment by yuezonglun** [comment]
+1

**Comment by matthiaskoenig96** [comment]
+1
Solution would probably be to cast "start" and "end" to "left" or "right" until react style sheet can handle the new values.

**Comment by Lucasark** [comment]
I don't not understand why it work with tag <p> and don't with tag <div>.

Example:
```
const html = `
  <div style="text-align: justify;">jaskjdhkas jdhkasjhdka sjhdkajs  hdkash kd jashk djah skd jahskdjhaksjdhka kahsdkjahskdj aksdjak sjdhk asjhdkajshkdajh ksdhk ajhskd jahksdjak sjhdk ajshdkajshdkajhskd jasdha kjshdkja ksdjhak shdka jshkda hskdj ahskda dhak sjhdk ahskdhs</div>
  <p style="text-align: justify;">jaskjdhkas jdhkasjhdka sjhdkajs  hdkash kd jashk djah skd jahskdjhaksjdhka kahsdkjahskdj aksdjak sjdhk asjhdkajshkdajh ksdhk ajhskd jahksdjak sjhdk ajshdkajshdkajhskd jasdha kjshdkja ksdjhak shdka jshkda hskdj ahskda dhak sjhdk ahskdhs</p>`

  return (

    <MainBackgroundContainer>
      <MainHeader navigation={props.navigation} titleSize="30" titleMargin="10" />
      <MainTitle containerStyle={{ marginTop: 15 }}>Política de Privacidade</MainTitle>
      <ScrollView>
        <HTML html={html} textSelectable={false} baseFontStyle={styles.text} containerStyle={styles.container}/>
      </ScrollView>
    </MainBackgroundContainer>
  )

```
And we have this:

![WhatsApp Image 2020-07-09 at 19 55 08](https://user-images.githubusercontent.com/31750882/87098834-a0c08380-c21e-11ea-8228-e99e940c0da3.jpeg)

Obs.: text and container styles is just color.

**Comment by jsamr** [comment]
In the next major release, we are considering using https://github.com/styled-components/css-to-react-native to overcome this kind of issues. In the meantime, we might release a hotfix for `text-align` rules.

@Lucasark Please post your question on stackoverflow with the `react-native-render-html` tag, we will be happy to help you here.
