### ISSUE TITLE
URI content renders as undefined

### ISSUE THREAD

**Issue by psuslick** [archriss/react-native-render-html#254]
### Is this a bug report or a feature request?

Bug

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Unknown

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

import React, { Component } from 'react'
import {
  View,
  Text,
  Image,
  ImageBackground,
  ScrollView,
  StyleSheet,
  ActivityIndicator,
  AsyncStorage,
  WebView,
  Dimensions

} from 'react-native'

import HTML from 'react-native-render-html';

const htmlContent = 'http://motherfuckingwebsite.com';

export default class TabAmLeader extends Component {
    render () {
        return (
            <ScrollView style={{ flex: 1 }}>
                <HTML uri={htmlContent} />
            </ScrollView>
        );
    }
}

### Expected Behavior

I expected the website to render based on using the URI prop however the content renders with the text "undefined"

(Write what you thought would happen.)

### Actual Behavior

I expected the website to render based on using the URI prop however the content renders with the text "undefined"

![Screen Shot 2019-04-11 at 2 40 30 PM](https://user-images.githubusercontent.com/31072678/55982834-c3549d00-5c67-11e9-9028-a51649552484.png)

(Write what happened. Add screencasts/screenshots!)
### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by npaulConnvertex** [comment]
I am also facing the same issue.  when trying to render it shows undefined. PLease help

**Comment by alexsanderg** [comment]
I'm having the same problem. Any solution?

**Comment by jsamr** [comment]
`htmlContent` prop is for **raw html**. Use `uri` prop to achieve what you want. See the [documentation](https://github.com/archriss/react-native-render-html#props).

**Comment by jsamr** [comment]
I could reproduce the issue on the Demo, but your snippet is wrong... I'll reopen.

**Comment by jsamr** [comment]
The fix has been backported to v4.2.3-beta.1. See the instructions to test and report here #390!
