### ISSUE TITLE
Invalid YGDisplay 'inline-block'

### ISSUE THREAD

**Issue by WDDong** [archriss/react-native-render-html#257]
<img width="363" alt="DA2B8E4DF27DB292E483F8DA4DE282B7" src="https://user-images.githubusercontent.com/8448083/56414172-5ae76a80-62bc-11e9-8108-0f9111afdc14.png">

**Comment by nolife08021** [comment]
i have same issue like @WDDong  too.
any advices?

**Comment by hadi13** [comment]
same for me

**Comment by happylinhdn** [comment]
same for me

**Comment by Wellington01** [comment]
same for me

**Comment by sumudu-dewasurendra** [comment]
If anyone can put similar issues in here, at least we can ignore those styles and use this library :-D

**Comment by jpamarohorta** [comment]
I'm having the same issue. Created a [pull request](https://github.com/archriss/react-native-render-html/pull/282) that fixes it.

**Comment by AlanQuadros** [comment]
Just add 'display' in ignoredStyles.

Ex.: 
`ignoredStyles={['font-family', 'display']}`

**Comment by jpamarohorta** [comment]
Adding display to ignoredStyles can not always be possible. I have a case when if the display is “none” I want to hide the element for example.

**Comment by hai2san** [comment]
I'm having the same issue.

**Comment by jsamr** [comment]
This issue will be fixed in version 4.2.2.
A pre-release is already available if you want this fix now, see #385.
