### ISSUE TITLE
set a customizable warper container to be able to switch from Portrait to Landscape

### ISSUE THREAD

**Issue by BricePissard** [archriss/react-native-render-html#26]
To be able to smoothly switch from **Portrait** to **Landscape**, even encapsulated into 
```Animated.createAnimatedComponent( HTML );```
the view container doesn't handle ```Animated``` Object.

Could you convert the render() func returned View (line 131)

**from:**
```       
 return (
    <View style={this.props.containerStyle || {}}>
       { RNNodes }
    </View>
 );
```

**to:**
```       
 return (
    <Animated.View style={this.props.containerStyle || {}}>
       { RNNodes }
    </Animated.View>
 );
```

So we can send ```styles.containerStyle``` with Animated effect without rebuilding the view.

**Comment by Exilz** [comment]
Hi,
I'm wondering if there is any drawback to using `Animated.View` by default as the wrapper for every node if you're not planning on using any animation. Anyway, it feels weird to me.

Do you think it should be implemented with an optional prop for those who want to use it ?

Or we might even add a prop that renders a custom wrapper to give full control to users that want it. I guess that would be even better.

**Comment by BricePissard** [comment]
Yes that's right, a customizable container warper as a ```..prop``` with a default val set to ```<View/>``` would be more elegant. 

So this new prop would even replace the ```this.containStyle```:
```
const WarperElement = this.props.containerWarper || View;
return ( 
  <WarperElement>
     { RNNodes }
  </WarperElement>
);
```

**Comment by Exilz** [comment]
Hi again,
in the end, rather than adding a prop that allows developers to choose the wrapper element, I added a function that takes RNNodes as the first parameter so you'll be able to do anything  you want.
This should be useful for some special cases if someone wants to store the ref of the container or some stuff like that.

```javascript
// ... props
customWrapper: (RNNodes) => (<Animated.View>{ RNNodes }</Animated.View>)
```

**Comment by BricePissard** [comment]
It works as a charm.

Thanks for the update.
