### ISSUE TITLE
Custom render for HTML without surrounding tag

### ISSUE THREAD

**Issue by maggialejandro-rp** [archriss/react-native-render-html#260]
Hi, I need to create a custom render for the Text that wraps this:

```javascript
const demo = 'this is a text <b> with html tag </b>';
```

react-native-render-html: 4.1.2

Thanks in advance!

**Comment by chrise86** [comment]
@maggialejandro-rp did you manage to work it out?

**Comment by chrise86** [comment]
For me, styling using `rawtext` was enough.

**Comment by maggialejandro-rp** [comment]
@chrise86 yeah thanks, I had to add custom renders for `rawtext` and `textwrapper`
