### ISSUE TITLE
How to ignore trim the value between the tags?

### ISSUE THREAD

**Issue by ibnukipa** [archriss/react-native-render-html#261]
Asking for the clarity

I've read to README, entirety. I didn't find any question/thread regarding this.
How to ignore trim the value between the tags?

example:

`this is a link <a href="https://google.com" type="link" label="https://google.co">https://google.co</a>  <a href="/user/view/180" type="mention" label="Risal">Risal</a>`

it's the same if I use renderers function or use the default render, the **space** between tag <a> is trimmed somehow.

It's possible to ignore the trimming?

libs:
"react-native-render-html": "^4.1.2",
"react": "16.5.0",
"react-native": "latest",

**Comment by grnkvch** [comment]
You can replace all whitespaces in your text by this way
.replace(/\/a>\s<a/g, '/a>&shy; <a')
Looks ugly, but it works for me

**Comment by jsamr** [comment]
@ibnukipa I think you are referring to this issue: #118. Closing as I believe is duplicate. If you don't agree, feel free to answer.
