### ISSUE TITLE
Using Touchable* inside an inline renderer, such as `a`

### ISSUE THREAD

**Issue by rikkitissier** [archriss/react-native-render-html#262]
### Is this a bug report or a feature request?

Question (maybe feature request?)

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Environment

  Environment:
    React: 16.5.0
    React native: 0.57
    react-native-render-html: 4.1.2

### Explanation

On RN 0.55, I was able to create a renderer for `a` that returned a component that uses `TouchableOpacity`. My use case is creating rich mention tags; I look for links containing a particular attribute, and return a `<Mention />` component if it matches:

```
a: (htmlAttribs, children, convertedCSSStyles, passProps) => {
	if (htmlAttribs["data-mentionid"]) {
		return <Mention userid={parseInt(htmlAttribs["data-mentionid"])} name={passProps.rawChildren[0].data} key={passProps.key} />;
	}

	return a(htmlAttribs, children, convertedCSSStyles, passProps);
}
```

However, since upgrading to RN 0.57, this no longer works because `TouchableOpacity` returns a `View`, and I therefore get a "View in Text" error because the link is inside a paragraph.

Does react-native-render-html provide any way to work around this kind of situation? I'm not really sure what the solution would be - I guess somehow ensuring the previous `<Text>` is ended before my custom component and a new one opened after.

I know `<Text>` provides an `onPress` prop, but styling a `<Text>` isn't really flexible enough for my needs here unfortunately.

Thanks for any advice and/or considering this as a request!

**Comment by cristianocca** [comment]
Ever found a way/work around this? Have you tried also overwriting <p> tags so they do not render text?

**Comment by rikkitissier** [comment]
Not yet, no. I did try creating my own `p` renderer that returns a `View`
rather than `Text`, but then text doesn't flow properly. I haven't had a
chance to look into whether I can fix that with my own styles or not, yet.

**Comment by donni106** [comment]
So no way of having a `TouchableOpacity` for links at the moment?

**Comment by PhanQuy97** [comment]
### [`_****_`](

- url

)

**Comment by annie-elequin** [comment]
I'm also experiencing this because I want to use an inline "TextInput". however, nesting a TextInput inside a Text component doesn't work, and I can't wrap it in a View because of the "no View inside Text" error.

**Comment by ramirezjag00** [comment]
No luck using touchable* but text with onpress is working for me, just read how to use customRenderers for the other properties, I'm on RN 0.59.10:

```
 renderers={{
          a: (htmlAttribs, children) => {
            return (
              <Text
                onPress={() => Linking.openURL(htmlAttribs.href)}
              >
                {children}
              </Text>
            );
          },
        }}
```

**Comment by jsamr** [comment]
I am closing because this issue seems to have been resolved.

**Comment by jsamr** [comment]
Since the foundry release (v6), every custom renderer can use `onPress` prop! [See this example](https://meliorence.github.io/react-native-render-html/docs/guides/custom-renderers#minimal-example).
