### ISSUE TITLE
Error when rendering tag with custom tagStyle

### ISSUE THREAD

**Issue by juniorklein** [archriss/react-native-render-html#266]
### Is this a bug report or a feature request?

Bug

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Both

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

yes

### Environment

  Environment:
    React:16.8.3
    React native: 0.59.9
    react-native-render-html: 4.1.2

  Target Platform:
    Android (5.0)
    iOS (12)

### Steps to Reproduce

When I use the props `tagsStyles` with `fontFamily` point to a font named `NovelSansPro-SemiBold` we had a error 

### Expected Behavior

No error happened

### Actual Behavior

Failed prop type: Invalid prop `fontFamily` of type `number` supplied to `Text`, expected `string`.

### Identified Problem

In `HTMLStyles.js`, function `cssToRNStyle`, line 193, the code is parsing to float values that has "em" in the string (in my case "NovelSansPro-S **em** iBold") . I don't know the entire logic behind that function to solve problem and publish a pull request, but I believe I can help in the process to solve that problem.

**Comment by blyscuit** [comment]
I am also facing this problem and have to comment line 193 till 200. What is the fix to this?
