### ISSUE TITLE
twitter embed doesn't work

### ISSUE THREAD

**Issue by gunduzcihat** [archriss/react-native-render-html#267]
I've added code starting with <blockquote class="twitter-tweet"... but it doesn't show properly, just shows text.

result: 

<img width="332" alt="Screen Shot 2019-06-11 at 14 04 53" src="https://user-images.githubusercontent.com/24367679/59267073-f01a3600-8c51-11e9-8dda-08e962f98f87.png">

but expected:

<img width="316" alt="Screen Shot 2019-06-11 at 14 43 37" src="https://user-images.githubusercontent.com/24367679/59269254-4e95e300-8c57-11e9-9dfd-3c974c3a9a47.png">

I need your help.

**Comment by jariwalabhavesh** [comment]
@gunduzcihat : Have find any solution I have same issue I am not able to render twitter embedded.

**Comment by saitbnzl** [comment]
We've faced this issue a long time ago :) Have a look at #91

**Comment by gunduzcihat** [comment]
yeah saitbnzl, we figured it out that way.  thanks
