### ISSUE TITLE
[Help-Wanted] How can i update the height of image?

### ISSUE THREAD

**Issue by kamalpandey** [archriss/react-native-render-html#275]
```
alterChildren={node => {
    if (node.name === "iframe") {
        delete node.attribs.width;
        delete node.attribs.height;
     }
       if (node.name === "img") {
          delete node.attribs.width;
           node.attribs.height =
                (node.attribs.height * PixelRatio.get()) / 2;
<!-- here height is updated but in view it doesnot reflect --> 
        }
        return node.children;
    }}
```

**Comment by jsamr** [comment]
From version 5.x on, we have a new implementation to scale images. You can read [our RFC here](https://github.com/archriss/react-native-render-html/blob/master/rfc/001-A-deterministic-approach-to-images-scaling.adoc), and see the first pre-release implementing the RFC for images here: https://github.com/archriss/react-native-render-html/releases/tag/v5.0.0-alpha.1.
