### ISSUE TITLE
How to remove newlines

### ISSUE THREAD

**Issue by joshi-anshul** [archriss/react-native-render-html#279]
Hello,
I'm getting `<p><br></p><p><br></p>` type of response from API side, So how can I remove extra newlines? I already **read your documents** but not getting idea.
Please look into it.
Thanks

**Comment by Krypternite** [comment]
Hi,
Any progress on this. I am facing the same issue ?

**Comment by papercoding** [comment]
You can use ignoredTags to ignore the `<br>` tag. Ex: <HTML ignoredTags={['br']} />. Or you can use some String methods to remove `<br>` from the html string before set it to the <HTML />.

**Comment by jsamr** [comment]
I am closing because this issue seems to have been resolved.
