### ISSUE TITLE
LineHeight is inherited from first component in a paragraph instead of baseFontStyle

### ISSUE THREAD

**Issue by rikkitissier** [archriss/react-native-render-html#281]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

I have made a minimal repro in an expo snack instead

### Environment

React Native 0.59.8
react-native-render-html: 4.1.2

### Steps to Reproduce

1. Add a baseFontStyle with a lineHeight (other styles may be affected too, I'm not sure)
2. Add a custom renderer for `a`, which just returns a <Text> with some very basic style
3. Render a paragraph of text that has a link at the very start of the paragraph

### Expected Behavior

The link should receive styles applied to it, but the remainder of the paragraph should still get the lineHeight from baseFontStyle and not inherit the lineHeight given to the link component.

### Actual Behavior

The baseFontStyle lineHeight is overridden by the link's lineHeight for the rest of the paragraph. Some styles (e.g. color) seem to be preserved, but lineHeight and possibly others are not.

If the link appears elsewhere in the paragraph then it renders correctly. The problem is only seen when the link is the _first_ node in the paragraph.

![image](https://user-images.githubusercontent.com/10898472/62252824-eeebc680-b3c1-11e9-9020-a2d9e03bbcc6.png)

### Reproducible Demo

Minimal repro using Snack: https://snack.expo.io/@rikkitissier/trusting-milkshake

**Comment by jsamr** [comment]
@rikkitissier AFAIK, this is the intended behavior, because line-height is [an inheritable property](https://www.w3schools.com/cssref/pr_dim_line-height.asp). If you want to ignore line-height inline style, you can add it to `ignoredStyles` prop array.
