### ISSUE TITLE
react-native-webview changed from dependency to peerDependency

### ISSUE THREAD

**Issue by jpamarohorta** [archriss/react-native-render-html#284]
`react-native-webview` is currently a dependency at `^5.6.0` which can conflict if other version of the library is already being using standalone.

This can lead to errors, for example:
`Unhandled JS Exception: Tried to register two views with the same name RNCUIWebView`

Can the library be changed from dependency to peerDependency? is there a downside for that?

**Comment by bd-arc** [comment]
Done and available in version `4.2.0`.
