### ISSUE TITLE
Rendering html with DOCType and script/link tags doesn't work

### ISSUE THREAD

**Issue by msintaha** [archriss/react-native-render-html#287]
### Is this a bug report or a feature request?

Bug Report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

Environment:
    React: 16.8.3
    React native: 33.0.0
    react-native-render-html: 3.9.0

  Target Platform:
    Android (6.0)
    iOS (10.3)

### Steps to Reproduce
```
function getContent(content) {
  return `
  <html>
  <head>
    <style>
      body { background: red; }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.2/katex.min.css" integrity="sha256-uT5rNa8r/qorzlARiO7fTBE7EWQiX/umLlXsq7zyQP8=" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.2/katex.min.js" integrity="sha256-TxnaXkPUeemXTVhlS5tDIVg42AvnNAotNaQjjYKK9bc="></script>
  </head>
  <body>${content}</body>
  </html>
  `;
}
<HTML html={getContent('<h1>hello</h1>')} />
```
The code above doesnt execute the tags inside the head tag. But in RN `WebView` it works.

### Expected Behavior

The code above doesnt execute the tags inside the head tag. But in RN `WebView` it works.

### Actual Behavior

The code above doesnt execute the tags inside the head tag. But in RN `WebView` it works.

**Comment by jsamr** [comment]
@msintaha I think there is a misunderstanding on the scope of this library. This library does not claim support for executing scripts, but only rendering html. Plus, there is no DOM environment on which the script could be safely executed. WebView is what you need here!
