### ISSUE TITLE
Invalid props value from WYCIWYG

### ISSUE THREAD

**Issue by carylaw** [archriss/react-native-render-html#289]
The html content as below:
`<p style="text-align:start;">content here</p>`

reproduct like this:
`<HTML html={'<p style="text-align:start;">content here</p>'}  />`

invalid to error
[https://imgur.com/Y0ikMwn](url)

**Comment by jsamr** [comment]
See #257. As a workaround, you can ignore the `text-align` style rule with the `ignoredStyles` property.
