### ISSUE TITLE
new version should be released ASAP

### ISSUE THREAD

**Issue by ochanje210** [archriss/react-native-render-html#295]
https://github.com/archriss/react-native-render-html/commit/c16f249166c8355f52573718f040644c4c9c3a27

The commit above is critical for latest React Native versions otherwise you will get this error: 
![Screen Shot 2019-09-19 at 2 26 12 PM](https://user-images.githubusercontent.com/16204807/65216486-fee37500-daeb-11e9-81f5-b99719bf9bd8.png)

**Comment by jsamr** [comment]
I am closing because this issue has been resolved in a recent release.
