### ISSUE TITLE
Feature request: Whitelist tags

### ISSUE THREAD

**Issue by RWOverdijk** [archriss/react-native-render-html#299]
### Is this a bug report or a feature request?

Feature request

### Description

I'd like to be able to whitelist instead of blacklist tags.

I'll be using custom renderers for a couple of components, and want to disable all the rest instead of the other way around.

This might be weird to want. I am willing to implement this with some pointers.

**Comment by dburdan** [comment]
You could implement this using the `ignoreNodesFunction` param.

```js
const WHITELIST = ['p', 'img', 'em'];
...
ignoreNodesFunction={(node, parentTagName, parentIsText) => {
  if (!node.name || WHITELIST.includes(node.name)) {
    return false; // Don't ignore
  }
  return true; // Skip this tag since it's not in the whitelist array
}}
...
```

**Comment by RWOverdijk** [comment]
That's a pretty creative solution you got there. Thanks!

**Comment by jedahan** [comment]
Would you mind if I made a PR to document this solution in the readme?

**Comment by jsamr** [comment]
@jedahan Yes, you are welcome to do so!
