### ISSUE TITLE
Empty unordered list causes exception

### ISSUE THREAD

**Issue by peacechen** [archriss/react-native-render-html#30]
An empty unordered list `<ul></ul>` appearing anywhere in the markup causes an exception `children.map is not a function` in HTMLRenderers.

Line 52 does not check for empty children
```
children = children.map((child, index) => {
```

Unfortunately I can't control the incoming content and it is valid HTML. Working on a PR.

**Comment by Exilz** [comment]
Hi again @peacechen, great catch.

It should be easy to fix by checking if `children` is actually an `array` [here](https://github.com/archriss/react-native-render-html/blob/master/src/HTMLRenderers.js#L52), looking forward to your PR 😄

**Comment by peacechen** [comment]
Created PR #31

**Comment by Exilz** [comment]
Published in the latest release (`3.4.0`), I'll merge it as soon as Github starts working again.

Thanks for the fix !
