### ISSUE TITLE
Content having '\n' not breaking to new line

### ISSUE THREAD

**Issue by akhilsanker** [archriss/react-native-render-html#303]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both the platforms

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

No

### Environment

    React: 16.8.3
    React native: 0.59.8
    react-native-render-html: 4.1.2

    Target Platform:
      Android (9.0)
      iOS (12.1)

### Steps to Reproduce

(Write your steps here:)

1. HTML content with '\n' for new line break.
2. After rendering html content , '\n', is not getting break to new line.

### Expected Behavior

To get the html content break to new line with '\n'.
![Simulator Screen Shot - iPhone X - 2019-10-09 at 16 10 48](https://user-images.githubusercontent.com/32122016/66474702-7125f480-eaaf-11e9-98d4-6be6ae33fa90.png)

### Actual Behavior

The line is not breaking with '\n'.

![Simulator Screen Shot - iPhone X - 2019-10-09 at 16 10 59](https://user-images.githubusercontent.com/32122016/66474739-8733b500-eaaf-11e9-88ad-801401e17742.png)

Thanks

**Comment by lengieng** [comment]
You can use `<br>` for line break in HTML.

**Comment by akhilsanker** [comment]
@lengieng ,
There are some limitations in providing `<br>` for line break in HTML content. The line break is denoted by `'\n'` in HTML content.

**Comment by lengieng** [comment]
@akhilsanker , what is the reason of using `\n` instead of `<br>`? `\n` is not a valid HTML tag. Therefore, it makes sense that the html parser won't pass it. Does your HTML content contain a code block which should be wrapped by `<pre>` tag?

**Comment by jsamr** [comment]
I am closing this issue because, as commented, `\n` is not interpreted in html.
