### ISSUE TITLE
WebView is depreciated

### ISSUE THREAD

**Issue by presencewebdesign** [archriss/react-native-render-html#304]
WebView will not work with version RN 0.61.0

Update the following file 
/node_modules/react-native-render-html/src/HTMLRenderers.js

Add this 
import { WebView } from 'react-native-webview'; 

And remove WebView from this line 
import { TouchableOpacity, Text, View, **WebView**, Platform } from 'react-native';

PS: when will this be updated?

**Comment by Utkarshkataria** [comment]
It worked.. Thanks.

**Comment by mtnptrsn** [comment]
This is already fixed in master, the issue is that it hasn't yet been released. When can we expect another release?

**Comment by maicolsantos** [comment]
When are you planning to launch release?

**Comment by vomchik** [comment]
@ThomasHenrissat  Could you please release a new version? 🙏

**Comment by ThomasHenrissat** [comment]
Sorry I'm not in charge of this repo, please use the master branch for now.

**Comment by vomchik** [comment]
i see, thanks

**Comment by jsamr** [comment]
I am closing because this issue has been resolved in a recent release.
