### ISSUE TITLE
iOS: CSS border-style=none is invalid - causes RN red screen warning

### ISSUE THREAD

**Issue by tdoran** [archriss/react-native-render-html#319]
iOS native styling can't accept border style as `none`. If HTML containing `style="border-style: none;` is passed in, RN Red-screen warning is shown on RN debug mode:
`Invalid RCTBorderStyle 'none'. should be one of: (dashed, dotted, solid)`

![Simulator Screen Shot - iPhone X - 2019-11-22 at 11 18 45](https://user-images.githubusercontent.com/29519739/69424573-e0367000-0d20-11ea-9098-a0ce5a98c6cd.png)

### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

iOS only

### Is the bug reproductible in a production environment (not a debug one)?

Not testable at present

### Environment

  Environment:
    React: 16.9.0
    React native: 0.61.2
    react-native-render-html: 4.1.2

  Target Platform:
    iOS 12.4

### Steps to Reproduce

1. pass in any html with `style="border-style: none;`
2. Try to render it in debug mode
3. There is no visible border, but there is a warning

e.g. `<iframe src="www.example.org" scrolling="no" style="border-style: none; width:100%; height:290px;"></iframe>`

### Expected Behavior

react-native-render-html renders the HTML without warning - and converts `border-style=none` to the correct format for iOS native styling.

### Actual Behavior

RN gives red screen warning:
`Invalid RCTBorderStyle 'none'. should be one of: (dashed, dotted, solid)`

**Comment by WLYau** [comment]
I'm experiencing the same issue and tried using ErrorBoundary to capture the error but that didn't work.
