### ISSUE TITLE
Can I use this library to render html generated by the Rich editors like Quill and draft.js?

### ISSUE THREAD

**Issue by sarang-naico** [archriss/react-native-render-html#322]
Hi,
We have some HTML content generated by using Quill editor, can I use this library to render that HTML?

**Comment by rikkitissier** [comment]
Yes. You may need to write some custom renderers and/or tag styles depending on what your content contains, but otherwise that's exactly what this library is designed to do.

**Comment by gvsakhil** [comment]
Ya @sarang-naico I am using this to display the content generated by Quill editor. Its working awesome. I just added a small tweek for Tables and other than that everything is fine for me.

**Comment by jsamr** [comment]
I am closing because this issue seems to have been resolved.
