### ISSUE TITLE
Android release build issue with version 4.2.0

### ISSUE THREAD

**Issue by ravirupareliya** [archriss/react-native-render-html#329]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes

### Environment

    Environment:
        React: 16.8.3
        React native: 0.59.10
        react-native-render-html: 4.2.0

### Steps to Reproduce

(Write your steps here:)

1. Generate signed apk or production build for android

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

It gives below error while creating signed apk

`
Unable to resolve module 'react-native-webview' from '/node_modules/react-native-render-html/src/HTMLRenderers.js': Module 'react-native-webview' does not exist in the Haste module map
`

**Comment by a-skuba** [comment]
Since *4.2.0* you have to use `react-native-webview`: [diff 4.1.2..master](https://github.com/archriss/react-native-render-html/compare/4.1.2...master).
Look at commit [c16f249](https://github.com/archriss/react-native-render-html/commit/c16f249166c8355f52573718f040644c4c9c3a27) and commits after.

It would be great to somehow configure to not use iframes, which requires the unpleasant package.

**Comment by ravirupareliya** [comment]
Does it mean we have to install `react-native-webview` separately? I am not using iframes anywhere, it is just simple html tags like `<br>` and `<ul> <li>`

**Comment by a-skuba** [comment]
Yes, you have to install `react-native-webview`.
The PR you are sending is not fixing anything, some more refactor is needed.

**Comment by ravirupareliya** [comment]
PR I have sent will not require user to install `react-native-webview` additionaly

**Comment by a-skuba** [comment]
@bd-arc you can close this :)
