### ISSUE TITLE
Build Fail Critical

### ISSUE THREAD

**Issue by nithinyell** [archriss/react-native-render-html#332]
```
warning " > react-native-render-html@4.2.0" has unmet peer dependency "prop-types@>=15.5.10".
warning " > react-native-render-html@4.2.0" has unmet peer dependency "react-native-webview@*".
```

FAIL:
`Unable to resolve module `react-native-webview` from `/Users/runner/runners/2.163.1/work/1/s/XXXXXXX/node_modules/react-native-render-html/src/HTMLRenderers.js`: Module `react-native-webview` does not exist in the Haste module map
`

@bd-arc please take a look.

This is happening after your changes happened two days ago.

**Comment by bd-arc** [comment]
Please read the doc: `react-native-webview` is now a peer dependency and you need to install it yourself.

**Comment by nithinyell** [comment]
@bd-arc 
Will check and get back.
