### ISSUE TITLE
4.2.0 is a breaking change

### ISSUE THREAD

**Issue by f-roland** [archriss/react-native-render-html#334]
Hi, 

I removed the issue template cause this isn't a bug with the code itself, but the versioning.

Because of the change to react-native-webview being a peer dependency, the consequence is that projects updating from 4.1.2 to 4.2.0 will break, unless another dependency is being added. 

The deed is done, but this is a violation of semver principles.

**Comment by ncryer** [comment]
Tagging on here to add that I get the following upon updating from 4.1.2 to 4.2.0: 
 
`Unable to resolve "./Stream.js" from "node_modules/htmlparser2/lib/index.js"`

**Comment by jsamr** [comment]
@ncryer See fb55/htmlparser2/issues/499
Have you tried removing node_modules and `npm i`?

**Comment by jsamr** [comment]
@f-roland I agree with you. We will make sure it does not happen again.
