### ISSUE TITLE
Please remove deprecated PropTypes

### ISSUE THREAD

**Issue by zamponotiropita** [archriss/react-native-render-html#338]
PropStyles (e.g. `Image.propTypes`) are deprecated in the current RN version. Please remove them.
Otherwise compatibility with the current `react-native-web` (1.12.0) is broken as it has completely removed PropTypes

**Comment by denissb** [comment]
I opened a PR for this, the approach is a bit hackish but it works until the package migrates to flow or TypeScript: https://github.com/archriss/react-native-render-html/pull/346

**Comment by jsamr** [comment]
This issue will be fixed in version 4.2.2.
A pre-release is already available if you want this fix now, see #385.
