### ISSUE TITLE
Custom renderers receiving no children as params

### ISSUE THREAD

**Issue by nikola-kolosek** [archriss/react-native-render-html#340]
### Is this a bug report or a feature request?

Bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes, I have

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes, I have

### Have you made sure that your issue hasn't already been reported/solved?

Yes, I have

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms

### Is the bug reproductible in a production environment (not a debug one)?

Yes, it is

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes, I have

### Environment

```
    React: 16.8.6
    React native: 0.60.0
    react-native-render-html: 4.2.0 (master)
```
Target Platform:
(They really don't matter, it's a js issue)
    Android API 28 (9.0)
    iOS (13.3)

### Steps to Reproduce

1. Try to use custom renderers as the documentation states
2. Provide the parameter for the custom renderer
3. Log the parameter to the console in order to see what it contains
e.g.
```
// Copied from the demo project
const CUSTOM_RENDERERS = {
  p: params => {
    console.log(JSON.stringify(params))
    return <Text>{params.children[0]}</Text> // This should be working, but params.children is undefined, thus it will throw an error
  },
}
```

### Expected Behavior

The fields inside `params` should exist

### Actual Behavior

![image](https://user-images.githubusercontent.com/49228982/74153738-8a7fae80-4c11-11ea-9372-da9dabf93351.png)
As you can see, the `children` field is nowhere to be found. The snippets used are the ones provided in the demo. I should see the text nodes as children. I don't even see the `strong` nodes when I insert them inside the `p` element

### Reproducible Demo

Inside your demo, paste my custom renderer

**Comment by jsamr** [comment]
@nikola-kolosek It is hard to help you since you don't provide the exact html extract that you pass to the HTML component which result in the behavior you are describing.

**Comment by jsamr** [comment]
I'm closing now, feel free to comment if you are still facing this issue.

**Comment by jsamr** [comment]
@nikola-kolosek Looking again at your example, it seems that you are misunderstanding the custom renderer API. This first argument is a node attributes argument, and does not contain any children property. [You're looking for the second argument](https://github.com/archriss/react-native-render-html#creating-custom-renderers) provided to the renderer function.
