### ISSUE TITLE
⚠️ Security issue: script tags are allowed by default due to typo in IGNORED_TAGS

### ISSUE THREAD

**Issue by rufusraghunath** [archriss/react-native-render-html#342]
### Is this a bug report or a feature request?

Bug

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yes

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yes

### Have you made sure that your issue hasn't already been reported/solved?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms

### Is the bug reproductible in a production environment (not a debug one)?

Yes

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

Yes.

### Environment

All environments.

### Steps to Reproduce

1. Check the `IGNORED_TAGS` array in `src/HTMLUtils.js`
2. There is a typo where the HTML tag `script` appears instead as `scripts`
3. Note that there is a [similar issue](https://github.com/archriss/react-native-render-html/issues/249) already filed for another typo (`diaglog` instead of `dialog`)

### Expected Behavior

For security reasons, `script` tags should be ignored by default. This appears to have been the author's intention, but it's not working due to the typo.

### Actual Behavior

`script` tags are allowed by default.

### Reproducible Demo

N/A, typo clearly visible in source code

**Comment by rufusraghunath** [comment]
Please merge [this](https://github.com/archriss/react-native-render-html/pull/272) existing PR to fix the issue.

**Comment by jsamr** [comment]
This issue will be fixed in version 4.2.2.
A pre-release is already available if you want this fix now, see #385.
