### ISSUE TITLE
On android, the last line is missing

### ISSUE THREAD

**Issue by xusir2** [archriss/react-native-render-html#348]
On android 9.0 and above, the last line of rich text is only half displayed, how to resolve.

**Comment by nschild** [comment]
@xusir2 we are seeing this too. There is a bug in React Native on Android Q here is the issue filed in their repo facebook/react-native#25258 most probable is that we'll need to wait until this is fixed on their end.

**Comment by nschild** [comment]
@xusir2 this PR seems to fix it. https://github.com/archriss/react-native-render-html/pull/305 Just set textBreakStrategy='simple' 

related to https://github.com/facebook/react-native/issues/25258

**Comment by xusir2** [comment]
I'm glad that you can reply to my question, but the problem has not been solved yet. I added textBreakStrategy='simple' under the Text, but it still failed to display properly, and react-native 0.59.9 was used

**Comment by nschild** [comment]
@xusir2 did you apply the changes from the PR I linked?

**Comment by xusir2** [comment]
@nschild Thank you for your patience.The problem has been solved
