### ISSUE TITLE
Is it using UIWebView?

### ISSUE THREAD

**Issue by yuanbolin** [archriss/react-native-render-html#351]
App Store Connect:
TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by pxmage** [comment]
I am developing with this library as well, if it's true and if there is no update or fix on replacing UIWebView, that would be a disaster to the project I am doing now :(

**Comment by pxmage** [comment]
hey @yuanbolin 

I just got some clue from google.

I found that in `package.json` of `react-native-render-html`, it declares `'react-native-webview': '*'` as a peer dependency, which you might be using in a low version.

`react-native-webview'` removed UIWebView sinced version `7.0.1`, check here: https://github.com/react-native-community/react-native-webview#versioning

Just my guess :)

**Comment by vwpo** [comment]
Please make an update on this topic. What should I do if I want to continue work with this library?

**Comment by hussainb** [comment]
any updates on this issue? I was wanting to use this library in my app.
Is there any other way to render html in react native?
https://github.com/jsdf/react-native-htmlview does not use webview, but it seems its not being maintained.

**Comment by kptac** [comment]
I use this package and launched 2 new apps on AppStore 2 weeks ago without any issues. No email notices on API usage were sent. I did update the SDK to v37 though. This is important because, in v36, I did get the email with API deprecation msgs. But after upgrading, I didn't.

My package.json:
```
"react-native-render-html": "^4.2.0",
"react-native-webview": "8.1.1",
```

**Comment by yuanbolin** [comment]
SDK name?

**Comment by hussainb** [comment]
Thanks @kptac

**Comment by jsamr** [comment]
I am closing because the issue seems to have been elucidated.
