### ISSUE TITLE
How to add an anchor Link 

### ISSUE THREAD

**Issue by asma-rgb** [archriss/react-native-render-html#353]
How can i use an anchor link using react-native-render-html ?
I used Linking.openURL(url) with external link,,
 what about the anchor link ?

**Comment by mehul2013** [comment]
I also want to open an external link. Is there any reference for this?

**Comment by AlishahSolanki** [comment]
<HTML html={item.getDefaultValue()} onLinkPress={(ev, href, htmlAttribs) => Linking.openURL(href)}
this way u can acheive it @mehul2013 @asma-rgb
