### ISSUE TITLE
question regarding html tags

### ISSUE THREAD

**Issue by sjaloomconnect** [archriss/react-native-render-html#354]
I have a question, I am using this plugin to dislay html and seems to be working fine.
But I am wondering, if I can remove certain style tags from a string before rendering it.

For example:

<p><span style="color:'#000';font-size:16px;">Some text</span></p>

I want to remove the color:'#000' part (keeping the font-size), but not sure if that can be done via this plugin.

Anyone an idea?

**Comment by gvsakhil** [comment]
Use ignoredStyles

<HTML html={content} ignoredStyles={['height', 'width', 'font-family', 'letter-spacing']} imagesMaxWidth={Dimensions.get('window').width} style={{ width: '100%', marginTop: 40 }} />

**Comment by jsamr** [comment]
I am closing because this issue seems to have been resolved.

**Comment by DeepakSharma04** [comment]
```
const source = {
  html: '<p><img src="https://qa.productdemourl.com/siva/public/storage/tinymce_attachments/62a91ba4-6070-4029-9020-0d4b9e02af39/mceclip0.png" width="1200" height="983" alt="mceclip0.png"></p>'
};


 <RenderHtml
        source={source}
        ignoredStyles={['height', 'width']} 
       />

```
Above ignoredStyles is not working , I am not able to remove height and width and not get full size image also side view is broken. Please help ..!!

    "react-native-render-html": "^6.3.4",
