### ISSUE TITLE
How to bind an image

### ISSUE THREAD

**Issue by maicolsantos** [archriss/react-native-render-html#365]
I open a PR where it is possible to get the image uri by a method called "onImagePress"

PR #364

**Comment by rafaelbpa** [comment]
Please approve this when possible. I need this feature too.

**Comment by marcelofreires** [comment]
Nice. This can help me too

**Comment by davigurgel** [comment]
I need this feature, please approve.

**Comment by sergiosilvajr** [comment]
Plz, me too..

**Comment by maicolsantos** [comment]
I solved it by binding the image using the renderers props

**Comment by Aiosa** [comment]
The api is different for a renderer callback, it receives an object so if you need the image URI, the path is `attribs.tnode.init.domNode.attribs` if attribs is the first argument.

**Comment by jsamr** [comment]
@Aiosa Simpler: `props.tnode.attributes`
