### ISSUE TITLE
Could not find a declaration file for module...

### ISSUE THREAD

**Issue by ghost** [archriss/react-native-render-html#370]
After import the module...

`import HTML from 'react-native-render-html';`

i've this warning

```
Could not find a declaration file for module 'react-native-render-html'. '...../node_modules/react-native-render-html/index.js' implicitly has an 'any' type.
Try `npm install @types/react-native-render-html` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-render-html';`
```

The command "npm install @types/react-native-render-html" return 404

Thanks

**Comment by jsamr** [comment]
Typescript declarations have just been merged and release, upgrade to v4.2.1 and your problem will be solved!
