### ISSUE TITLE
How to render 3 images in vertically center?

### ISSUE THREAD

**Issue by sunilprajapatisa** [archriss/react-native-render-html#371]
Here is sample HTML code for 3 image render should be vertically centred. **And also should be in One Line**

 ```
const htmlDescriptionContent = `<p style="text-align:center"><img alt="" src="https://fomoyolo-dev-assets.s3.amazonaws.com/image-gallery/c4ea7600-9acb-11ea-a7d0-9bf50f73b3c4.jpg" style="height:32px; width:32px" />&nbsp; <img alt="" src="https://fomoyolo-dev-assets.s3.amazonaws.com/image-gallery/5358e030-9ad0-11ea-a7d0-9bf50f73b3c4.jpg" style="height:32px; width:32px" />&nbsp;&nbsp; <img alt="" src="https://fomoyolo-dev-assets.s3.amazonaws.com/image-gallery/99439680-9ad0-11ea-a7d0-9bf50f73b3c4.jpg" style="height:32px; width:57px" />
> </p>`

<HTML
      containerStyle={{ width: '100%' }}
      html={htmlDescriptionContent}
      imagesMaxWidth={Dimensions.get('window').width}
      onLinkPress={(evt, href) => this.props.onLinkPress(evt, href)}
/>
```

**What get result:**
![Screenshot 2020-05-21 at 6 57 40 PM](https://user-images.githubusercontent.com/29479459/82563588-fa002500-9b94-11ea-94e8-aeda92bbe5cd.png)

**Want Result:**
![Img_ResultShouldBe](https://user-images.githubusercontent.com/29479459/82563313-79d9bf80-9b94-11ea-918e-606000ceef7d.png)

Followed readme file and prepared a demo.

**Comment by murilobd** [comment]
try to change the tag for images and add a flexDirection as row
```
const tagsStyles = {
    img: {
      flexDirection: "row"
   }
}

<HTML
     containerStyle={{ width: '100%' }}
     html={htmlDescriptionContent}
     imagesMaxWidth={Dimensions.get('window').width}
     onLinkPress={(evt, href) => this.props.onLinkPress(evt, href)}
     tagsStyles={tagsStyles}
/>

```

**Comment by sunilprajapati714** [comment]
> tagsStyles={tagsStyles}

Not working

**Comment by sunilprajapati714** [comment]
> try to change the tag for images and add a flexDirection as row
> 
> ```
> const tagsStyles = {
>     img: {
>       flexDirection: "row"
>    }
> }
> 
> <HTML
>      containerStyle={{ width: '100%' }}
>      html={htmlDescriptionContent}
>      imagesMaxWidth={Dimensions.get('window').width}
>      onLinkPress={(evt, href) => this.props.onLinkPress(evt, href)}
>      tagsStyles={tagsStyles}
> />
> ```

Not working

**Comment by sunilprajapati714** [comment]
Any updates on this?

**Comment by sunilprajapati714** [comment]
@Exilz , Any update on this?

**Comment by jsamr** [comment]
Currently this is not supported, because we break the inline formatting context to block when encountering `img` tags. This is because until recently, RN didn't support Views as children of Text nodes. We will allow this in a future release, where you'll be able to have more fine-grained control over layout.

**Comment by sunilprajapatisa** [comment]
Please do need full for this issue asap because my app have feature to to display images inline. Also I tried do solved but no get success and I'm stuck in this issue.

**Comment by jsamr** [comment]
Closing in favor of #428
