### ISSUE TITLE
Re-render html to change colors

### ISSUE THREAD

**Issue by aleixo** [archriss/react-native-render-html#377]
Hello all

I have been using this lib a while now. It does very well the work. But now i have a requirement that is to change the colors of based on the theme.

For that, for now, i have my styles on `classStyles` and `tagStyles` props that will adapt to the theme that i have applied. In order for the styles to be used i have to re-render the complete html that depending on the html size will or not be noticed by the user.

Do you think there is a more efficient solution for that?

Thank you very much.

**Comment by jsamr** [comment]
In version 4.2.2, HTML component will re-render on tagsStyles and classesStyles changes, if this is what you meant.
You can test a pre-release version now, see #385.
