### ISSUE TITLE
Not getting htmlAttribs in some case

### ISSUE THREAD

**Issue by Dani93380** [archriss/react-native-render-html#38]
when i create a custom renderer ,if a text is wrapped inside a div like `<div prop="value"> hello </div>`
then htmlAttribs is equal to an empty object.
But if the text inside the div is wrapped into a paragraph like `<div prop="value"><p> hello</p> </div>`
everything work fine , htmlAttribs is equal to {"prop":"value"}

**Comment by Exilz** [comment]
Hi,
great catch, thank you.

This bug is induced by [this logic](https://github.com/archriss/react-native-render-html/blob/master/src/HTML.js#L254-L257).
I'll change it so it doesn't move *every* attribute to the child, but only the `style` one.

**Comment by Dani93380** [comment]
You welcome , nice lib by the way!!

**Comment by Exilz** [comment]
This is fixed in `3.5.0-rc.4`, along with major styling fixes. This made me discover some other bugs 😛 

I'll re-open if it didn't fix it for you.
