### ISSUE TITLE
Android: Not display any content or paragraph HTML.

### ISSUE THREAD

**Issue by sseyha** [archriss/react-native-render-html#39]
It's working fine with iOS, but it's not working on Android.
All the paragraph display in White (Blank) but image appear in the paragraph.
Could anyone give an advise please???

**Comment by Exilz** [comment]
Please show us the HTML you're trying to render, and the props you're using.
You should also start the demo on your android and check if it works.

**Comment by sseyha** [comment]
Thank for fast response.
Here is my scenario:

"moment": "^2.19.1",
"native-base": "^2.3.3",
"react": "^16.0.0",
"react-native": "^0.49.3",
"react-native-render-html": "^3.5.0-rc.3",

====
I find out it problem is about Font-Color.
After i render the HTML and set backgroundColor into **Red** because font-color become into White Color. That's why could not display those tag.
However, i could not customize the font color as well.
Any advise???

**Comment by sseyha** [comment]
![simulator screen shot - iphone 6 - 2017-11-06 at 10 39 21](https://user-images.githubusercontent.com/7949290/32424397-c8c495de-c2de-11e7-9439-214a505db6be.png)
![screenshot_1509939565](https://user-images.githubusercontent.com/7949290/32424399-ca7395ba-c2de-11e7-9122-02dc838bf1c6.png)

======
This is what is display...
All font become in White Color.
That's won't display properly as iOS in Android.
Could you please fix this issue???

**Comment by sseyha** [comment]
All text in tag <p> become in White Color in Android device.
That's why it won't display properly as iOS.

Below what i have customize the font color:
`<HTML html={item.content} tagsStyles={{p:{color:'#555'}}} imagesMaxWidth={width-40} />`
