### ISSUE TITLE
🚀 Feedback for v4.2.3 drafts

### ISSUE THREAD

**Issue by jsamr** [archriss/react-native-render-html#390]
Following the release of version 4.2.2, [a new small pre-release is available](https://github.com/archriss/react-native-render-html/releases/tag/v4.2.3-beta.1) with a few fixes backported from master.

To test this release, simply install the package with the next tag:

    npm i --save react-native-render-html@next

**Please tell us how it works out for you!** Don't forget to mention the exact version you're testing. Current latest `next` tag: 

<p align="center"><img src="https://img.shields.io/npm/v/react-native-render-html/next" /></p>

And build status:

<p align="center"><img src="https://github.com/archriss/react-native-render-html/workflows/CI/badge.svg?branch=release/4.2.2" /></p>

Enjoy!

**EDIT** If you are upgrading from a version lower than 4.2.0, you must install `react-native-webview` manually because it became a peer dependency.

**Comment by vijay-mca** [comment]
i i am using npm i --save react-native-render-html@next i got this error
![Screenshot_1596525949](https://user-images.githubusercontent.com/45515876/89265322-ec195680-d651-11ea-9f2f-f8f049e252a4.png)

**Comment by jsamr** [comment]
@vijay-mca If you are upgrading from a version earlier than 4.2.0, this is our "fault". We should have published a new major, because react-native-webview became a peer dependency (a dependency you must install by yourself). 

Just `npm install react-native-webview` and you should be good to go.
