### ISSUE TITLE
tagsStyles property cannot edit all React Native StyleSheet properties because it is not called until after mounting

### ISSUE THREAD

**Issue by isaiahnixon** [archriss/react-native-render-html#40]
The problem arises when a property that affects the mounting of the referenced component is adjusted through <code>tagsStyles</code>. To replicate my exact error simply adjust the <code>resizeMode</code> of an <code>img</code> tag from a <a href="https://github.com/react-community/create-react-native-app">create-react-native-app</a>.

**Comment by Exilz** [comment]
This has been fixed in `3.8.0`, better late than never!
