### ISSUE TITLE
PropTypes being deprecated

### ISSUE THREAD

**Issue by megantaylor** [archriss/react-native-render-html#400]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [x] I have read the documentation here: https://git.io/JJcAl 
- [x] I have checked that this enhancement has not been asked yet

### Decision table

- [x] The change I am requesting is not a new prop
- [x] The change I am requesting does not provide support for a HTML element,
  attribute, CSS rule or anything related to HTML and CSS standards
- [x] The change I am requesting  does not provide support for a React Native
  feature

### Enhancement

Just an FYI that you might want to ditch propTypes or add compatible TypeScript types because propTypes are being deprecated in react-native. 

Some context:

I'm using this with react-native-web (https://github.com/necolas/react-native-web) which has removed propTypes in advance of propTypes being deprecated in react-native. To make this library work, I had to patch the reference to Image.propTypes.style in HTMLImage.js.

**Comment by jsamr** [comment]
@megantaylor I thought we had fixed that in #346 which has been merged. Which version of this library have you tried?

**Comment by megantaylor** [comment]
@jsamr ahhh, we're using 4.2.0. I'll try updating tomorrow!

**Comment by megantaylor** [comment]
updated and everything looks great!

**Comment by jsamr** [comment]
@megantaylor I am glad it worked out!

**Comment by amhouel** [comment]
Actually @jsamr with this new version that my colleague @megantaylor installed, we are now getting a typescript error in the `alterNode` function that I'm using as described in your documentation:
https://github.com/archriss/react-native-render-html#alternode

```
alterNode: (node) => {
  const { name, parent } = node;
  // If the tag is an <a> and we've found a parent to be a blockquote
  // (see the utils part of this documentation to know more about getParentsTagsRecursively)
  if (
    name === "a" &&
    getParentsTagsRecursively(parent).indexOf("blockquote") !== -1
  ) {
    // Let's assign a specific color to the node's attribs (if there already are)
    node.attribs = { ...(node.attribs || {}), style: `color:lightblue;` };
    return node;
  }
  // Don't return anything (eg a falsy value) for anything else so nothing is altered
};
```
The error is: `Property 'name' does not exist on type 'HTMLNode'`
Could the type of `node` be fixed?

**Comment by jsamr** [comment]
@amhouel I'll take a look tomorrow!

**Comment by amhouel** [comment]
Thank you @jsamr!

**Comment by jsamr** [comment]
@amhouel The reason is that `name` attribute only appears to HTMLTagNodes while HTMLNode is defined as  `HTMLTagNode | HTMLTextNode;` So you could rewrite:

```ts
import { HTMLTagNode } from 'react-native-render-html';
// ...
const { name, parent } = (node as HTMLTagNode);

**Comment by amhouel** [comment]
Perfect! Thank you @jsamr for taking the time to look at this!

**Comment by jahead** [comment]
Someone should update the peer dependencies?

**Comment by AlexJeeee** [comment]
@jsamr Thank you for the solution! but I still have some problems:
```
alterNode={(node) => {
                const {name} = node as HTMLTagNode;
                if (name === 'img') {
                  node.attribs = {
                    ...(node.attribs || {}),
                    style: `min-height: 1px;
                    max-width: ${maxWidth}px `,
                  };
                  return node;
                }
              }}
```
the max-width style doesn't work when I set it with a variable, but works if I set it with a static value such as '300', do you know why? thx~
