### ISSUE TITLE
<font color='red'>&#x20b9;&nbsp;270</font>

### ISSUE THREAD

**Issue by jamesawer3** [archriss/react-native-render-html#405]
### Decision table

- [ ] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless
  we claim support for it),
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Bug Report

The HTML element given inside font is not rendering the color just rendering the content.

##### React Native

```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 567.61 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

```

##### Libraries

- react-native-render-html: 6.14.8
- react-native-webview: 6.14.8

#### Devices

- Device 1
  * OS: All Android devices
  * Diagnostic: reproduction
  * Environment: development
- Device 2 
  * OS: All Android devices
  * Diagnostic: reproduction
  * Environment: development

##### Description

(Write your steps here:)

1. Just used the npm
2. Add this code ```<font color='red'>&#x20b9;&nbsp;270</font>```

**Comment by jsamr** [comment]
@jamesawer3 This library does not provide a renderer for the `font` tag, but you could write a [custom renderer](https://github.com/archriss/react-native-render-html#creating-custom-renderers). This is a feature request rather than a bug! But we won't access this request because [this tag is deprecated](https://www.w3schools.com/tags/tag_font.asp).

**Comment by jamesawer3** [comment]
Thanks for your immediate response!!!
Can you please just give me an example for render this?
```<font color='red'>&#x20b9;&nbsp;270</font>```

**Comment by jsamr** [comment]
@jamesawer3 Here is a very basic implementation covering the "color" attribute. It makes me realize the API improvement we can make to enhance extensibility! Certainly a feed to craft the v6 API. But I want to emphasize that this is an obsolete tag, [as stated by MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font):

> This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.

```js
import * as React from "react";
import { View, StyleSheet, Text } from "react-native";
import Constants from "expo-constants";
import { default as HTML } from "react-native-render-html";
import { cssStringToRNStyle } from "react-native-render-html/src/HTMLStyles";

function isFontAttribute(attrName) {
  return attrName === 'color';
}

function extractInlineStyleFromFontAttributes(fontAttribs) {
  return Object.keys(fontAttribs)
    .filter(isFontAttribute)
    .map((attrName) => `${attrName}: ${fontAttribs[attrName]};`)
    .join();
}

const renderers = {
  font: {
    wrapper: "Text",
    renderer: function (
      htmlAttribs,
      children,
      convertedCSSStyles,
      passedProps
    ) {
      const { key } = passedProps;
      const stylesFromFontAttributes = cssStringToRNStyle(
        extractInlineStyleFromFontAttributes(htmlAttribs),
        'text',
        passedProps
      );
      return (
        <Text style={[convertedCSSStyles, stylesFromFontAttributes]} key={key}>
          {children}
        </Text>
      );
    },
  },
};

const html = `
<p>Hello world</p>
<font color="red">&#x20b9;&nbsp;270</font>
`;

export default function App() {
  return (
    <View style={styles.container}>
      <HTML html={html} renderers={renderers} />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    paddingTop: Constants.statusBarHeight,
    backgroundColor: "#ecf0f1",
    padding: 8,
  },
});
```
