### ISSUE TITLE
Math functions with HTML content.

### ISSUE THREAD

**Issue by ankitaptagline** [archriss/react-native-render-html#406]
Hello there,
I am using this library to display an HTML API response.

This is mathjax script tag link I want to apply to display the Math functions.
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"></script>

**### Expected Result:**
![Expeced Result](https://user-images.githubusercontent.com/68049130/92873083-4a411280-f424-11ea-8359-999f2c4cd728.png)
**### Result:**
![Result](https://user-images.githubusercontent.com/68049130/92873190-65138700-f424-11ea-9aa5-116d87a38aeb.png)

**Here's my HTML content:**
![Screenshot 2020-09-11 at 11 51 48 AM](https://user-images.githubusercontent.com/68049130/92873997-3f3ab200-f425-11ea-88fa-c4b9e592f8ad.png)

I have attached two reference screenshots, please review.
Looking forward to your response,
Thanks.

**Comment by jsamr** [comment]
@ankitaptagline If I understood you well, I think your needs would be best met with [react-native-webview](https://github.com/react-native-community/react-native-webview). Our library doesn't provide a DOM API on which you can run arbitrary JavaScript content (thus we don't support script tags), but rather a way to map html elements to React Native elements.

**Comment by jsamr** [comment]
@ankitaptagline You could also use [react-native-mathjax-svg](https://www.npmjs.com/package/react-native-mathjax-svg) with a [custom renderer](https://github.com/archriss/react-native-render-html#creating-custom-renderers) for span.

**Comment by ankitaptagline** [comment]
@jsamr, I have one other issue, multiple images are not loading and Table tag content is not showing with this.
My content are something like this,
<table border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>hshsh</td>
			<td>jsjsjsj</td>
			<td>ajajaj</td>
			<td>jajaja</td>
			<td>ajaja</td>
		</tr>
		<tr>
			<td>hjshsh</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>nanan</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>hahaha</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</tbody>
</table>

**Comment by jsamr** [comment]
@ankitaptagline Please open a new issue with a reproduction, and then I can help!

**Comment by ankitaptagline** [comment]
@jsamr, I have found your https://github.com/native-html/table-plugin#readme plugin. Thanks for your quick response.

**Comment by deepak-jha-kgp** [comment]
Hey guys, sorry for a dumb question here. How do I get the entire HTML element (entire <span .... </span>  in this case) and it's children element to use in my customer renderer.
I'm trying to use the 'children' prop but seems like it sends children after converting them into native components (<RCTView> etc).
How do I get the entire <span...</span> and it's children to send it some other webview /MathML parser?

**Comment by jsamr** [comment]
@deepak-jha-kgp Would you mind posting your question in SO? I'd like to answer, but I'd rather have the community benefit from the great visibility of SO. https://stackoverflow.com/questions/tagged/react-native-render-html

**Comment by deepak-jha-kgp** [comment]
@jsamr  Sure thing. https://stackoverflow.com/questions/63979897/extract-entire-html-element-and-its-children-in-react-native-render-html

**Comment by jsamr** [comment]
@deepak-jha-kgp I posted a sulution: https://stackoverflow.com/a/63980013/2779871
Hope that works out for you. If not, you can comment here! I also suggested changes to your original post, tell me what you think.

**Comment by deepak-jha-kgp** [comment]
@jsamr Thanks for this. Will try out the solution and ket you know.
