### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new _htmlparser.DomHandler')

### ISSUE THREAD

**Issue by amdrade** [archriss/react-native-render-html#407]
After update to `4.2.3` TypeError: undefined is not a constructor (evaluating 'new _htmlparser.DomHandler')

react: 16.9.0
react-native: 0.61.5
Device: iOS simulator iPhone 8 Plus (13.5) 

Simple code:
```jsx
return (
	<HTML
		onLinkPress={_openLink}
		html={htmlContent}
		imagesMaxWidth={imagesMaxWidth}
		tagsStyles={tagsStyles}
                baseFontStyle={{fontSize: 16}}
	/>
);
```

On Android works ...

**Comment by jsamr** [comment]
@amdrade We've seen multiple users stumbling on this with metro or your package manager (#244), if you have not done this already, I suggest you take the actions proposed here: https://stackoverflow.com/a/63111913/2779871
If that doesn't work, feel free to comment!

**Comment by amdrade** [comment]
> @amdrade We've seen multiple users stumbling on this with metro or a package manager (#244), if you have not done this already, I suggest you take the actions proposed here: https://stackoverflow.com/a/63111913/2779871
> If that doesn't work, feel free to comment!

Solve!
