### ISSUE TITLE
iframes starting with a two forward slashes src attributes are not rendered

### ISSUE THREAD

**Issue by workhub90** [archriss/react-native-render-html#408]
### Oath

I swear that I have completed these tasks before submitting:

- [x] I have read the help https://github.com/archriss/react-native-render-html/issues/137 but does'nt help.

------------
Hello archriss, please help me about this bug or some trouble.
images and text are all displayed successfully. however, only the youtube video link does not appear. any suggestions?

version package react-native-render-html@4.1.2
tested device : emulator & real device.

Here's a quick source:
......
  <View style={styles.rowContent}>
        <HTML
          html={this.props.article.description}
          baseFontStyle={styles.textContent}
          onLinkPress={(event, href, htmlAttribs) => this.props.openLink(href)}
        />
 </View>
.......

![Screenshot_2020-09-15-19-37-41-18](https://user-images.githubusercontent.com/56101357/93459282-b2539500-f90b-11ea-8dc5-699f831fe489.png)
![Screenshot_2020-09-15-19-39-37-37](https://user-images.githubusercontent.com/56101357/93459296-b67fb280-f90b-11ea-93a2-6370806dca7a.png)

**Comment by jsamr** [comment]
@workhub90 As a starting point to resolve your issue, I suggest you upgrade to the latest 4.2.3 (you'll need to install react-native-webview manually, this was an error on our end breaking semantic versioning!).

If that doesn't work out for you, I invite you to provide a full reproduction, see https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug

**Comment by workhub90** [comment]
> @workhub90 As a starting point to resolve your issue, I suggest you upgrade to the latest 4.2.3 (you'll need to install react-native-webview manually, this was an error on our end breaking semantic versioning!).
> 
> If that doesn't work out for you, I invite you to provide a full reproduction, see https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug
> 
> **EDIT**: the reproduction **must include** the HTML content that is causing trouble.

hai @jsamr thanks for fast response and give

**Comment by workhub90** [comment]
hello @jsamr  i've tried your suggestion. 
1. upgrade react-native-render-html to newer 4.2.3
2. install manually react-native-webview with this documentation 
https://engineering.brigad.co/demystifying-react-native-modules-linking-964399ec731b. i used newer version 10.9.0

is still same error. does'nt work.

i had tested in emulator & real device
 
![Screen Shot 2020-09-17 at 23 11 07](https://user-images.githubusercontent.com/56101357/93511588-442fc200-f94d-11ea-82cb-02f76e0a9aa4.png)
![Screenshot_1600366559](https://user-images.githubusercontent.com/56101357/93511597-472ab280-f94d-11ea-8d57-323fb72f1cd6.png)

**Comment by jsamr** [comment]
@workhub90 To help you out, I need to know **what** is the **HTML** code you are trying to render, that is the content of the string you are passing to html prop (this.props.article.description).

**Comment by jsamr** [comment]
I am starting to understand; I was confused because you said "the video link", so I thought you were talking about anchors (`<a>` elements). You are probably referring to an iframe element. The same remains true, cannot help you without the HTML source! This library support iframes now (will be moved out to a plugin for next major release) so I am unsure what is problematic here.

**Comment by workhub90** [comment]
@jsamr here the html i want to display.
![Screen Shot 2020-09-18 at 10 05 55](https://user-images.githubusercontent.com/56101357/93562217-cd77e080-f9af-11ea-838f-2be9c3341bc3.png)

you can see here on web everything shown. text, image and youtube video embeded.
but, when in mobile only youtube video embeded not shown.
![Screenshot_1600401237](https://user-images.githubusercontent.com/56101357/93563102-6d823980-f9b1-11ea-9e9a-cc36ea394cdd.png)

and yeah i had checked. using <iframe/> element please check images below.
but, youtube video embeded. still not shown.

**Comment by jsamr** [comment]
@workhub90 With all regards, I don't have much time to investigate this issue *as it is* right now. If you can provide a full reproduction in the form of an expo snack or git repository, I'll be willing to investigate further though. I kindly invite you to follow our contribution guidelines here: https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug

**Comment by jsamr** [comment]
@workhub90 I reviewed this issue a little further, and realized that the `iframe` src attribute is starting with two-forward slashes! Like this `//www...`. I guess we should handle this situation better. I'll try to implement a fix.

**Comment by jsamr** [comment]
@workhub90 In the meantime, you can "fix" the src attribute with `alterNode` prop.

**Comment by jsamr** [comment]
@workhub90 Version `4.2.4-beta.1` has just been released, it should work now!

**Comment by workhub90** [comment]
wow great, @jsamr  thank you for your updated. now its work.

**Comment by jsamr** [comment]
A fix has been released in v4.2.4 a few moments ago.

**Comment by skizzo** [comment]
Is there currently any way of displaying an iframe, say, for an embedded YouTube video? The docs are everything but clear on this. Thanks
