### ISSUE TITLE
How to use tagStyles property ?

### ISSUE THREAD

**Issue by enguerranws** [archriss/react-native-render-html#41]
Hi,

It seems to be a dumb question, however, I recently updated this package (from v2.xx to v3.4), which brings a lot of stuff. So first of all, thanks.

Then, I'm simply using tagStyles property:

```
<HTML
              html={I18n.t('ProfileEditCGU.content')}
              tagStyles={{
                p: {
                  color: colors.darkGray,
                  lineHeight: 1.6,
                  fontFamily: fonts.regular,
                  textAlign: 'center'
                },
                strong: {
                  marginBottom: 0,
                  color: 'red'
                } }}
              textAlign={'left'}
              onLinkPress={(evt, href) => this._onLinkPress(href)}
            /> 
```

The content I provide is a simple text wrapped with HTML tags:
```
    <p><strong>Title</strong>
    </p>
    <p>Test content.
    </p>
```

However, none of these style properties are applied. I don't know what I'm doing wrong. My only guess is I'm not using tagStyles the right way.

Any ideas?

**Comment by isaiahnixon** [comment]
I think your problem could simply be that the property is called <code>tagsStyles</code> and not <code>tagStyles</code>. Also, you should probably move your <code>textAlign</code> property definition inside of <code>tagsStyles</code>.

**Comment by Exilz** [comment]
I'm pretty sure @isaiahnixon is right.
Re-open an issue if this wasn't the issue.

**Comment by enguerranws** [comment]
@Exilz Yes, @isaiahnixon was right, just a typo :/
