### ISSUE TITLE
Some styles not working like text-decoration underline 

### ISSUE THREAD

**Issue by shalinivathra** [archriss/react-native-render-html#410]
Hi,
I have used this library its working fine. But some of the styles its not working in this library. so i used allowed styles tag. But if allow styles also text-decoration is not working.  
<html>
<head></head>
<body style="padding: 20px 100px;">

<div><p style="margin-top:0pt; margin-bottom:8pt; text-align:center; line-height:108%; font-size:11pt"><span style="font-family:Calibri; text-decoration:underline">CR-8: Training Access</span></p>

<p style="margin-top:0pt; margin-bottom:8pt; line-height:108%; font-size:11pt"><span style="font-family:Calibri; font-weight:bold">Introduction:</span><span style="font-family:Calibri"> Provide option for the crew or ship users to login to the NIBIKI shore to access the SMS and Circulars online.</span></p>

<p style="margin-top:0pt; margin-bottom:8pt; line-height:108%; font-size:11pt"><span style="font-family:Calibri; font-weight:bold; text-decoration:underline">Pre-requisite: </span></p>

<ol start="2" style="margin:0pt; padding-left:0pt" type="1">
	<li style="margin-left:31.51pt; margin-bottom:8pt; line-height:106%; padding-left:4.49pt; font-family:Calibri; font-size:11pt; font-weight:bold"><span style="font-weight:normal">Check SCEB00006. </span><span>Report shows UNRETRIEVED but recording shows, POS is RETRIEVED</span><span style="font-weight:normal">. Additionally, wrong ageing logic for this POS. RFSH Oct 4 in movement entry. POS received in Oct 7 and therefore ageing should be 3 days only </span><span>NOT 330.</span></li>
</ol>
</div>
</body>
</html>

**Comment by jsamr** [comment]
For me to investigate the issue, I need you to provide a minimal reproduction. [**What we mean by that is explained here**](https://stackoverflow.com/help/mcve).

See also [**our contribution guidelines here**](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc). Best if you could provide an expo snack or git repository; and at minima you need to provide a code snippet (no code screenshot, I don't want to retype everything!) which contains the html you're attempting to render.

I am closing now, but feel free to comment if you manage to provide a reproduction which meets our guidelines and I'll reopen.
