### ISSUE TITLE
Documenting & Question on handling <Script  type and src javascript in the HTML

### ISSUE THREAD

**Issue by BryonConley** [archriss/react-native-render-html#413]
Hi,  I am reading the documentation on this great package for the renderingf HTML.  However, I didn't see any specific section on handling tags involving <script  language-, type;,  src= />.  As in my case I have this in my HTML:
<script language="javascript" type="text/javascript" src="https://whsh4u-panel.com:2199/system/request.js"></script>

The code actually operates on the text input HTML widgets in the  html form so it is an essential and functional element to the HTML page itself.   Ssome questions include:
1. how do we handle these?
2. Can I copy the src file into my react-native project and do an import and
3.  If I can import the <script> files, how do I modify the HTML or reference within the arguments for the render-html component to operate this correctly?

This is a documentation bug, not necessarily a "functional bug" if you already have the <script> tag function already working.

Thank you very much for putting together such a high quality package for the HTML rendering purpose.

  

### Oath

I swear that I have completed these tasks before submitting:

- [ ] I have read the help guide here: https://git.io/JJ0y3
- [ ] I have read the contribution guidelines here: https://git.io/JJ0Pg
- [ ] I have read the documentation here: https://git.io/JJcAl 

------------

(Write your message here.)

**Comment by jsamr** [comment]
@BryonConley We could do a better job at clearly stating the use case for this library. react-native-render-html **does not** provide a web engine to execute JavaScript in the DOM. It barely translates HTML syntax to a native UI tree. You're probably looking for [react-native-webview](https://github.com/react-native-webview/react-native-webview).

If you need interactive elements and want to keep using this library, you can however use [custom renderers](https://github.com/archriss/react-native-render-html#creating-custom-renderers) to render your forms.
