### ISSUE TITLE
error when build android

### ISSUE THREAD

**Issue by ahmadpy888** [archriss/react-native-render-html#415]
hi, i use

"react": "16.13.1",
"react-native": "0.63.2",
"react-native-render-html": "^4.2.4",
"react-native-webview": "^10.2.3",

app/build.gradle -> multiDexEnabled true

error when run-android

`[Tue Oct 06 2020 17:35:07.236]  ERROR    Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
[Tue Oct 06 2020 17:35:07.237]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Tue Oct 06 2020 17:35:07.238]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`

**Comment by jsamr** [comment]
@ahmadpy888 There could be [many reasons unrelated to this library](https://stackoverflow.com/q/56663785/2779871). Actually, this library (version 4.2.4) does not use hooks. Won't be able to help without a reproduction. See [our contributing guidelines here](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug)!

**Comment by tkserver** [comment]
I realize this topic has been closed, but I ran into the same issue.  In case this helps anyone, my problem was that I had the <HTML....> wrapped  inside of a <TEXT>.

Bad: 

`       <View style={{flex:1, flexDirection: 'column'}}>
          <Text style={styles.topic_title}>{title}</Text>
         <Text><HTML source={{ html: content }} ignoredStyles = {['font-family']} /></Text>
        </View>`

Good: 

`       <View style={{flex:1, flexDirection: 'column'}}>
          <Text style={styles.topic_title}>{title}</Text>
          <HTML source={{ html: content }} ignoredStyles = {['font-family']} />
        </View>`
