### ISSUE TITLE
Support <table> tag

### ISSUE THREAD

**Issue by inv2004** [archriss/react-native-render-html#43]
Hello,

Does it support <table> tag ?

Thank you,

**EDIT**: [solution here](https://github.com/archriss/react-native-render-html/issues/43#issuecomment-487731497)

**Comment by Exilz** [comment]
Hi, not at the moment.
This is a good subject of pull request. We would have to add a table render to `HTMLRenderers.js`.

I think it shouldn't be *too* hard to have something working, even if it's not perfect.

**Comment by wayferer** [comment]
I can have an initial go at this @Exilz if you'd be happy to review and tidy up my code?

**Comment by Exilz** [comment]
@wayferer Yes, I'd be happy to review and improve it. However, I don't have much time right now, but I'll definitely look into it once I can.

**Comment by wayferer** [comment]
No worries. I'm jumping around a bit so it might take a while :(

**Comment by inv2004** [comment]
just found that renderers cannot find table in simple example:
```
123<p/><table><tr><td>111</td></tr></table><p/>345
```

added debug output to renderRNElements <- cannot find table also
```
D/ReactNativeJS( 5058): TEST: rawtext [123
D/ReactNativeJS( 5058): TEST: p [no_data
D/ReactNativeJS( 5058): TEST: p [no_data
D/ReactNativeJS( 5058): TEST: rawtext [345
D/ReactNativeJS( 5058): TEST: p [no_data
```

**Comment by Exilz** [comment]
@inv2004 remove `table` from the ignored tags array in [here](https://github.com/archriss/react-native-render-html/blob/master/src/HTMLUtils.js#L29)

**Comment by GopiKrishna10** [comment]
@Exilz I removed the table related tags in ignored tags array.Now it's displaying like text not like the table, for Example, see below code.

   const htmlContentLink = 
        `<table style="width:100%">
  <tr>
    <th>Firstname</th>
    <th>Lastname</th> 
    <th>Age</th>
  </tr>
  <tr>
    <td>Jill</td>
    <td>Smith</td> 
    <td>50</td>
  </tr>
  <tr>
    <td>Eve</td>
    <td>Jackson</td> 
    <td>94</td>
  </tr>
</table>`

output
=====
Firstname
Lastname
age
Jill
smith50

What should i do for rendering the table

**Comment by Exilz** [comment]
@GopiKrishna10 that's the point of the issue, it has no default renderer that handles `<table>`.
I told inv2004 to remove it from the ignored array so he can start working on making a renderer.

**Comment by GopiKrishna10** [comment]
Ok Thanks @Exilz  for your response

**Comment by Reier360** [comment]
Does anyone know if any progress has been made regarding the table tag?

**Comment by Exilz** [comment]
Not on my end, however, I'm still open to review a PR regarding this feature.

**Comment by Reier360** [comment]
@Exilz PR?

**Comment by Exilz** [comment]
@Reier360 Pull request 😄

**Comment by Reier360** [comment]
Oh wow, my bad. Sorry I have never contributed to GitHub so I am not really sure how these things work. I will go read up on the process and see if I can maybe have a swing at it.  Thanks.

**Comment by fvsch** [comment]
I don’t want to discourage anyone, but the table layout algorithm in HTML and CSS is extremely complex. And since Yoga only uses the Flexbox layout algorithm which lays out content in one direction (vs tables which auto-layout in 2 directions), mimicking a tiny subset of it will be quite hard.

Basically you would need to make all cells equal-width so that you can mimick columns.

```js
// equal-width cells, yay!
const defaultCellStyle = {
  flexBasis: 0,
  flexGrow: 1
}
```

Optionally you could look for a `width` attribute with a percentage value (old-school, I know) on the top cells and use that as the `width` for all cells in the corresponding column. That might be doable.

But be careful if your use case is showing tables made for displaying on the Web (especially on larger screens) and edited with a JS WYSIWYG editor: your chances of porting that to React Native elements are roughly zero. ;)

**Comment by jm90m** [comment]
Just want to say thanks so much for this library....

I currently use this in my app on production, "bSteem" - see here for more details (https://busy.org/@janicehung/bsteem-for-ios-and-android-newest-mobile-steemit-app)

Would be really helpful to have tables support, I understand its complex to parse out tables so I might try to fork this and submit when I have time

**Comment by Reier360** [comment]
@jm90m Hi, I also needed the table functionality, I never tried to get tables worked and It would be fantastic if someone can get it working but in my case I just used react natives webview. It has fantastic html render functionalities, and it was pretty decent when it came to rendering.

**Comment by charpeni** [comment]
I've managed to get something working quickly. Unfortunately, it's not a custom renderer, and it's not optimal. I'd prefer a version with nodes alteration, but if you want a quick solution here it is.

I've used a regex that matches all `<table>`, then replaces the `<table>` with an `<iframe srcdoc>` before they're parsed by `react-native-render-html`.

```javascript
render() {
  const { html, ...props } = this.props;

  let content = html;
  const tables = html.match(/(<table(?:.|\n)*?<\/table>)/g);
  
  tables.map((table) => {
    content = content.replace(table, `<iframe srcdoc="${tableStyle + table}"></iframe>`);
  });

  return (
    <HTML
      html={content}
      {...props}
    />
  );
}
```

**Comment by ciriac** [comment]
@charpeni Thanks for this. I'm working on a similar workaround. What does your 'tableStyle' variable look like?

**Comment by jm90m** [comment]
@charpeni awesome, workaround, I'll have to try this!

**Comment by webdevbyjoss** [comment]
Anyone knows the way to override the `IGNORED_TAGS` https://github.com/archriss/react-native-render-html/blob/master/src/HTMLUtils.js#L44 and allow `<table>` rendering without a need to fork the library?

Don't like the WebView approach, but looking to implement the custom table rendered using "react-native-table-component"

**Comment by yashojha19** [comment]
@charpeni  this regex is not working for me. :(
`/(<table(?:.|\n)*?<\/table>)/g`

**Comment by tclarke-scottlogic** [comment]
Has anyone got a solution for this:

**Comment by webdevbyjoss** [comment]
@tclarke-scottlogic by looking at the source code, it looks like we don't have a DOM at this point and all children are already pre-rendered React components. Doubtfully anything could be done here with existing renderers implementation. 

I had a __ very simple __ tables, and managed to render as on exampe above
https://github.com/archriss/react-native-render-html/issues/43#issuecomment-414986278

So in my case each `<tr>` was a `<View>` styled as flexbox row (` flexDirection: 'row',`)
 and `<td>` was rendered as just a regular `<View></View>`

**Comment by tclarke-scottlogic** [comment]
I'll give this a go, thanks. Problem is our table has about 8 columns, most of which are wide.
So I was thinking of just passing the table HTML. Not a problem, I'll just need to find a good solution for pulling out the table elements, before rendering, so I can pass them into a separate WebView or other component.

**Comment by webdevbyjoss** [comment]
The problem with tables that has a lot of columns is that those are not responsive and look ugly on mobile in portrait orientation. In that case maybe it worth to just show the cells as a stack of blocks.

For example, render each `<td>` and `<tr>` as a regular `<View>` element, making the content responsive. In that case, there will be no table but just a flat list of content.

**Comment by tclarke-scottlogic** [comment]
@webdevbyjoss Can't see that being accepted by the client. It'll be impossible to actually comprehend the content.
Throwing the table into a webview makes the most sense for their needs.

**Comment by tclarke-scottlogic** [comment]
For others to use, this produces a reasonably good quality table, with rows/columns aligned, and that you don't have to give a fixed height to get it to display.

Obviously you may need to adjust to taste, and it's very limited.

```            
renderers={{
              table: (htmlAttribs, children, style, passProps) => {
                return (
                  <ScrollView key={`table${++x}`} horizontal={true}>
                    {children}
                  </ScrollView>
                );
              },
              tr: (html, children, style, passProps) => {
                return (
                  <View
                    key={`tr${++x}`}
                    style={{
                      flex: 1,
                      flexDirection: "row"
                    }}
                  >
                    {children}
                  </View>
                );
              },
              th: (html, children, style, passProps) => {
                return (
                  <View
                    key={`th${++x}`}
                    style={{
                      width: 200,
                      backgroundColor: productColor(item.product).darker,
                      borderColor: colors.grey6,
                      borderWidth: 1
                    }}
                  >
                    <Text style={{ color: colors.white, fontWeight: "bold" }}>
                      {children}
                    </Text>
                  </View>
                );
              },
              td: (html, children, style, passProps) => {
                return (
                  <View
                    key={`td${++x}`}
                    style={{
                      width: 200,
                      borderColor: colors.grey6,
                      borderWidth: 1
                    }}
                  >
                    <Text>{children}</Text>
                  </View>
                );
              }
            }}
```

**Comment by tclarke-scottlogic** [comment]
Looking into borders, is there a good way to tell if my <th> or <td> is the last element in its parent node? I want to apply borders selectively to prevent double borders between cells.

**Comment by webdevbyjoss** [comment]
@tclarke-scottlogic the way I managed to prevent double borders is to add **top** and **left** borders for `<th>` & `<td>` elements and then **bottom** and *right* border to `<tr>` elements.

**Comment by tclarke-scottlogic** [comment]
@webdevbyjoss Surely the top of the <td> will still double up with the bottom of the <tr> above it?

I ended up using "passProps.nodeIndex === 0" to support, but your way might be cleaner code...

**Comment by tclarke-scottlogic** [comment]
@webdevbyjoss Any suggestion for how to resolve a "rowspan" tag? Crossing the <tr> DOM boundary seems *very* unlikely to be stable.

**Comment by webdevbyjoss** [comment]
yeah, `rowspan` is unlikely to be doable universally

**Comment by tclarke-scottlogic** [comment]
Thanks, at least I've updated my snippet above to support colspan.

**Comment by tclarke-scottlogic** [comment]
This is a way to use `onParsed` help with handling row spans. Basically, it detects rowspans and injects additional cells that match the spanning row.

```
function rowspanParser(dom, elements) {
  const tables = elements.filter(n => n.tagName === "table");
  if (!tables.length) return elements;
  tables.forEach(table => {
    const tbody = table.children.find(n => n.tagName === "tbody");
    if (!tbody) return;

    const rowspanColumns = {};
    for (let i = 0; i < tbody.children.length; ++i) {
      const tr = tbody.children[i];

      const rowspanners = tr.children.filter(n =>
        Object.keys(n.attribs).includes("rowspan")
      );

      const rowspanKeys = Object.keys(rowspanColumns);

      for (let k = 0; k < rowspanKeys.length; ++k) {
        const key = rowspanKeys[k];
        rowspanColumns[key].count = rowspanColumns[key].count - 1;
        if (rowspanColumns[key].count > 0) {
          const column = rowspanColumns[key].column;
          const index = rowspanColumns[key].index;
          tr.children.splice(index, 0, { ...column });
        } else {
          delete rowspanColumns[key];
        }
      }

      if (rowspanners.length > 0) {
        rowspanners.forEach(n => {
          rowspanColumns["val" + n.nodeIndex] = {
            column: n,
            index: n.nodeIndex,
            count: parseInt(n.attribs.rowspan, 10)
          };
        });
      }
    }
  });

  return elements;
}
```

**Comment by kartavyaparekh96** [comment]
Remove all tables tags from IGNORED_TAGS in HTMLUtils.js and 
```
table:{
          flex:1,
          flexDirection:'row',
          borderLeftWidth:1,
          borderTopWidth:1,
          alignItems:'center',
          justifyContent:'center',
          borderColor:'#ccc',
          borderRightWidth:0.5,
        },
        tbody:{
        },
        tr:{
          flex:1,
          borderBottomWidth:1,
          flexDirection:'row',
          borderBottomColor:'#ccc'
        },
        td:{
          justifyContent:'flex-start',
          width:'50%',
          paddingHorizontal:12,
          paddingVertical:5,
          borderRightWidth:0.5,
          borderRightColor:'#ccc',
          alignItems:'flex-start'
        },
```
only for 2 colums tables.

**Comment by webdevbyjoss** [comment]
@kartavyaparekh96 the example listed few messages earlier is more general, and works in all cases, including the 2 columns. It is because with flexbox style rule `flex: 1` you don't need to set `width:'50%'` as all cells will be evenly distributed, and it will automatically set 50% width for tables with 2 columns.

**Comment by jsamr** [comment]
[I managed to create a bridge with `react-native-webview`](https://gist.github.com/jsamr/991cc4d6ae544af24da0ad0f01534ee3) It's not optimal, since inner nodes are not natives.
But at least it's fully compliant with HTML table layout algorithm. [Video extract.](https://webmshare.com/play/43LRo)

<img src="https://user-images.githubusercontent.com/3646758/54037258-fc5ba680-41bd-11e9-8f71-7c14ba3ce63c.png" width="300" />

**Comment by nvonbenken** [comment]
@jsamr Can you provide an example of that solution being used? I'm trying to implement it myself and having issues with implementing it in my `<HTML />` .

**Comment by jsamr** [comment]
@nvonbenken I'll work on an example repo next week and share it here.

**Comment by nvonbenken** [comment]
@jsamr 

Any update on this? I'd really like to see how you accomplished this in an example.

**Comment by zehgreven** [comment]
I was able to use @jsamr stuff:

!!!! Download his files (link above) !!!!

**Imports:**
```
import HTML from 'react-native-render-html';
import { renderers } from './renderers';
import { alterNode } from './alter-node';
import { IGNORED_TAGS } from 'react-native-render-html/src/HTMLUtils';
```

**Constants**
`const tags = _.without(IGNORED_TAGS, 'table', 'caption', 'col', 'colgroup', 'tbody', 'td', 'tfoot', 'th', 'thead', 'tr');`

**render()**
```
<HTML
  html={htmlText}
  ignoredTags={tags}
  alterNode={alterNode}
  renderers={renderers}
/>
```

I don´t know why but everything I put AFTER (BELLOW) the HTML tag just don´t render...

**Comment by jsamr** [comment]
@zehgreven I embedded the table in a modal so I didn't see this bug comming. I guess you're experiencing react-native-community/react-native-webview#101!

@nvonbenken OK I'll work on something before the end of the week!

**Comment by jsamr** [comment]
@zehgreven I embedded the table in a modal so I didn't see this bug comming. I guess you're experiencing react-native-community/react-native-webview#101!

@nvonbenken OK I'll work on something before the end of the week!

**Comment by jsamr** [comment]
@zehgreven I embedded the table in a modal so I didn't see this bug comming. I guess you're experiencing react-native-community/react-native-webview#101!

@nvonbenken OK I'll work on something before the end of the week!

**Comment by jsamr** [comment]
@zehgreven I embedded the table in a modal so I didn't see this bug comming. I guess you're experiencing react-native-community/react-native-webview#101!

@nvonbenken OK I'll work on something before the end of the week!

**Comment by zehgreven** [comment]
> @zehgreven I embedded the table in a modal so I didn't see this bug comming. I guess you're experiencing [react-native-community/react-native-webview#101](https://github.com/react-native-community/react-native-webview/issues/101)!

I actly found that my <ScrollView> is not growing as much as it should :X

If i find a work arround I let you guys know.

**Comment by zehgreven** [comment]
> @zehgreven I embedded the table in a modal so I didn't see this bug comming. I guess you're experiencing [react-native-community/react-native-webview#101](https://github.com/react-native-community/react-native-webview/issues/101)!

Yep! You´re totally correct... That´s what happened... But once I fixed it this "glitch" the table just don´t show anymore, I think that I still need to find a way to grow up the screen height so it´ll have extra space to show up the table...

I let you know if I fix it.

**Comment by nvonbenken** [comment]
@jsamr  @zehgreven 

Is this working with Expo for you? In setting it up as above I'm getting this:

`Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager`

**Comment by zehgreven** [comment]
I actly wasn´t able to make it work properly, still deciding if i´ll try another soluction...

**Comment by jsamr** [comment]
@zehgreven Writing the bridge-library right now ; to circumvent the issue and avoid native dependency, I'll make WebView component an argument to the main function.

**Comment by jsamr** [comment]
:tada: Good news everyone ; I've been working on this all this day through. [`react-native-render-html-table-bridge`](https://github.com/jsamr/react-native-render-html-table-bridge) released to **npm**, with support for `onPressLink` and autoheight! :tada:

**Comment by jsamr** [comment]
@nvonbenken How is the released library working for you with Expo ?
@zehgreven would be happy if you could test

**Comment by nvonbenken** [comment]
@jsamr  Same issue as above, `Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager`

**Comment by jsamr** [comment]
@nvonbenken Did you follow the steps in the readme ? If you are using Expo SDK &le; 32, you must provide `WebView` component from `react-native`.

``` typescript
import { WebView } from 'react-native'
```

**Comment by nvonbenken** [comment]
@jsamr  Ahh good call, missed that piece. Had referenced `WebView` from `react-native-webview` by mistake. Looks good now!

Thanks a lot for making this!

**Comment by jsamr** [comment]
@nvonbenken I'll try to make the readme more Expo-friendly!

**Comment by zehgreven** [comment]
> @zehgreven would be happy if you could test

Tested and looks like it works.

I´ll try some more weird test cases as soon as I can.

Here is my code working just fine using your bridge.

``js
/* eslint-disable no-undef */
import React, { PureComponent } from 'react';
import { Linking, Dimensions, View } from 'react-native';
import HTML from 'react-native-render-html';
import WebView from 'react-native-webview';
import { IGNORED_TAGS, alterNode, makeTableRenderer } from 'react-native-render-html-table-bridge';
import MJax from './MJax';
import { Fonts, Colors } from '../../Themes';

export default class HtmlView extends PureComponent {
  render() {
    const { html, baseFontStyle = {}, containerStyle = {} } = this.props;

    const config = {
      WebViewComponent: WebView,
      tableStyleSpecs: {
        trOddBackground: '#FFFFFF',
        trEvenBackground: '#FFFFFF',
      },
    };

    const renderers = {
      table: makeTableRenderer(config),
      mathjax: (attribs, _children, _css, { key }) => (<MJax key={key} rawHtml={attribs.rawHtml} />),
    };

    const htmlConfig = {
      alterNode,
      renderers,
      ignoredTags: IGNORED_TAGS,
    };

    return (
      <View style={{ flex: 1, opacity: 0.99 }}>
        <HTML
          html={html}
          allowFontScaling
          baseFontStyle={{
            ...Fonts.style.small,
            ...Fonts.helpers.textLeft,
            ...Colors.from(Colors.black),
            ...baseFontStyle,
          }}
          containerStyle={[
            containerStyle,
          ]}
          imagesMaxWidth={200}
          imagesInitialDimensions={{
            height: Dimensions.get('window').height,
            width: Dimensions.get('window').width,
          }}
          onLinkPress={(event, href) => {
            Linking.openURL(href);
          }}
          {...htmlConfig}
        />
      </View>
    );
  }
}
``

**Comment by ashu777** [comment]
Did any one get any way  to support<table> tag

**Comment by jsamr** [comment]
@ashu777 https://github.com/archriss/react-native-render-html/issues/43#issuecomment-487731497

**Comment by hirvin-faria** [comment]
> @kartavyaparekh96 
> Remove all tables tags from IGNORED_TAGS in HTMLUtils.js and
> add this generateDefaultBlockStyles in HTMLDefaultStyles.js
> 
> ```
> table:{
>           flex:1,
>           flexDirection:'row',
>           borderLeftWidth:1,
>           borderTopWidth:1,
>           alignItems:'center',
>           justifyContent:'center',
>           borderColor:'#ccc',
>           borderRightWidth:0.5,
>         },
>         tbody:{
>         },
>         tr:{
>           flex:1,
>           borderBottomWidth:1,
>           flexDirection:'row',
>           borderBottomColor:'#ccc'
>         },
>         td:{
>           justifyContent:'flex-start',
>           width:'50%',
>           paddingHorizontal:12,
>           paddingVertical:5,
>           borderRightWidth:0.5,
>           borderRightColor:'#ccc',
>           alignItems:'flex-start'
>         },
> ```
> 
> only for 2 colums tables.


I used the solution of styles of @kartavyaparekh96, but I didn't modify the dependency files.
I used the properties tagsStyles and ignoredTags, to pass constants defined with the settings for the component properties.

```javascript
const IGNORED_TAGS = ['head', 'scripts', 'audio', 'video', 'track', 'embed', 'object', 'param', 'source', 'canvas', 'noscript',
    'caption', 'col', 'colgroup', 'button', 'datalist', 'fieldset', 'form', 'input',  'label',  'legend',  'meter', 'optgroup',
    'option', 'output', 'progress', 'select', 'textarea', 'details', 'diaglog', 'menu', 'menuitem', 'summary', 'tfoot', 'th', 'thead', ];

const TAG_STYLE = {
table:{
  flex:1,
  flexDirection:'row',
  borderLeftWidth:1,
  borderTopWidth:1,
  alignItems:'center',
  justifyContent:'center',
  borderColor:'#ccc',
  borderRightWidth:0.5,
},
tbody:{
},
tr:{
  flex:1,
  borderBottomWidth:1,
  flexDirection:'row',
  borderBottomColor:'#ccc'
},
td:{
   justifyContent:'flex-start',
   width:'50%',
   paddingHorizontal:12,
   paddingVertical:5,
   borderRightWidth:0.5,
   borderRightColor:'#ccc',
   alignItems:'flex-start'
},
}```
```html
<HTML                
html={table}
tagsStyles={TAG_STYLE}
ignoredTags={IGNORED_TAGS}
imagesMaxWidth={Dimensions.get('window').width}
/>
```

Again these solution works for two column tables as mentioned

**Comment by WilbertJanney** [comment]
> @charpeni this regex is not working for me. :(
> `/(<table(?:.|\n)*?<\/table>)/g`

I had to change the \n to \r\n to get it work.

I am trying to figure out the tablestyle part that he added now. Anyone know what goes here?
