### ISSUE TITLE
Array of around 30 to 40 pictures doesn't be rendered.

### ISSUE THREAD

**Issue by VaraderoCuba** [archriss/react-native-render-html#431]
#### Devices

- Device 1 
  * OS: 
  * Diagnostic: 
  * Environment: 

##### Description

(Write your steps here:)

1. this is my very simple code like below.

```jsx
<ScrollView = ....
<View = ...
                                <HTML
                                    html={arrDatadt.contents}
                                    contentWidth={Layout.window.width} 
                                    imagesMaxWidth={Layout.window.width}
                                    imagesInitialDimensions={{ width: Layout.window.width }}                                   
                                />
</View>
</ScrollView>
```

My array which named 'arrDatadt' would include tones of pictures like 30 to 40 with each picture's width and height about 950x1200, 190kb.
Even though my array loaded, all of my pictures doesn't renders at scrollview but around 10 to 15 pictures seen.
Thus, I just think it could be memory issue or <Image> loose its cache pic possibly.

2. I don't know if you are feel bad at my change for configuring it.
I change 'renderImage' inside of your code <Image> to use <FastImage>

```jsx
  renderImage(imageBoxDimensions) {
    const { source, style } = this.props;
    let src = source;
    src.priority = FastImage.priority.high;
    return (
      <FastImage
      priority={FastImage.priority.high}
        source={src}
        style={[defaultImageStyle, style, imageBoxDimensions]}
        testID="image-layout"
      />
    );
  }
```

Now, your 'react-native-render-html' renders all my pic , however, there is performance issue.
Page is loaded but so slow.

Hope your feed back soon.

**Comment by jsamr** [comment]
@VaraderoCuba It is impossible to investigate performance issues without a full reproduction, including the images you are trying to load, and which classes of devices are affected by the "slow rendering". Also, you didn't provide a version used for this library. I am going to close as this report doesn't follow our template. Feel free to comment if you have edited your issue to comply with [our guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc#tickets) and the template after which I'll reopen and be happy to investigate.
