### ISSUE TITLE
TagsStyles for <p> tags

### ISSUE THREAD

**Issue by aaronlinley** [archriss/react-native-render-html#44]
Setting color style on a p tag that contains children seems to throw a warning:

"Warning: Failed prop type: Invalid props.style key 'color' supplied to 'View'.

Any idea why this happens? I'm guessing there's some logic to check whether it has children and change it to a View instead of a Text component?

Is there a way to set the default of ALL text to white?

Thanks for your help.

**Comment by isaiahnixon** [comment]
@aaronlinley What ended up happening with this issue?
