### ISSUE TITLE
Large content is not loaded in html

### ISSUE THREAD

**Issue by SelvaraniAlagumuthu** [archriss/react-native-render-html#441]
Hi,
how to load large content in Html content . If we load large content in <Html html={largecontent}> app getting crash in all three platform Android , iOS and Window. Thanks

**Comment by jsamr** [comment]
Hi @SelvaraniAlagumuthu! This issue didn't follow [our contribution guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.adoc#submitting-a-bug), and I am going to close. Feel free to post a new issue while filling the required template, and providing a reproduction.
