### ISSUE TITLE
How to give number of lines based on the condition. (How to show "Read more" when using numberOfLines property?)

### ISSUE THREAD

**Issue by sankar9659** [archriss/react-native-render-html#444]
Hi, I 'm working on a react native project. I am using react native render html package for convert the html tag contents to normal text. I have to add a show more/less functionality in this content. I dont know how to give the number of lines dynamically based on the condition. The below condition is not working. Please reply this issue. Thanks in advance.
my code is,

``<HTML  html={`An iOS/Android pure javascript react-native component that renders your HTML into 100% native views. It's made to be extremely customizable and easy to use and aims at being able to render anything you throw at it.
                            `}
                            renderers={{
                                p: (htmlAttribs, children, convertedCSSStyles, { key }) => {
                                    return (
                                        <Text
                                            numberOfLines={ show more ? 3 : 1}
                                            key={key}
                                        >
                                            {children}
                                        </Text>
                                    )
                                }
                            }}
                        />`

**Comment by jsamr** [comment]
@sankar9659 This is a general question about React Native, and this place is not appropriate for such questions. I suggest you ask for help in one of the communities identified in the official website: https://reactnative.dev/help

Wish you success in your project!
