### ISSUE TITLE
Can't style some tags

### ISSUE THREAD

**Issue by enguerranws** [archriss/react-native-render-html#45]
Hi,

This sounds like a stupid question (it might be a stupid question) but I have trouble styling `<a>` and `<li>`.

Let's consider this example:

```
<p>
  Bla bla bla <a>test</a>. 
</p>
<ul>
  <li>test li</li>
</ul>
```

And these styles:
```
  li: {
  lineHeight: 24,
  fontFamily: fonts.regular,
  fontSize: 16
},
  ul: {
  lineHeight: 24,
  fontFamily: fonts.regular,
  fontSize: 16
},
  a: {
    fontFamily: fonts.regular,
    fontSize: 16,
    color: 'red'
  },
```

The issues are: 
- the `<a>` element doesn't take color property, it isn't applied (when fontSize and fontFamily are applied)
- I simply can't apply styles to `<li>` element, nothing is applied

I'm searching in the docs but can't find anything to help me. Any idea?

**Comment by Exilz** [comment]
Hi,
I don't really have time to dive more into this issue right now.

Can you try applying your `li` styles on `rawtext` and tell me if it changed something ?

I know the documentation, especially regarding new features like lists is sometimes shady.

Regarding the color of the `a` tag, I'm not sure what could be the problem.

Are you using the latest version of the plugin ?

**Comment by enguerranws** [comment]
> Are you using the latest version of the plugin ?

That was it, I was using 3.4.0, updated to 3.5.0 which works. Sorry for not checking that point.
