### ISSUE TITLE
onPress on img

### ISSUE THREAD

**Issue by butavpaul** [archriss/react-native-render-html#47]
Hi, how can I make onPress over the <img src""> I want to open a specific image from the entire article.
Thank you!

**Comment by Exilz** [comment]
Hi, you need to [create a custom renderer](https://github.com/archriss/react-native-render-html#creating-custom-renderers).

Use the various arguments it receives to render a touchable component for your specific image, and render a plain `Image` for everything else.

**Comment by butavpaul** [comment]
Hi, thank you for your message. I've tried to do something but the images doesn't appear anymore. I'm new to react and I can't figure it out why is this happening.
This is what I have now.
` render(){
        const HTMLStyles = 
        {
            h2: {fontSize:20,color: '#303235'},
            img: {marginBottom:15}
        }
        const defaultRenderer = {
            renderers: {
                img: () => <Image style={{width:90}}/>
            }
        }
        return(
            <ScrollView>
            <View>
                <View style={styles.previewContent} > 
                    <HTML
                    html={this.state.articleContent}
                    imagesMaxWidth={Dimensions.get('window').width}
                    tagsStyles={ HTMLStyles }
                    {...defaultRenderer}
                    />
                </View>
            </View>
            </ScrollView>
        )
    }`

It seems that the renderer finds the Image but it doesn't apply any props to it. I've changed <Image... to
<TouchableOpacity onPress={this._showImage()}/> but it doesn't work.
Thank you!

**Comment by Exilz** [comment]
I think you're missing the `height` attribute in your image's style.

**Comment by butavpaul** [comment]
It still doesn't work. I also get this error even if I add height.
![screen](https://user-images.githubusercontent.com/8864497/32603367-1fa20696-c552-11e7-966e-370ddde138bf.png)

**Comment by Exilz** [comment]
You're also missing your image's source, try something like this (untested, I wrote it quickly) :

```javascript
 render(){
        const HTMLStyles = 
        {
            h2: {fontSize:20,color: '#303235'},
            img: {marginBottom:15}
        }
        const defaultRenderer = {
            renderers: {
                img: (htmlAttribs, children, convertedCSSStyles, passProps) => <Image key={passProps.key} style={{width:90, height: 90}} source={{ uri: htmlAttribs.src }}/>
            }
        }
        return(
            <ScrollView>
            <View>
                <View style={styles.previewContent} > 
                    <HTML
                    html={this.state.articleContent}
                    imagesMaxWidth={Dimensions.get('window').width}
                    tagsStyles={ HTMLStyles }
                    {...defaultRenderer}
                    />
                </View>
            </View>
            </ScrollView>
        )
    }
```


Anyway, this has nothing to do with the module. Adding custom renderers is a quite advanced usage, if you're still quite new with react and react-native, it's a lot to wrap your head around.

The snippet above should be working, or almost working. Good luck with your custom implementation.

Feel free to re open a new issue if you feel like you're encountering an issue due to the module itself.

**Comment by hesusdios** [comment]
Hey i tried your code and it's almost fully working. However when I add a modal view and use the html.attribs.src as source it only loads the last <img> element in the html body. So im not able to open specific photos.

**Comment by aashish-pixere** [comment]
> You're also missing your image's source, try something like this (untested, I wrote it quickly) :
> 
> ```js
>  render(){
>         const HTMLStyles = 
>         {
>             h2: {fontSize:20,color: '#303235'},
>             img: {marginBottom:15}
>         }
>         const defaultRenderer = {
>             renderers: {
>                 img: (htmlAttribs, children, convertedCSSStyles, passProps) => <Image key={passProps.key} style={{width:90, height: 90}} source={{ uri: htmlAttribs.src }}/>
>             }
>         }
>         return(
>             <ScrollView>
>             <View>
>                 <View style={styles.previewContent} > 
>                     <HTML
>                     html={this.state.articleContent}
>                     imagesMaxWidth={Dimensions.get('window').width}
>                     tagsStyles={ HTMLStyles }
>                     {...defaultRenderer}
>                     />
>                 </View>
>             </View>
>             </ScrollView>
>         )
>     }
> ```
> 
> Anyway, this has nothing to do with the module. Adding custom renderers is a quite advanced usage, if you're still new with react and react-native, it's a lot to wrap your head around.
> 
> The snippet above should be working, or almost working. Good luck with your custom implementation.
> 
> Feel free to re open a new issue if you feel like you're encountering an issue due to the module itself.

Hey! I am tried your code and it's not working means images are disappeared without any error in code. So please let me know if there any change for current library version of HTML ("react-native-render-html": "^4.2.0").

========================
Code : 

const defaultRenderer = {
                renderers: {
                    img: (htmlAttribs, children, convertedCSSStyles, passProps) => <Image key={passProps.key} resizeMode={'contain'} source={{ uri: htmlAttribs.src }}/>
                }
            }

<HTML {...defaultRenderer} {...DEFAULT_PROPS} tagsStyles={ HTMLStyles } baseFontStyle={updateFontAndLineHeight(13, 19, this.props.fontPercent)} html={entities.decode(html)}></HTML>

**Comment by mahadevsempire** [comment]
Image is not showing, the `htmlAttribs.src `is undefined and the `passProps.key` is also undefined

![simulator_screenshot_E522409C-3970-4606-85A9-B5AF5461C0F5](https://user-images.githubusercontent.com/99904173/168871026-68da2595-09da-41ab-bdc5-4f3327482299.png)
<img width="1098" alt="Screenshot 2022-05-17 at 22 38 04" src="https://user-images.githubusercontent.com/99904173/168871116-2aefc4d2-3196-41bf-b5be-849069358960.png">

**Comment by Aiosa** [comment]
I believe the API has changed, it is more 'modern' to pass objects instead of argument list to functions, it gives the freedom of 'named arguments'
