### ISSUE TITLE
fontFamily not working on heading element

### ISSUE THREAD

**Issue by amirbayat** [archriss/react-native-render-html#527]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

custom external font family is not working on heading elements like h2 ( android device )

### React Native Information

```sh
using expo cli
```

### RNRH Version

6.1.0

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

...

**Comment by expertcoder6** [comment]
> @amirbayat Hi, and thank you for your submission! Unfortunately, you did not provide a reproduction, which is a required field, and thus this issue will be closed. There is a good chance that you didn't provide the `systemFonts` prop [as indicated in the official documentation](https://meliorence.github.io/react-native-render-html/api/renderhtmlprops#tagsstyles):
> 
> ![image](https://user-images.githubusercontent.com/3646758/137304681-04114eea-439a-4c1c-aeb6-ef8944cb83bc.png)

WORKED!!!!

**Comment by jsamr** [comment]
For anyone stumbling on this, check out the FAQ entry: https://meliorence.github.io/react-native-render-html/docs/faq#custom-font-families-dont-work-whats-happening
