### ISSUE TITLE
Styling issue on version 3.5.1

### ISSUE THREAD

**Issue by wayferer** [archriss/react-native-render-html#54]
We just updated from 3.5.0 to 3.5.1 and now all the individual tags are not picking up font size styling through `tagsStyles`. Below are some screenshots:

Before updating:
![image](https://user-images.githubusercontent.com/1575559/32675965-5c1b51d2-c61e-11e7-9e6f-a7fba665f3af.png)

After updating:
![image](https://user-images.githubusercontent.com/1575559/32675947-50f11e2c-c61e-11e7-85e0-9620bdaa451b.png)

I went into the code and removed the change (https://github.com/archriss/react-native-render-html/blob/master/src/HTML.js#L274) and the styling returns. Other styling like colour and spacing seem to carry through fine.

**Comment by rborn** [comment]
The same happens with the 3.5.2 version but the specified line seems to be fine.

Also the npm version says 3.5.2 but the git is 3.5.1

**Comment by Exilz** [comment]
Yeah, long story short, shit hit the fan.

I thought I fixed this in v3.5.1 (and I kinda did) but this introduced major regression in some cases.
Since I couldn't just remove 3.5.1 from npm, I re-published the previous version as v3.5.2... my bad.

I need more time to dig into this issue, it looks more complicated than I originally thought.

**Comment by rborn** [comment]
What would be the last version where this was working correctly?
Thanx

**Comment by Exilz** [comment]
`3.5.0` or `3.5.2` don't have those huge regressions I told you about, but this issue is definitely there. `3.5.1` is the other way around. You should use the last version published on npm.

**Comment by rborn** [comment]
@Exilz thanks a lot for the reply. I use 3.5.2 and a combinations of styles between baseFontStyle and the tagsStyles and somehow it works for my case

**Comment by soorajvnair** [comment]
Thanks a lot, was facing this issue. Great work btw :)
