### ISSUE TITLE
Request: <meta> tags support

### ISSUE THREAD

**Issue by bitfabrikken** [archriss/react-native-render-html#55]
Thanks for an incredible addon! It's super fast and easy to use.

I have a request though: I would be nice if we could include some custom meta tags.

Specifically, I need this to be able to zoom in on some HTML text.
I would use this:
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=1.0, minimum-scale=1.0, maximum-scale=2.0">
```

**Comment by Exilz** [comment]
Hi, I'm glad to hear you like this module !

I don't think it would make sense to support any meta tag. These tags offer features that are entirely tied to browsers. Most of them wouldn't have much use with native components, except, maybe the viewport one.

However, mimicking this zooming behavior would be really tedious in react-native. To be honest, I wouldn't even know where to start, and I'm not sure this would be the highest priority right now.

Maybe we could wrap the rendered nodes inside something like react-native-view-transformer, but I don't know how texts would behave while zooming. I guess they'd just become a pile of ugly pixels.

If you, or someone else, has more vision on this particular feature, I'd be happy to consider it, or review any PR.

**Comment by bitfabrikken** [comment]
The viewport meta tag works very well, at least in my device tests, for both iOS and Android. I have a RN app in production, with zero issues: https://play.google.com/store/apps/details?id=dk.krydsord.dagligkrydsen.xl - it's in Danish, but you should be able to get it or at least see the screenshots. The "zooming webview" is the crossword "player" itself.

Now, I'm making an app with song texts, primarily for an older audience, and I thought it would be nice if they could zoom in on the text by pinching (and there will also be sheet music, where it will also be important to zoom in). But on Android RN, no one has yet to make a View type that can support both zoom and scrolling in both directions. But WebView supports it out of the box, with the viewport meta tag, thus why I found your module. 

That's why I'd like to somehow inject the meta tag within your module. 
If you can point me in the right direction, I'd be happy to implement it and submit a PR.

**Comment by Exilz** [comment]
Heh.. I'm pretty sure you're using [display-html](https://github.com/archriss/react-native-display-html) not this one which is render-html.

There is no webview at all in this repo 😅

**Comment by bitfabrikken** [comment]
I am using this one, mistakingly installed the other one earlier, but I'm on display-render now :)
I was just assuming it was using WebView. Oops! :)
