### ISSUE TITLE
Can you add onLayout prop?

### ISSUE THREAD

**Issue by serhiipalash** [archriss/react-native-render-html#56]
I know that it is possible to pass onLayout with `customWrapper`, but it will be good to have it as top level prop.

<img width="805" alt="screen shot 2017-11-13 at 12 45 04" src="https://user-images.githubusercontent.com/14208343/32721833-8173cb0e-c870-11e7-9b12-e6396c0b8c1f.png">

**Comment by Exilz** [comment]
Hi, I'll make sure to add this with the next release.

**Comment by serhiipalash** [comment]
Thanks!

**Comment by Exilz** [comment]
Since the quantity of available props is kinda getting out of hand in this plugin, let's just use `customWrapper` instead of adding `onLayout` as a prop.
