### ISSUE TITLE
How to style li tag?

### ISSUE THREAD

**Issue by serhiipalash** [archriss/react-native-render-html#57]
Can you help with `<li>...</li>` tag styling?

I did not find another solution other than this

```
html={content.replace(
  new RegExp('<li[^>]*>([\\s\\S]*?)<\\/li>', 'g'),
  '<li><p>$1</p></li>'
)}

tagsStyles={{
  p: styles.contentParagraph,
}}
```

**Comment by Exilz** [comment]
Hi, try using the `rawText` fake tag in your `tagsStyles` and tell me if it allows you to style your lists properly.
The documentation regarding lists is lacking right now.

**Comment by Exilz** [comment]
Did it fix it for you ?

**Comment by serhiipalash** [comment]
```
tagsStyles={{
  rawtext: styles.contentParagraph,
}}
```

overwrites my styles for `strong` or `em`

**Comment by Exilz** [comment]
This should be fixed now that content inside `li` are styled with `baseFontStyle`. Moreover, you can apply more specific styles with `tagsStyles`. Feel free to re-open an issue if you still have problems regarding this.
