### ISSUE TITLE
Allow users to highlight text

### ISSUE THREAD

**Issue by rhysforyou** [archriss/react-native-render-html#58]
Like it says on the tin, it'd be great if users could select the rendered text, or if I could pass a prop to enable text selection.

**Comment by Exilz** [comment]
Hi, this would be a nice and easy addition for this module.

I'll try it out and add it in the next release if it's working properly without too much hassle.

**Comment by stschwar** [comment]
Hey @Exilz 
Can see that this feature didn't make what you referenced as 'next release'. What's the status? This would really be a great addition. Cheers!

**Comment by Exilz** [comment]
Ok so I looked into this and I can't make `<Text>`'s `selectable` prop work properly.

It looks like a React Native bug, so I can't add this feature for now.

[Check out the issue in rn repo](https://github.com/facebook/react-native/issues/13938)

**Comment by hyb175** [comment]
@Exilz Took a stab at it with this PR -> https://github.com/archriss/react-native-render-html/pull/85
Seems to work. Let me know if there is anything problematic with it

**Comment by Exilz** [comment]
I forgot to close this issue, but `textSelectable` prop has been added in `3.8.0`.

Keep in mind this is still problematic on iOS up to the current version of react-native (`0.53` right now).

**Comment by GopiKrishna10** [comment]
@Exilz ,

**textSelectable** Prop is selecting all the text in the screen.How should i select the specific text in the screen.Is there any solution for this 

**For example**
i have text like some thing.Which i need to select the text is **AAA**
from above text i need to select the **AAA**.if i select the **AAA** hava to show th abbrevation in tooltip.this is my requirement.For now am not able to select the specific Text.Could you please help me Guys.

Thanks

**Comment by Exilz** [comment]
@GopiKrishna10 take a look at my previous message, it isn't working properly on react-native's end.

I guess you're on iOS, and if so, it doesn't allow you to select only a part of your text for now, only the whole thing.

**Comment by GopiKrishna10** [comment]
@ExilzYes,

Am on IOS.I need to implement the Functionality in ios as well.May I know when it will be added to IOS.

**Comment by mfrna** [comment]
This is different from react-native's Text, I'm on android, and the selection boundary "flags" look different than native ones, and I don't get the default options (only copy since this is read only text), not sure if I;m missing another prop

**Comment by AnandKuhar** [comment]
How to copy the parsed result in a variable

**Comment by aqos156** [comment]
@Exilz  Hi one of the proposed fixes by react-native community for this issue is to use [this](https://github.com/facebook/react-native/issues/13938#issuecomment-520590673) fix, but we are unable to make it work with `defaultTextProps`.

![0-02-05-ae8121ea5fd71c2cee1f18735135acf546bcca003c6b12251ccb0409e5ff4327_1c6da327771a89](https://user-images.githubusercontent.com/11147374/115842808-7b53dd80-a41e-11eb-8372-8e44466841e6.png)

The fix still works with pure `<Text/>` component in rn64. Is there a limitation that we are missing?

**Comment by AryanMadhavVerma** [comment]
Having the same issue. Want to let user select a part of text and highlight it. The closest solution I've found is to use a `TextInput` instead of a `Text` and tinkering with some props like `caretHidden`, `onChangeText` etc.

**Comment by The0racle** [comment]
Was anybody able to solve this?

**Comment by paul-rinaldi** [comment]
Having same issue `textSelectable={true}` and `defaultTextProps={{selectable: true}}` on iOS. Android allows selection of text with these props though.

**Comment by paulrinaldi** [comment]
I see `textSelectable` is deprecated. Anyone have any ideas what could be going wrong with defaultTextProps.selectable = true not impacting rendered html as text on iOS?

**Comment by ceebows** [comment]
@Exilz
@jsamr pardon your inclusion.

this issue should be reopened as it is still present.
Also, `textSelectable` prop is no longer present in 6.3.4.

changelog: https://github.com/meliorence/react-native-render-html/blob/8325646fc8b39cf4ec8576b297a718ad2e1c44bc/packages/render-html/CHANGELOG.md?plain=1#L300

or at least add clarification to the issue that it is a react native bug.

see issue: https://github.com/facebook/react-native/issues/13938
