### ISSUE TITLE
I have a warning when rendering my HTML

### ISSUE THREAD

**Issue by sr3d** [archriss/react-native-render-html#59]
Warning: Failed prop type: Invalid prop `fontWeight` of value `400` supplied to `Text`, expected one of ["normal","bold","100","200","300","400","500","600","700","800","900"].
Bad object: {
  "fontWeight": 400
}
    in Text (at HTML.js:331)

The HTML contains the <b> tag.

**Comment by YeatsLu** [comment]
Two ways:
1. modify `"fontWeight": 400` to  `"fontWeight": "400"`
2. see #60

**Comment by Exilz** [comment]
Lots of issues are similar, I'm going to close this one as they're all resulting from the same problem.
