### ISSUE TITLE
Styling all text

### ISSUE THREAD

**Issue by zachdixon** [archriss/react-native-render-html#61]
Hi, I was wondering if there was an easy way to style all `<Text/>` elements, i.e. change the color.
Reading the docs, the only ways I can see of doing this would be:
- add every element to `tagStyles`
- add a custom renderer for every tag to add a class and add that to `classesStyles`

Maybe something like:
```
renderedTagStyles: {
    {text: {color: "red"}}
}
```

**Comment by Exilz** [comment]
Hi, have you tried using the `baseFontStyle ` prop ?

**Comment by zachdixon** [comment]
I saw that in the docs but it says it's a number and the default is 14 so I assumed it was just font size. Does it accept a full object of font style properties?

**Comment by Exilz** [comment]
Yes it does, I forgot to update the documentation. You guessed it, it used to be just the fontSize.

**Comment by zachdixon** [comment]
Awesome, I probably should have tried it anyway and found that it works :) Thanks

**Comment by DevAelius** [comment]
How do i increase font size at run time (e.g from state)
