### ISSUE TITLE
Lots of warning

### ISSUE THREAD

**Issue by conduongtong** [archriss/react-native-render-html#614]
### Decision Table

- [X] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

I have warnings every time I render html.
```
Task orphaned for request <NSMutableURLRequest: 0x281892080> { URL: xxx}

Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}

Did not receive response to shouldStartLoad in time, defaulting to YES
```

Does this errors have any impact?

### React Native Information

```sh
confer snack
```

### RNRH Version

6.3.4

### Tested Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

Yellow warnings

**Comment by jsamr** [comment]
Closing as no reproduction was provided, and it is unclear the provided warnings have anything to do with this lib.
