### ISSUE TITLE
Unrecognised font family openSans-light

### ISSUE THREAD

**Issue by fahadhaq** [archriss/react-native-render-html#64]
Hi any time I render my html with the above font family I am getting an error. Can you pease let me know what I am doing wrong. The html is valid as I have tested it on web page 

Thanks in advance.

**Comment by Exilz** [comment]
I'm pretty sure this is not related to this plugin. You probably didn't link your font into your project, or it's using a different name than the one you're referencing in your CSS.

Please re-open an issue with more detailed informations if you think this is actually an issue from the plugin.

**Comment by tkserver** [comment]
I just ran into a similar error.  I'm parsing HTML content from a message board into a react native app.  When using react-native-render-html and the content contains a style for a font which isn't in the system, the app crashes.  This is not something I can control. Users often copy/paste content in from other sites.  In this case there was a span with an inline style which set a specific font. Is there a way to have the html render that without crashing?

**Comment by leesolway** [comment]
@Exilz is there any way to ignore fonts specified within the html that may not be installed on the device?

**Comment by tkserver** [comment]
YES.  It isn't that in my case the developer hasn't link the font in the project.  End users are copying an pasting HTML content into a discussion forum.  That html contains inline font styles.

**Comment by leesolway** [comment]
Resolved using the following prop

ignoredStyles={['font-family', 'letter-spacing']}

**Comment by tkserver** [comment]
Confirmed!  ignoredStyles fixes it!
