### ISSUE TITLE
link's doesn't opening

### ISSUE THREAD

**Issue by FrK492** [archriss/react-native-render-html#65]
When i click on html view's link nothing is happening. I checked my html string and everything looks good on that side. Is that a bug or am i doing something wrong?

r.n version 0.49.3
react-native-render-html version 3.5.2

**Comment by Exilz** [comment]
Try using the `onLinkPress ` prop and see if you can log something from it.

Please paste your HTML string and all the props you're using.

**Comment by FrK492** [comment]
When i use onLinkPress prop all i can log out is a Proxy object.

Im using html and imagesMaxWidth props.

this is what i see when i log it.
![image](https://user-images.githubusercontent.com/32894084/33767243-e90a1032-dc31-11e7-9efc-37b1c68a4afc.png)

and this is my htm string

`<p>​​​</p><p>ŞEHİR Akademik Arşiv'de yer alan belgelerden yararlanılarak yapılacak ve&#160;<strong>basılı ve/veya elektronik ortamlarda&#160;yayınlanacak</strong>&#160;her türlü çalışmada söz konusu&#160;<strong>belgelerin hak sahiplerinden gerekli izni almak çalışmayı yapan kişi ve kurumların sorumluluğundadır.</strong>&#160;İstanbul Şehir Üniversitesi hiçbir ticari amaç gütmeksizin kamu kaynaklarının yanı sıra&#160;kendi kaynak ve imkanlarını da&#160;kullanarak sahip olduğu&#160;arşivdeki belgeleri kamuoyuna gösterme görevini yapmaktadır.&#160;</p><p>ŞEHİR Akademik Arşiv'de yer alan ancak hak sahiplerince&#160;veri tabanında&#160;gösterilmesi istenmeyen&#160;belgeler bulunduğu taktirde&#160; bu kişilerin&#160;tarafımıza yapacakları bilgilendirmeler dikkatle incelenecek ve&#160;belgenin kendisi kullanıma kapatılarak sadece belge ile ilgili bibliyografik&#160;veriler (metadata) kullanıma sunulacaktır.&#160;Halihazırda bu uygulama çeşitli belgeler için yapılmakta olup bu belgelerin yanlarında&#160;&#160;​<strong>kilit</strong>&#160;işareti bulunmaktadır ve bu belgelere erişim için özel olarak talepte bulunulması gerekmektedir.&#160;<a href="http&#58;//earsiv.sehir.edu.tr&#58;8080/xmlui/feedback">Bu linki </a>&#160;kullanarak bu&#160;konudaki taleplerinizi&#160;bize iletebilirsiniz.</p><p>Veri tabanından yararlanılarak yapılacak çalışmalarda ŞEHİR Akademik Arşiv'den yararlanıldığı bilgisinin de ilgili çalışmada gösterilmesi zorunludur.​<br></p><p style="color&#58;#333333;font-family&#58;&quot;helvetica neue&quot;, helvetica, arial, sans-serif;background-color&#58;#ffffff;"><br></p>`

**Comment by Exilz** [comment]
The `href` itself is the second argument on onLinkPressed, please read the docs.

Since you can log the event, I assume everything is working properly.

**Comment by FrK492** [comment]
thanks.

I didn't notice that href is the second argument. I solved the problem by passing that url to Linking.openURL.
