### ISSUE TITLE
JSON value 'inherit' of type NSString cannot be converted to NSNumber

### ISSUE THREAD

**Issue by hshaukatali** [archriss/react-native-render-html#66]
```
import React, {Component} from 'react';
import {View} from 'react-native';
import HTML from 'react-native-render-html';

const htmlContent = `<h3 style="margin: 0px 0px 1.25rem; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 1.25rem; line-height: 1.3; font-family: 'Open Sans', Helvetica, Arial, sans-serif; vertical-align: baseline; text-align: center;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">TEAM</strong><br />T- Together<br />E- Everyone<br />A- Achieves<br />M- More</h3>`

export default class MessageView extends Component {
    render(){
       return(
          <View>
                <HTML html={htmlContent}/>
            </View>
       )
    }
}

```

Following error was shown:

![image](https://user-images.githubusercontent.com/16544616/33880603-fabcd100-df53-11e7-9d64-ab534b7e6c81.png)

**Comment by Exilz** [comment]
Hi,
all your CSS properties like `line-height: inherit ` are transformed like so : `{ lineHeight: 'inherit' }`.
Obviously, `<Text>` expects a `number` for this prop, hence the bug.

I don't have a solution that would prevent this crash for all cases yet. If you have control over the HTML you're displaying, just remove those `inherit` in your CSS.

If you don't, you can various props such as `ignoredStyles`, `alterNode`, `alterChildren` to make sure that won't happen again.

**Comment by ryanhomer** [comment]
I'm getting a similar error and wondering why the various renderers are used. That is, if you're using a `WebView` why do you need to render some content with `Text`?

I have some fairly complicated HTML that was created by Word and it's going to be a challenge trying to figure out what to fix or ignore. This HTML may also be updated in the future; I have no control over that process.

**Comment by nadav2051** [comment]
Not sure why this issue has been closed - there is an issue on iOS where it crashes while trying to render html pasted from a Word editor or similar other editor, I get the same issue.

**font-variant: normal** on a div produces that error:
Error setting property 'fontVariant' of RCTText with tag #1483: JSON value 'normal' of type NSString cannot be converted to NSArray

**letter-spacing: normal** on a div produces that error:
Error setting property 'letterSpacing' of RCTText with tag #1483: JSON value 'normal' of type NSString cannot be converted to NSNumber

This only applies to iOS, I don't get the same experience in Android.
