### ISSUE TITLE
Html prepended with line break whenever tags are inserted

### ISSUE THREAD

**Issue by kyle-ssg** [archriss/react-native-render-html#67]
<img src="http://g.recordit.co/ueiUHCjb7I.gif"/>

The above shows the affect of html containing an <i> tag.

**Comment by kyle-ssg** [comment]
After a bit of digging I found that the content was surrounded in a <p> tag when html was added, setting the following attribute is a workaround:

```
   tagsStyles={{p: {}}}
```

**Comment by Exilz** [comment]
Yeah this is a bit tricky, we need a wrapper component (anything that maps to `Text` if all components are texts themselves) to make sure there won't be line breaks between your tags.

[Related source](https://github.com/archriss/react-native-render-html/blob/master/src/HTML.js#L192-L232)

**Comment by Exilz** [comment]
Please re-open an issue if you feel like the default behavior should be changed.

**Comment by kyle-ssg** [comment]
In my opinion, it's a caveat that will catch most people out, shouldn't the default wrapper be something else like a div without any form of styling?

**Comment by Exilz** [comment]
You're right, I'll make sure no styles are associated to this wrapper by default.

**Comment by kyle-ssg** [comment]
Cool, brilliant library by the way - very handy!
