### ISSUE TITLE
Images on Android are different from those on iOS. iOS displays normally, while Android images appear blurry

### ISSUE THREAD

**Issue by Yi-debug** [archriss/react-native-render-html#675]
### Decision Table

- [x] My issue does not look like “The HTML attribute 'xxx' is ignored” (unless we claim support for it)
- [X] My issue does not look like “The HTML element `<yyy>` is not rendered”

### Good Faith Declaration

- [X] I have read the HELP document here: https://git.io/JBi6R
- [X] I have read the CONTRIBUTING document here: https://git.io/JJ0Pg
- [X] I have confirmed that this bug has not been reported yet

### Description

I have tried all possible methods, but none of them have worked

### React Native Information

```sh
"react": "18.2.0",
 react-native": "0.73.6",
```

### RNRH Version

"react-native-render-html": "^6.3.4"

### Tested Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Reproduction Platforms

- [X] Android
- [X] iOS
- [ ] Web
- [ ] MacOS
- [ ] Windows

### Minimal, Reproducible Example

.

**Comment by jsamr** [comment]
This is a known limitation of React Native, see this comment https://github.com/meliorence/react-native-render-html/issues/404#issuecomment-824246260 

Closing since it is a React Native limitation, not particular to this library.

**Comment by buildnewapp** [comment]
I use Expo Image to render images.

```
  <RenderHtml
      contentWidth={SIZES.width-32}
      source={{html: detail?.content}}
      renderers={{
          img: (props) => {
              const { rendererProps } = useInternalRenderer('img', props);
              return <AutoSizeImage source={rendererProps.source} width={SIZES.width-32} />
          }
      }}
  />

function AutoSizeImage({source, width}){
    const [height, setHeight] = useState(width);

    function onLoad(e){
        const {width:w, height:h} = e.source
        setHeight(h*width/w);
    }

    return <Image
        source={source}
        onLoad={onLoad}
        contentFit={'contain'}
        style={{
            width: width,
            height: height
        }}
    />
}
```
