### ISSUE TITLE
How to get size image with tag?

### ISSUE THREAD

**Issue by DevToanNH** [archriss/react-native-render-html#74]
Can you help me get size of Image with tags <img or class?

**Comment by Exilz** [comment]
If I understand correctly you want to set a size for your images in your HTML ?

You can do something like that `<img style="width:100px;height:100px;" src="https://i.imgur.com/dHLmxfO.jpg" />`

If your size is bigger than the viewport of your device, it will be scaled down to make sure it's not overflowing from your app.
