### ISSUE TITLE
paddingTop, paddingBottom in containerStyle is not working

### ISSUE THREAD

**Issue by nighttiger1990** [archriss/react-native-render-html#77]
How can i set paddingTop=0 or paddingBottom=0 at containerStyle, i think children are set default marginTop and marinBottom which make wrong padding in containerStyle.

**Comment by PoojaVM** [comment]
Hey @nighttiger1990 , I think I have similar problem. Did you find any solution before closing the issue?

**Comment by mfferreira** [comment]
Same issue. How do I get rid of the top/bottom margins?

**Comment by jacobsmith** [comment]
For anyone in the future, I've been able to set negative margins via `containerStyles`. For my use case, it's almost always a single `<p>` tag being rendered - I don't know how it will stand up to other use cases.

```
containerStyle: {
  marginTop: -4,
  marginBottom: -4
}
```

The default text size is 14, so a margin of -4 leaves 10 pixels as margin. Not a "forever" solution, but good enough for some use cases
