### ISSUE TITLE
Feature proposal: Accept an uri as input?

### ISSUE THREAD

**Issue by ramsestom** [archriss/react-native-render-html#8]
Would be great if we could also provide this component a source uri rather than the html source string.
htmlparser2 seems to be able to parse a stream. So it should be feasible to add a `source` props tag to the component that would accept an uri parametter. Then the component should download, parse and render the content of this uri on the fly (rather than downloading it entirely and then render it afterward).
I don't know if it would be complicated to implement but it would be a nice enhancement ;)

**Comment by Exilz** [comment]
This would be a nice feature. I'm short on time so I won't be able to work on it for now, but I'd glady accept and review a PR for this. 👍

**Comment by Exilz** [comment]
Just to keep you posted (and other contributors who might be reading this issue), I'll add this as an experimental feature for the next release of this module.

It looks like it's working, but I'd need more time to make it production-ready. This first draft will be handy if someone wants to improve it without starting over.

I managed to load my all-time-favorite [motherfucking website](http://motherfuckingwebsite.com/)

![](https://puu.sh/xDxo7/1b4fcac666.png)

**Comment by Exilz** [comment]
This landed in `3.5.0`. It should be good enough for must use cases.

**Comment by psuslick** [comment]
Maybe I'm doing something wrong, but I have unexpected results with the code below. Can you advise?

import React, { Component } from 'react'
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  AsyncStorage,
  Dimensions

} from 'react-native'

import HTML from 'react-native-render-html';


export default class TabAmLeader extends Component {
    constructor (props) {
        super(props)
        this.state = {
        }
    }

    render () {
        return (
            <ScrollView style={{ flex: 1 }}>
                <HTML
                    html={undefined}
                    uri={'http://motherfuckingwebsite.com'}
                />
            </ScrollView>
        );
    }
}

![55982834-c3549d00-5c67-11e9-9028-a51649552484](https://user-images.githubusercontent.com/31072678/56082929-c331da00-5dec-11e9-9828-d60257c73e84.png)
