### ISSUE TITLE
Render Asset Image

### ISSUE THREAD

**Issue by ethanbrown3** [archriss/react-native-render-html#82]
Is there a way to reference an image that is stored as an asset in the project rather than a URL that would require an internet connection?
I am working on an offline first app but have used HTML to style large amounts of text that needs to be displayed but I need to add photos into the text. (It's a medical guide)

**Comment by Exilz** [comment]
I guess you can override the default `<img>` renderer and use the `src` attribute to reference the local assets you want to use.

Something like `<img src="./static/images/localImage.jpg" />`.

**Comment by ethanbrown3** [comment]
Yeah I've tried this and it doesn't find the image.

**Comment by Exilz** [comment]
I'll guess you found a way out of your problem, or a least a workaround.
Anyway, this shouldn't be a problem with the module itself.

If you feel like there is indeed a bug, please re-open.

**Comment by themakerman** [comment]
@ethanbrown3 can you share the method that worked for you?

**Comment by Exilz** [comment]
@themakerman You could create a custom renderer that does a `require()` of your asset path instead of using an url that is used as such : `source={{ uri: 'http://...' }}`.
This should work.

**Comment by themakerman** [comment]
@Exilz How do i refer the path then inside renderer? Can you write example code?
