### ISSUE TITLE
State change does not apply to baseFontStyle

### ISSUE THREAD

**Issue by baona95** [archriss/react-native-render-html#89]
Hello,

I need to apply new style to baseFontStyle after users changed their options. Are there anyway to do this?
Currently I tried:

```
<HTML
   html={chapter.content + ''}
   imagesMaxWidth={this.state.width  * 0.7 | 0}
   tagsStyles={tagsStyles}
   baseFontStyle={Object.assign({fontSize: 20, color: '#000', fontFamily: 'times'}, this.state.preset.font)}
/>
```

`this.state.preset.font` changes when users update config.

But it only work when re-render whole screen.

## UPDATE: So the easiest way I've found is to change 'key' prop of the element.

`key={this.state.key}`

**Comment by magarence** [comment]
@baona95 Where are you adding key prop, on <HTML/> or on a custom renderer?

**Comment by baona95** [comment]
@magarence The element prop

```<HTML html={data} key={this.key} />```

**Comment by Exilz** [comment]
Hi, this is a decent workaround, but as for `imagesMaxWidth` and the styles themselves, the component should re-render by itself.

I'll take a look at this problem. It bothers me a lot that I can't use hot reloading during development.

**Comment by blazk0** [comment]
@baoanhng  Man THANK YOU, i had an issue about changing number of lines in text component not rerendering.
This solved it. Thanks alot.

**Comment by hanzoow** [comment]
> @magarence The element prop
> 
> `<HTML html={data} key={this.state.key} />`

This will force HTML re-calculate in DOM and render itseft
