### ISSUE TITLE
Not read tag label

### ISSUE THREAD

**Issue by charleycesar** [archriss/react-native-render-html#90]
example  <label for="">1</label> A
    <label for="">30</label> DE CADA MÊS”. AS SOLICITAÇÕES INSERIDAS DENTRO DESTE CICLO SERÃO PROCESSADAS NO DIA
    <label for="">30</label>  DO REFERIDO MÊS, PREVENDO O DIA
    <label for="">1</label>  PARA CONTABILIZAÇÃO JUNTO AO CLIENTE.

for me all inside label come null

**Comment by nbastoWM** [comment]
@charleycesar how did you fix this? I'm getting the same problem.

**Comment by JodiRaina** [comment]
how u solve that tag label?
