### ISSUE TITLE
How can I get inner html?

### ISSUE THREAD

**Issue by saitbnzl** [archriss/react-native-render-html#91]
I'm trying to display embedded tweets. I need to show tweets in a webview. Is there a way to get inner html of nodes from a custom renderer?

**Comment by ozanmanav** [comment]
Same problem. Is there a any solution ?

**Comment by jariwalabhavesh** [comment]
@saitbnzl : Have you found a solution because I  am facing the same issue in renderer I am only able to get full HTML, not the inner one.
Can you specify how you achieved it?

**Comment by saitbnzl** [comment]
@jariwalabhavesh Hi, We've made some changes in the source code and we made it a local component (not npm dependent). 

As far as I can remember this was the only change related to this issue:
```
    mapDOMNodesTORNElements (DOMNodes, parentTag = false) {
        const { ignoreNodesFunction, ignoredTags, alterNode, alterData, alterChildren, tagsStyles, classesStyles } = this.props;
        let RNElements = DOMNodes.map((node, nodeIndex) => {
            let { children, data } = node;
            if(node.name=='blockquote'){ // this block is added
                node.innerHTML = htmlparser2.DomUtils.getOuterHTML(node);
            }
```
Then we access it like below in the renderer:

```
blockquote: {
    renderer: (htmlAttribs, node, parent, children, innerHTML) => {
      if (htmlAttribs.class == 'twitter-tweet') {
        console.log("twitter", children.rawChildren[1].parent.innerHTML)
```

**Comment by jariwalabhavesh** [comment]
@saitbnzl : I had followed your  guide. And able to see embed twitter code. But is covering too many height. Is there any way you had adjusted height of embded. I had rendered inner html inside webview.

**Comment by saitbnzl** [comment]
@jariwalabhavesh  Yes we had some with height, too. We had a solution with WebView. Try to embed tweets in [this](https://gist.github.com/saitbnzl/b3117cb3a82505a0c84574e2e0be82e3).

**Comment by jariwalabhavesh** [comment]
@saitbnzl : Thanks a lot for providing me webview code. I will try and let you know here.

**Comment by jariwalabhavesh** [comment]
@saitbnzl : Awesome, Thank you so much it works.

**Comment by jariwalabhavesh** [comment]
@saitbnzl : One more thing I had noticed that twitter embedded works perfectly in debug mode in both android and ios. But when I tried with release version then twitter embedded was not loading in android in ios it is loading fine.

Have you any idea why is it like that in android??

**Comment by saitbnzl** [comment]
@jariwalabhavesh Yes, I just have noticed this is happening in our app, too. It was fine a while ago. Idk the reason and have no time to investigate currently. Please let me know, if you can find something.

**Comment by jariwalabhavesh** [comment]
@saitbnzl : sure, I will let you if I find a solution

**Comment by jariwalabhavesh** [comment]
@saitbnzl : I put webview back with static height and it is working. So I think issue is either with message or javascript that we are injecting in smartWebView.

**Comment by jariwalabhavesh** [comment]
@saitbnzl : Finally I found solution. The main issue was **window.postMessage**. javascript was working fine and height getting fine.

To fix it I had used _[react-native-webview-bridge](https://www.npmjs.com/package/react-native-webview-bridge)_ . I am using react-native-webview-bridge version 0.40.1.

I had done little bit changes to make it work in android. Code base will be [link](https://gist.github.com/saitbnzl/b3117cb3a82505a0c84574e2e0be82e3) @saitbnzl  that you provided.

**Change injectedScript**
```
const injectedScript = function () {
  function waitForBridge() {
    if (this.WebViewBridge) {
      let height = 0;
      if (document.documentElement.clientHeight > document.body.clientHeight) {
        height = document.documentElement.clientHeight
      }
      else {
        height = document.body.clientHeight
      }
      this.WebViewBridge.send(height.toString())
    } else {
      setTimeout(waitForBridge, 600);
    }
  }
  waitForBridge()
};
```
