### ISSUE TITLE
Image can't show

### ISSUE THREAD

**Issue by DonChengCheng** [archriss/react-native-render-html#92]
if 'html' has 'img' tag, use 'react-native-render-html' to render,  i can't see picture.

**Comment by Exilz** [comment]
iOS or Android ?

**Comment by DonChengCheng** [comment]
ios发自我的iPhone------------------ Original ------------------From: Maxime Bertonnier  <notifications@github.com>Date: 周一,2月 5,2018 17:29To: archriss/react-native-render-html <react-native-render-html@noreply.github.com>Cc: Dong ChengCheng <chengchengdong20@gmail.com>, Author <author@noreply.github.com>Subject: Re: [archriss/react-native-render-html] Image can't show (#92)iOS or Android ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/archriss/react-native-render-html","title":"archriss/react-native-render-html","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/archriss/react-native-render-html"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Exilz in #92: iOS or Android ? "}],"action":{"name":"View Issue","url":"https://github.com/archriss/react-native-render-html/issues/92#issuecomment-363027884"}}}

**Comment by DonChengCheng** [comment]
Android has not problem,Only IOS has problem

**Comment by Exilz** [comment]
Then you should make sure your image's domain is in your app transport security in your xcode project.

**Comment by DonChengCheng** [comment]
Thank you, i sloved problem.
