### ISSUE TITLE
Default styles not working

### ISSUE THREAD

**Issue by matheusmatos** [archriss/react-native-render-html#96]
Hi guys,

I have used the example on readme to test the library and I can't see the default styles (h1 and h2, for example) there. Take a look:

<img src="https://user-images.githubusercontent.com/1237450/35971935-f470eca6-0cb6-11e8-98c0-7d9c7d89453f.png" width="450" />

However, I still can use the tagsStyles prop and customize the rendering.

Am I doing something wrong?

**Comment by Exilz** [comment]
Hi,
I didn't notice this bug, you're not doing anything wrong, there is a little problem with how default styles are applied to texts.

I found a potential fix but I'm wondering if this is a regression, what version of the plugin are you using ?

**Comment by matheusmatos** [comment]
Hi, thank you for fast response.

I'm using the `3.7.0` version.

**Comment by Exilz** [comment]
Can you please try [this commit](https://github.com/archriss/react-native-render-html/commit/9524401d105d0ea0a2a3d3307efbbc6c3596d961) and tell me if this is fixed for you ?

**Comment by matheusmatos** [comment]
Yey! It works!

Take a look now:

<img src="https://user-images.githubusercontent.com/1237450/35979141-b420944a-0cce-11e8-88d5-bdaaeef18325.png" width="450" />
